### ISSUE TITLE
Work with array

### ISSUE THREAD

**Issue by AliMD** [stylus/stylus#1039]
Sorry for ask this question here

I have many problem with array

for example how can create a multi dimension empty array and fill it with 2 for ?

or how can create some array like json ?

I exactly want to have a simple data base in stylus and build style with that.

we have db of font names and files and property and i want to have a perfect solution for fonts libs like google web font

Look at my repo plz https://github.com/alimd/1fonts/

I west many time on this but i cant do what in my mind.

I try to load json in stylus but its only work for simpe var not multi dimension array and objects !

how can i write js in stylus like jade ?

sorry for too many questions and my english.

**Comment by kizu** [comment]
We already have objects for some time and in 1.0.0 would have proper arrays support, so I'm closing this issue.
