### ISSUE TITLE
Parent reference is not working for nested children.

### ISSUE THREAD

**Issue by renjupaul** [stylus/stylus#1188]
<p>Docs states that: </p>

<pre><code> 
textarea
input
  color #A7A7A7
  &:hover
    color #1000 
</code>
</pre>

<p> will compiles to: </p>

<pre><code>
textarea,
input {
  color: #a7a7a7;
}
textarea:hover,
input:hover {
  color: #000;
}
</code>
</pre>

<p> But I'm having and additional nested selector that look like this: </p>

<pre><code>
.menu   
    margin-left : 30px
    color : white
    font-size : 16px
    height : 37px
    &:hover
        background-color : #808080
           .menu-drop-down
             display : block
             left: 0px
</code>
</pre>

<p> It is not compiling to what it supposed to be. Here is the compiled output: </p>

<pre><code>
.menu{
        margin-left:30px;
        color:#fff;
        font-size:16px;
        height:37px;
}

.menu:hover{
       background-color:#808080
}

.menu .menu-drop-down{
     display:block;left:0
}
</code>
</pre>

<p> I expected something like this: </p>

<pre><code>
.menu{
        margin-left:30px;
        color:#fff;
        font-size:16px;
        height:37px;
}
.menu:hover{
       background-color:#808080
}
.menu:hover .menu-drop-down{
     display:block;
     left:0
}
</code>
</pre>

<p> Is this an issue or am I miss something? </p>

**Comment by mikeevstropov** [comment]
```
.index

  &__block
    padding: 10px;

    &:hover

      ^[-1]__image
        transform: scale(1.6)
```
Expected:
```
.index__block {
  padding: 10px;
}
.index__block:hover .index__block__image {
  transform: scale(1.6);
}
```
Got:
```
.index__block {
  padding: 10px;
}
.index__block__image {
  transform: scale(1.6);
}
```

**Comment by kizu** [comment]
@mikeevstropov Whenever you use `^[]` stylus stops from prepending the `&` to the selector, so to make it render your expected code, you should mention it explicitly:

``` stylus
.index

  &__block
    padding: 10px;

    &:hover

      & ^[-1]__image
        transform: scale(1.6);
```

This would do the trick.
