### ISSUE TITLE
Spriting with Stylus

### ISSUE THREAD

**Issue by fronteed** [stylus/stylus#1200]
What do you think about including sprites compilation into Stylus?

The main advantage of the SASS is the Compass sprites. 
http://compass-style.org/help/tutorials/spriting/

Especially, my favourite function is `$icons: sprite-map('icons/*.png', $spacing: 5px)`.
Actually, this is likely the only one reason why I use SASS instead of Stylus.

Stylus would become my favourite preprocessor, once it supports sprites generation.
Would you like to be the best?

**Comment by kizu** [comment]
Closing this issue as this is out of scope for Stylus and could be better done using external tools.
