### ISSUE TITLE
Style inline SVG files

### ISSUE THREAD

**Issue by walle89** [stylus/stylus#1213]
First I want just to thank you for great work. I started to use Styles for the first time in a project a few weeks ago, and I relay love it. Especially the minimal syntax.

The only thing I missing is a way to style a SVG file in a way similar way you can in rework-svg (https://npmjs.org/package/rework-svg). 

I use this many to change fill- and stroke colors in SVG files. Example of a SVG file I use:
```xml
<svg width="100" height="87" viewBox="0 0 100 87" xmlns="http://www.w3.org/2000/svg">
    <g>
        <path fill="#000000" stroke="#000000" stroke-width="0" d="m0,86.6
  l50,-86.6
  l50,86.6
  l-100,0z" id="svg_1"/>
    </g>
</svg>
```
My idea is when you only want the SVG file without any changes, you just write:
```css
div
 background: url('arrow.svg')
```
When you need to fill the svg-file with a color, then you write:
```css
div
 background: url('arrow.svg') svg( path { fill #FEFEFE}  )
```
And if you want to change the stroke color:
```css
div
 background: url('arrow.svg') svg( path { fill #FEFEFE, stroke #FEFEFE}  )
```

The output css wold be an base64 dataUrl.

What do you think?

**Comment by kizu** [comment]
Closing this issue as this is out of scope for Stylus and could be better done using external tools.
