### ISSUE TITLE
New site for Stylus

### ISSUE THREAD

**Issue by kizu** [stylus/stylus#1242]
I'm here to say, that I'm working on the new Stylus site.

Right now the engine is almost complete (**upd: it is complete and is in production**), when all the basic stuff would be there, I'll move the site to the engine, without touching the existent content and without changing the styles. Then we could begin the rewriting of the existent docs, adding new examples, redesigning everything etc. — the new engine would make it easy and fun.

Deadline for the first sneak-peak for the site is somewhere around the first two weeks of January (somewhat far, I know, but realistic)

Below is my vision of the site, feel free to discuss anything.
## Engine

Right now the site is hosted on GitHub pages — and that's ok. But it is not using any of the nice Jekyll features — everything is built locally and then just pushed to the gh-pages branch.

I'm working on a proper Jekyll-based engine for blogs and sites that could be used for Stylus' site perfectly.

It would able us automate a lot of things for the docs and make them usable, maintainable and just awesome.
## The data

Right now the docs are in a strange state. Most of them are stored in the `gh-pages` branch, some of them are duplicated in the `docs/` of the `master` branch, and they're not synced. People don't know where to commit the changes and how to build them. We need to have only one place where the docs are stored and it should be the main repo, so people could update the docs when they update the code in one PR.

So, as the docs would be stored in `master` branch, how would they go to the `gh-pages`? Using git submodules. GitHub Pages support them, so we could just write the docs near the code and them attach them to the submodule. This way `gh-pages` won't contain any docs and there would be only an engine.
## The docs themselves

Most of the docs are somewhat generated from the jsdoc, then there were a lot of changes right in the generated files, thn some docs are hand-written from scratch etc.

I'm against using jsdoc and other autogenerated ways for main docs, as it limits what we can do in them and makes it hard to find where to fix things.

So, there should be only hand-written docs, containing useful up-to-date examples, placed in the `.md` in the `master` branch.
## Examples

@panya recently updated the client version of Stylus — http://learnboost.github.io/stylus/try.html

This means we have an ability to use it everywhere in the docs, enhancing every and each example.

Of course, that would be done in a lazy way, so even without the script you could see the `before`/`after` code, but when the script would be loaded, you could edit the `before` part to see how the `after` changes.
## Design and styles

That is not the most important thing, but it would be nice to have a new simple, but nice design for the site, and there should be some nice Stylus code inside. While I'm thinking on doing everything by myself there, you could contribute to it when I'll ship the first initial version.
## What else?

Feel free to tell what you miss in the Stylus' docs and site!

**Comment by corysimmons** [comment]
I went ahead and made an unofficial one.

http://stylus-lang.com

Don't care if you guys like it. It's better than what you have and responsive so I can finally read Stylus docs while using the bathroom.

It's generated with Jekyll using whatever is in Stylus repo's `docs` dir so I can update it from time to time.

**Comment by kizu** [comment]
@corysimmons How are you planning to update the docs there?

I guess it won't hurt to mirror the mechanism for this from https://github.com/LearnBoost/stylus/tree/gh-pages — using a submodule, leading to the `dev` branch of Stylus repo. This way when a new release with changed docs is up, you could just update the submodule and you'll get the latest docs.

Actually, if you did the same thing by forking the existing gh-pages, then you could send a PR with the changed styles and we'd merge it, but it's up to you ¯\_(ツ)_/¯

**Comment by kizu** [comment]
@corysimmons Also, if you're placing the logo for “LaunchBox” at the bottom of the right column, please, place also LearnBoost's logo too, as the copyright to the Stylus belong to them and it is rather strange.

**Comment by walkerab** [comment]
@corysimmons Good work! That looks soooo much better.

**Comment by corysimmons** [comment]
@kizu Sure thing on the LearnBoost logo. Can I get an SVG or a hi-res raster of their logo?

**Comment by corysimmons** [comment]
@walkerab Thanks

**Comment by kizu** [comment]
@corysimmons Their site is rather slow now, can't find anything better on it, so, I guess, you could use the logo from the github org's userpic, as it have transparent background: https://avatars0.githubusercontent.com/u/204174?v=3&s=200

**Comment by corysimmons** [comment]
Done

**Comment by GarthDB** [comment]
I would love to help with a new logo, would it be alright to start a new issue and we can discuss it separately?
We recently did something similar for Jade and I think it worked well. https://github.com/jadejs/jade/issues/1882

**Comment by corysimmons** [comment]
I'm pretty fond of the new logo but totally open to suggestions. @kizu your thoughts?

**Comment by GarthDB** [comment]
I'm sorry I totally missed your prototype @corysimmons it looks great. When does it ship?

**Comment by corysimmons** [comment]
I'm unsure. I made the site several months ago (http://stylus-lang.com/). I'm sure I have a todo list somewhere within these issues but I've been too busy with work to really mess with it.

I think what I have is pushed so feel free to go through issues and suss out what still needs to be done in order to get it shipped.

**Comment by GarthDB** [comment]
Ok, well I'm here to help. Happy to prod it into more action.

Also, with the logo - what would the square variation be for things like avatar images?

I worry the handscript "s" might be a bit too similar to another css preprocessor that starts with an "s".

**Comment by kizu** [comment]
I love the rabbit at Jade's logo, it would be nice to Stylus' logo to have a similar detail that could be also used for square variations for example. I'm not sure if we need to replace the latest logo (used at stylus-lang.com right now), or we could just somehow enhance it, but any ideas are welcome! If there would be completely new ideas for a logo, I guess we could look into them too, why not :)

Regarding site status: yeah, no time to get into it. But there are not that much issues left for the new site: it already uses the latest Stylus' docs via submodule and jekyll, and the only real issue left is the logo status I believe, @corysimmons? (https://github.com/stylus/stylus-lang.com/issues/4) If we could resolve the logo status, we could make stylus-lang.com to be an official url for Stylus' docs, and then start iteratively enhance and upgrade the site, slowly changing the structure, the homepage, adding live examples and stuff like that.

**Comment by groenroos** [comment]
Closing as stale. Relevant discussion for a new 2021 website redesign in stylus/stylus-lang.com#23 and stylus/stylus-lang.com#36.
