### ISSUE TITLE
enabling multi-user setup with user-override .styl files

### ISSUE THREAD

**Issue by Pomax** [stylus/stylus#1243]
I'm trying to use stylus in an express/connect multi-user setup, with all the base style files in ./public/stylesheets, but with every user able to override any file found there with their own copy from ./userdata/{{username}}/stylesheets

User routes have the username in the URL path, so it's easy to detect which content needs to be served, but I can't figure out how to tell stylus that it should compile things in ["./public", "./userdata/*/stylesheets"] to effect stylus processing in however many directories that ends up being.

Is this already built in but just not documented, or would this be a feature request, effectively for allowing the src option for the stylus middleware to be an array of locations with `glob` patterns?

**Comment by kizu** [comment]
I think this is out of Stylus scope and should be done with tools like grunt/gulp/etc, so I'm closing this issue.
