### ISSUE TITLE
add globstar (asterisk) support for imports

### ISSUE THREAD

**Issue by notslang** [stylus/stylus#1269]
It would be really nice if we could use globstars to import directories of stylus files.

For example, with a directory structure like this (from an animate.css port):

```
├── flippers
│   ├── flip.styl
│   ├── flipInX.styl
│   ├── flipInY.styl
│   ├── flipOutX.styl
│   ├── flipOutY.styl
├── lightspeed
│   ├── lightSpeedIn.styl
│   └── lightSpeedOut.styl
├── rotating_entrances
│   ├── rotateIn.styl
│   ├── rotateInDownLeft.styl
│   ├── rotateInDownRight.styl
│   ├── rotateInUpLeft.styl
│   └── rotateInUpRight.styl
├── rotating_exits
│   ├── rotateOut.styl
│   ├── rotateOutDownLeft.styl
│   ├── rotateOutDownRight.styl
│   ├── rotateOutUpLeft.styl
│   └── rotateOutUpRight.styl
├── sliders
│   ├── slideInDown.styl
│   ├── slideInLeft.styl
│   ├── slideInRight.styl
│   ├── slideOutLeft.styl
│   ├── slideOutRight.styl
│   └── slideOutUp.styl
├── specials
│   ├── hinge.styl
│   ├── rollIn.styl
│   └── rollOut.styl
├── package.json
├── bower.json
└── README.md
```

We could use `@import 'animate.css/*'` to import everything in the library, or `@import 'animate.css/sliders/*'` to get only the sliders, or `@import 'animate.css/sliders/slideInDown'` to get only the slideInDown animation.

I know that we can do this already by adding an index.styl to each folder with a list of `@import`s for files in that folder. However, that requires a lot of extra files that need to be kept in sync with any removals or additions to the directory they are in.

Edit: as @jasonkuhrt mentions below, we could use https://github.com/isaacs/node-glob for the implementation.

**Comment by hiulit** [comment]
Is this possible using the client side version of stylus? Because I'm getting an error "glob is not defined". Thanks.

**Comment by Panya** [comment]
@hiulit imports are not supported in client side version of Stylus.

**Comment by Panya** [comment]
And even if they would be supported, we can't use glob patterns there because we don't have full access to the filesystem in client side JS.
