### ISSUE TITLE
Using JavaScript API to define variables with hash values doesn't allow use of dot notation in stylesheets

### ISSUE THREAD

**Issue by jas** [stylus/stylus#1286]
I'm really enjoying the new hash support in Stylus. Thank you @Panya for all the work you did to make it happen.

I ran into an issue tonight with using `stylus.define` to set a variable in JavaScript — I might be overlooking something.

``` js
style.define('testhash', {
  a: 'value1',
  b: 'value2',
  c: {
    d: 'value 3'
  }
});
```

I would like to be able to access these values in my Stylus files using dot notation (ie `testhash.a`), but get the following error:

```
testhash has no property .a
```

When I inspect the value of `testhash` with the `p` function this is the output:

```
(a 'value1') (b 'value2') (c ((d 'value 3')))
```

Using `stylus.nodes` or `stylus.utils` is there currently a way to do this? I tried `utils.coerce` but it doesn't appear it's been updated for the new hashes.

**Comment by acidjazz** [comment]
This seems to only mainly work when specifying a colin in stylus, for instance:

```stylus
          &.c_red1
            color white
            background-color d.color.red1
 ```

Will give me an error: expected "indent", got "outdent", where as this

```stylus
          &.c_red1
            color white
            background-color: d.color.red1
 ```

compiles just fine.

**Comment by vendethiel** [comment]
That's another thing entirely, though.

**Comment by acidjazz** [comment]
Yes @vendethiel after I wrote this I dug through issues and found issue #1405 , It seems like its still outstanding and undecided. I can see how the parser can be confused but also how this puts a dent in the sugar of stylus (like not requiring colons).  Where do you think this should land?
