### ISSUE TITLE
Can't extend, if I import a stylus file from within a class

### ISSUE THREAD

**Issue by donaldpipowitch** [stylus/stylus#1381]
I have the following two sass files.

```
// fileA.styl
.test-hello {
  color: red;
}

.test-world {
  @extend .test-hello;
}
```

```
// fileB.styl
.theme {
   @import "fileA";
}
```

What I would expect, if I compile `fileB.styl`:

```
.theme .test-hello,
.theme .test-world {
  color: red;
}
```

What I get:

```
>> Error: src/style.styl:3
>>    1| .theme {
>>    2|   @import "fileA";
>>  > 3| }
>>
>> Failed to @extend ".test-hello"
```

If I use `@extend .theme .test-hello;` in `fileA.styl`, it works. But I use `fileA.styl` as a external module and I can't know beforehand, if `fileA.styl` will be imported from within a class.

Interestingly  [Less](https://github.com/less/less.js/issues/1850) and [Sass](https://github.com/nex3/sass/issues/1101) also don't work as I would expect, but every preprocessor handles this problem differently :D

**Comment by Cactusbone** [comment]
stylus now boast a Block-level import feature, so this should maybe work ?

**Comment by LouiseStroeh** [comment]
This still doesn't work, when using @extend in the file being imported

**Comment by Cactusbone** [comment]
You can use my PR if you want

**Comment by LouiseStroeh** [comment]
@Cactusbone it is working like a dream! Thank you so much

**Comment by btjones** [comment]
Any chance that PR will get approved? https://github.com/stylus/stylus/pull/2270
