### ISSUE TITLE
Comments in @import-ed files are being inappropriately suppressed

### ISSUE THREAD

**Issue by vitormil** [stylus/stylus#1389]
In `@import`ed `.styl` files, all block comments are being suppressed in the output.

There's a closed issue for that https://github.com/LearnBoost/stylus/issues/444 from 2 years ago but It's still not working.

I've created a repo to show this scenario:
https://github.com/vitormil/stylus-comment-bug

**Comment by MarkusPoparkus** [comment]
Is there a working solution without explicitly mark comments like /*! */ ?
Like @dpanov I am working with the sc5 styleguide where I urgently need comments from imported/required .styl files for my styleguide documentation.

The problem with /*! */ is that the stylus compiler can't remove them in further build tasks for production. So I need another CSS minifier to remove the persisted comments.

I would suggest an additional build flag to remove persisted comments /*! */ as well if it is needed.

**Comment by codyroot** [comment]
I agree on Markus suggestion.

**Comment by bruvvn** [comment]
+1
