### ISSUE TITLE
Multiple Parent Selectors

### ISSUE THREAD

**Issue by optikalefx** [stylus/stylus#1408]
It would be great if you could combine multiple `&` together to keep going up the tree.

Current solution

    .body
       .alert-bar
          li
             a
                color blue
     &.redalert .alert-bar li a
         color red

Proposed solution

    .body
        .alert-bar
           li
               a
                   color blue
                &&&.redalert
                   color red

In this case the page sets a class on the body for all elements to react to.
Typically this could be done in a sep `body.redalert` block repeating all selectors.

It would be really nice if we could keep the context that were in, and still reference the `body.redalert` class without repeating selectors

**Comment by kizu** [comment]
Closing as a duplicate of #1240, this would be possible using the reference selector in the future.
