### ISSUE TITLE
YAML front matter

### ISSUE THREAD

**Issue by kizu** [stylus/stylus#1434]
I wonder it such feature could be used by anyone except by me :)

We can allow `.styl` files to have YAML front matter, looking like

```
---
foo: bar
---
```

etc., it shouldn't be that hard to do and won't break things to anyone, as this throws an error right now.

Possible use-cases:

1. Such front-matter could be used for documentation purposes: instead of parsing `.styl` file using a parser, we could retrieve some info right from those front matters.

2. Files with front-matter could be seen by tools like Jekyll or DocPad, so it could be too used for documentation purposes, or for just anything else.

3. We could made the data from the front-matter to be available inside Stylus as a (local to the file scope) object variable. This could be handy, as we could then easily reuse the variables from the front matter in other tools, without using a parser for `.styl`.

4. If we'd add some more robust modules, importing and requiring, we could use the metadata from those front matters somehow.

However, as I said, this would be rather exotic feature and could be considered feature bloat. If someone have thoughts why it should be there or why not — feel free to post them there.

**upd:** here is [an example](https://github.com/docpad/docpad-plugin-stylus/issues/8#issuecomment-37666751) where the front-matter could appear in real world. When someone would add the Front Matter for their DocPad project, they make this file to be readable only by DocPad (or other tools that understand the front-matter), so if we would add support for those front matters, those files could be reused by any Stylus project.

**Comment by vendethiel** [comment]
reminds me of #784
