### ISSUE TITLE
Capture and extend another class

### ISSUE THREAD

**Issue by donpark** [stylus/stylus#149]
How do I capture and extend another class like I can with SASS?

For example, following SCSS let's me reuse a pseudo class:
    .button {
        @include fancy-button(...);
    }
    .button-active {
        @extend .button:active;
    }

**Comment by AlecRust** [comment]
One area this could be improved is when you're referencing a selector that has pseudo-classes e.g. [a clearfix solution](https://github.com/suitcss/utils-layout/blob/89003d655c8aa2b6a7f72c273ddc64c7aff1ed31/lib/layout.css#L15-L23).

`@extend .u-cf` won't work when referencing this, instead specifying each pseudo-class is required:

```css
@extend .u-cf:before
@extend .u-cf:after
```

It would be nice if `@extend .u-cf` in this case picked up any potential pseudo-classes.
