### ISSUE TITLE
Stylus linter?

### ISSUE THREAD

**Issue by andrewboni** [stylus/stylus#1501]
Hey guys, just wondering if there's any kind of linter for stylus? I did some googling, but couldn't find anything. If it doesn't exist, is there anything on the roadmap for it?

I ask because we recently switched over from LESS, which has a nice grunt plugin for linting, called [grunt-lesslint](https://www.npmjs.org/package/grunt-lesslint). Thanks!

**Comment by monolithed** [comment]
+1

**Comment by rossPatton** [comment]
i wrote a linter and would appreciate feedback: 

https://www.npmjs.com/package/stylint

Has been out a couple months now, been using it in production at work during this time with no issues.

**Comment by vendethiel** [comment]
It does seem pretty cool!

**Comment by jaeh** [comment]
stylint is very nice, solves this problem, no need to push this into stylus.

**Comment by bignimbus** [comment]
+1 for stylint - have used it in the past.

**Comment by kizu** [comment]
I'm closing this issue as there is a https://github.com/rossPatton/stylint now.

**Comment by exherb** [comment]
seems stylint  it's not maintain anymore.

**Comment by ibufu** [comment]
+1
