### ISSUE TITLE
Double parent reference (ampersand) bug

### ISSUE THREAD

**Issue by futekov** [stylus/stylus#1592]
In Stylus 0.42.0 I'm allowed to use double ampersand (with some character escaping)

```
.test
  foo: bar
  &\/&
    baz: qux
```

...and get the following:

```
.test {
  foo: bar;
}
.test.test {
  baz: qux;
}
```

However, in Stylus 0.45.0 (not sure when the regression happened exactly), the output code is:
```
.test {
  foo: bar;
}
.test/.test {
  baz: qux;
}
```

Less for example allows this even without escaping - there you can just write `&&` as a selector.

**Comment by Panya** [comment]
Fixed in 0.53.0. You can use `&&` now:
```styl
.test
  foo: bar
  &&
    baz: qux
```
