### ISSUE TITLE
json BIF to hash nested keys by default

### ISSUE THREAD

**Issue by darsain** [stylus/stylus#1606]
Currently, `json()` will flatten nested keys by joining with a dash.

For example:

``` json
{
  "foo": {
    "width": "10px"
  }
}
```

Results into `width` being accessible with `foo-width`, instead of `foo.width`. This takes away a lot of control from the developer. For example:

```
// can't use interpolation
.foo
  {foo}

// can't iterate
for key, value in foo
  {key}: value
```

And all the [other awesome hash stuff](http://learnboost.github.io/stylus/docs/hashes.html#other-stuff) like `width in foo`, `length(foo)`, `keys(foo)`, `merge(foo, bar)`.

It just makes sense for nested json structures to be represented as hashes.
### Cons

The only drawback I can think of is that people will have to use colon `:` when defining properties:

```
.bar
  width foo.width  // error, stylus confused
  width: foo.width // works
```

The confusion, if I understand it correctly, comes from stylus not being able to discern whether the `foo.width` is a hash reference, or a selector when colon is not used? Dunno, but that's the state of things, so I though it'd be worth mentioning.

_Due to this I've personally made the use of colon to be a best practice when writing `.styl` files._

---

Also, could you please document the jsob BIF? :) I've tried, but was unable to quickly  parse what are the other 2 optional arguments for, and all the ways how to use them.

**Comment by hmalaud** [comment]
Any news on this issue?
I am trying to import a json of vars and loop through the keys, which does not work. Compiling the json will crash if there are nested keys. 

`json('config.json', { hash: true })`

Compiles correctly:
`{
  "url": "aze"
}`

Does not:
`{
  "url": {
    "css": "css/",
    "dyn": "media/dyn/",
    "img": "media/img/",
    "fonts": "media/fonts/",
    "config": "config/",
    "js": "js/"
  }
}`
`Cannot read property 'lineno' of undefined`
