### ISSUE TITLE
Pattern matching for CSS properties

### ISSUE THREAD

**Issue by grayrest** [stylus/stylus#161]
The main thing I think stylus offers over less/sass is the ability to implement mixins transparently. The main problem I face with preprocessing CSS is that the designers I work with don't want to learn something on top of what they already know about CSS. Allowing them to write straight standards complianct CSS3 and have it work everywhere is therefore a huge win for me.

The main challenge in implementing this is parsing the crazy values. Consider [box-shadow](https://developer.mozilla.org/en/CSS/box-shadow):

    box-shadow:  none | <shadow> [,<shadow>]*

      where <shadow> is defined as:

    inset? && [ <offset-x> <offset-y> <blur-radius>? <spread-radius>? <color>? ]

    border-radius:   <border-radius>{1,4} [ / <border-radius>{1,4}]?

Trying to parse these using the current mixin argument parsing behavior is quite painful.

There are a couple options. At minimum, this parsing is possible if mixins are only split by commas, e.g.:

    mixin(a, b)
      ""+a+","+b

    mixin a b  // -> "a b,"
    mixin a, b // -> "a,b"

This would still make parsing difficult, but it would at least allow me to figure out where the shadows split.

Ideally, I'd like full-on pattern matching, which I would imagine looking like:

    box-shadow(inset^[indent]? x^size y^size radius^size? spread^size color^color)

The ? marks optional properties. The ^ is an (optional) type separator since in these cases the only way to distinguish whether an optional property is there or not is by the type of the argument. The [] is an | separated list of options, which would be really useful for runs of optional idents.

I'm not completely sure this should be done for all mixins since it is a fairly major change in behavior, I'd be happy if this was a built in function or something. I don't have a clear idea of exacly what I want, this is mostly just for discussion before I try to implement something.

**Comment by kizu** [comment]
While I see how such feature would be handy and I like the general idea, but it is falling slightly out of the Stylus scope, as it fits more into the post-processing. It can be rather easily implemented now using something like PostCSS, and adding it to Stylus itself would be a feature creep, so I'm closing this issue. However, if someone would come with a nice, usable and easy to comprehend PR, we would be glad to look into it :)
