### ISSUE TITLE
Creating placeholders with a loop

### ISSUE THREAD

**Issue by Karmac** [stylus/stylus#1623]
Hi everyone! I'm currently trying to create a grid system based on placeholders with stylus, which is the preprocessor I like most. 

This is my code.

```
for key, i in keys(grid-breakpoints)
    value = values(grid-breakpoints)[i]
    media = 'screen and ' + value

    @media media
        for i in 1..grid-columns
            {beginning + key + '-' + convertNumberToWord(i)}
                @extends {beginning}column
                width: calcColumnWidth(i)
                *width: calcColumnWidth(i, grid-old-ie-delta)
```

The variables.

```
grid-use-placeholders   =   true
grid-old-ie-delta       =   -0.00031
grid-decimals           =   4
grid-columns            =   12
grid-wrapper            =   950px
grid-gutter             =   24px
grid-push               =   true
grid-pull               =   true
grid-breakpoints        =   ('small' '(min-width: 35.5em)') ('medium' '(min-width: 48em)') ('large' '(min-width: 64em)')

beginning = grid-use-placeholders ? '$' : '.'
```

And finally the functions.

```
calcColumnWidth(i, adjust = 0)
    return unit(floor((i / grid-columns + adjust) * 100, grid-decimals), '%')

convertNumberToWord(num)
    for word, i in zero one two three four five six seven eight nine ten eleven twelve thirteen fourteen fifteen sixteen seventeen eighteen nineteen twenty twentyone twentytwo twentythree twentyfour
        if num is i
            return word
```

When I'm not using placeholders (normal classes instead) it works fine. Is there any workaround to fulfill my objective? Trying to use it as follows:

```
.row
    background: flat-clouds
    min-height: 300px

.sidebar
.wrapper
    background: flat-concrete
    min-height: 300px

.sidebar
    @extends {beginning}small-five

.wrapper
    @extends {beginning}small-seven
```

Thanks in advance and excuse my bad english.

**Comment by FranzSkuffka** [comment]
@Panya Is there a way to create mixins iteratively? Let's say i want to redefine layout properties <code>width</code>, <code>height</code>. Is there a way to do this?

My use case is as follows: Creating transparent mixins for layout properties that take numbers and output themselves in multiples of a grid of vw units while creating breakpoints automatically. Like this it is a breeze to create fluid UIs.
Creating these mixins iteratively would save me the bulk of code at the second half of this snipped.
<pre><code>
// grid
scale = 3

// fontsize
base = 3
msRatio = (6/5)
breakpoint = 700px
breakpoints = 1..5

scaleAttribute(attribute, args)
    {attribute} scaleTo(args)
    for stop in breakpoints
        +above(breakpoint * stop)
            {attribute} scaleTo(args, 1/(stop+1))

scaleTo(args, breakpointRatio = 1)
    yield = ''
    for arg in args
        yield = yield + (arg*scale*breakpointRatio)vw + ' '
    unquote(yield)

padding(args...)
    scaleAttribute('padding', args)
margin(args...)
    scaleAttribute('margin', args)
left(args...)
    scaleAttribute('left', args)
padding-bottom(args...)
    scaleAttribute('padding-bottom', args)
fluidWidth(args...)
    scaleAttribute('width', args)
fluidHeight(args...)
    scaleAttribute('height', args)
mfs(step)
    font-size (base*(msRatio**step))vw
    for stop in breakpoints
        +above(stop*breakpoint)
            font-size (base/(stop+1)*(msRatio**step))vw
</code></pre>

**Comment by kizu** [comment]
@FranzSkuffka There is a way to do something like that, but it's rather obscure :)

Here is an example:

``` Stylus
scaleAttribute($prop, $args)
  {$prop}: $args * 2

scaleProxy()
  scaleAttribute(called-from, arguments)

$scaledProps = 'padding', 'margin', 'left', 'padding-bottom', 'width', 'height'
for $prop in $scaledProps
  define($prop, @(){
    scaleProxy(arguments)
  })

.asd
  width: 10px
```

Would render as 

``` CSS
.asd {
  width: 20px;
}
```

The important parts are:

1. Defining transparent mixins in the global scope, as it is not yet possible to define them from a mixin in a such way (but it would be possible in the nearest future).

2. Using a proxy function that uses the `called-from` property to get the name of the function as it is not possible to just include it in the defined mixin without closures (we don't have them ATM too).

Otherwise it's a rather working way of doing such stuff :)

**Comment by FranzSkuffka** [comment]
Wow, thank you.
Can I contributo to the docs somehow? I don't think these examples really belong to the bifs section, but should be given in the docs nevertheless.
Apart from that, why is http://stylus-lang.com/ not the official documentation page?

**Comment by kizu** [comment]
Yeah, there are a lot of things to document yet. stylus-lang.com is half-official now, there are still some things to fix there till we could make it “official” and change the links everywhere to it.

**Comment by FranzSkuffka** [comment]
Is there a repo for stylus-lang.com somewhere?
Some feedback: The navigation needs to be overdone. Nested or something. you get lost easily and having to scroll through the nav itself is not overly cool.
However, if you create a list of stuff that needs to be documented I will help. Because, you know, stylus for president.

**Comment by kizu** [comment]
Here it is — https://github.com/stylus/stylus-lang.com, however the actual docs themselves are placed in the main repo — https://github.com/stylus/stylus/tree/dev/docs

We're planning to redo the site almost from scratch, and the nav would be redone too of course.

**Comment by FranzSkuffka** [comment]
Seems like a perfect use case for roots.cx, or am I mistaking here?
