### ISSUE TITLE
.css vs .styl

### ISSUE THREAD

**Issue by 131** [stylus/stylus#1650]
Vanilla css is a valid stylus syntax, and i like that. I also like to use .css as an extension, even for stylus files. But now, after player playing a little with stylus cli, i found out that .css file are NOT processed, even when using --include-css. As ".styl" is a mandatory extension for stylus files, i think the documentation should reflect that (this is NEVER stated) (and --include-css be more precise out that).
Also, this behavior is misleading, as, following the exectutable documentation, i tried to 
`stylus < someslylusfile.css > output` ,  which is working (of course)

AFAIC, i think this behavior is wrong and stylus should treat file regarding their extension (.styl, .css or .theme)

**Comment by jtremback** [comment]
I'd like to include css in my outputted bundle, as I won't be serving node_modules, and I need to import css from modules that do not use stylus.
