### ISSUE TITLE
Stylus Can't Recursively Compile

### ISSUE THREAD

**Issue by Albert-IV** [stylus/stylus#1711]
If I try to use the Stylus executable to compile, the command doesn't recognize the `**` command to recursively compile.

```
stylus views/stylesheets/** --out public/stylesheets/
```

My `views/stylesheets` directory structure:

```
-- stylesheets
|
---- some_directory
|
---- other_directory
```

I'd assume that the above command would compile `.styl` files from `/stylesheets` as well as `/stylesheets/some_directory` and `/stylesheets/other_directory` here, however this only compiles at the base-level `stylesheets` folder.
# EDIT

It appears as though it does go into the subdirectories, however it outputs those files to the `public/stylesheets` directory rather than `public/stylesheets/some_directory`.

**Comment by tannerlinsley** [comment]
Just to make sure, before I start developing the PR, this would basically be a feature to support glob stye imports eg. `my/recursive/stylesheets/**` would recursively import stylus files in that directory?

**Comment by Panya** [comment]
@tannerlinsley we already support imports with globbing. This issue is about CLI and preserving directory structure if we're using `--out` flag and multiple files.

**Comment by tannerlinsley** [comment]
I see. Can you point me to an example of a recursive import? I know the *
can be used to get every file in a directory. But as far as I can tell, it
will not traverse deeper than one level.

**Comment by Panya** [comment]
Well, suppose we have a directory with our `.styl` files (`./test/`):
`tree test`
```
test
├── a
│   └── a.styl
├── b
│   └── b.styl
└── c
    ├── c.styl
    └── d
        └── d.styl
```
Each file in the `test` dir contains something like:
```styl
body
  content: 'from <a>/<b>/<c>...'
```
And main file `./main.styl`:
```styl
@import 'test/**/*'
```
Then after compiling the main file with `stylus main.styl` we will get:
`main.css`
```css
body {
  content: 'from a';
}
body {
  content: 'from b';
}
body {
  content: 'from c';
}
body {
  content: 'from d';
}
```
Looks like all is working fine.

**Comment by tannerlinsley** [comment]
Wow. A lot of people I know including me obviously didn't know this. That's
spectacular. I'll give it a whirl tomorrow in my project. I would love to
ditch stylus-import-tree
