### ISSUE TITLE
Stylus transforms special comment blocks

### ISSUE THREAD

**Issue by Todd-Werelius** [stylus/stylus#1763]
I noticed that stylus transforms 'special' comment blocks 

``` javascript
/*!
*
*/
```

stylus turns this into 

```
/*
*
*/
```

This keeps clean-css, gulp-minify-css etc. from recognizing it as a special comment, just wondering why it does this and if there is anyway to disable it?

**Comment by jakubpawlowicz** [comment]
@Panya the page you point to says: "Multi-line comments which are not suppressed start with /*!. This tells Stylus to output the comment regardless of compression." - this means user should not need to add a 2nd `!` to preserve comment internals.
