### ISSUE TITLE
May the doc column be "wider"?

### ISSUE THREAD

**Issue by ibc** [stylus/stylus#1764]
Any reason for having the documentation in a single ~375px width column? It is unreadable in most of the sections (example: the "Executable" section).

http://learnboost.github.io/stylus/docs/executable.html

**Comment by sebaestel** [comment]
If you need help to redesign the stylus page, I can help

**Comment by PalleZingmark** [comment]
Make the source available for pull requests, and let users rebuild and submit a new design.

**Comment by Panya** [comment]
@PalleZingmark all the sources already available [here](https://github.com/learnboost/stylus/tree/gh-pages) and [here](https://github.com/stylus/stylus-lang.com) (new design). Feel free to send a PR.

**Comment by PalleZingmark** [comment]
@Panya So it seems I really am half asleep, didn't look in the right places. Thank you. :)

**Comment by cssmagic** [comment]
@Panya 
The "website" field needs to be update to the new official site.

![website](https://cloud.githubusercontent.com/assets/1231359/11264733/073bf878-8ed1-11e5-935e-68caf159e9b0.png)
