### ISSUE TITLE
Unexpected Behaviour with @extends

### ISSUE THREAD

**Issue by srsgores** [stylus/stylus#1795]
I have the following placeholder:

```
$formField
    box-sizing border-box
    padding $formFieldPadding
```

When I `@extend` that placeholder to existing classes:

```
.form
    &-section
        &-horizontal
            @extend $formField
        &-vertical
            @extend $formField
```

I expect that that placeholder can be re-introduced and modified like so:

```
.form
    &-section
        &-grid
            $formField
                display table-cell
        &-inline
            $formField
                display inline-block
```

Because the selector `.form-section-horizontal` and `form-section-vertical` were initially extended, I would expect the placeholder to act as an intermediary selector, resulting in such a combined selector: 

```
.form-section-grid .form-field,
.form-section-grid .form-field-horizontal,
.form-section-grid .form-field-vertical {
  display: table-cell;
}
.form-section-inline .form-field,
.form-section-inline .form-field-horizontal,
.form-section-inline .form-field-vertical {
  display: inline-block;
}
```

However, no such selector is reproduced.

[Codepen here](http://codepen.io/srsgores/pen/LEbpRO).

**Comment by srsgores** [comment]
@Panya, in SASS, my experience has been that something like this works:

```
$column
	display table-cell

.one-half, .one-quarter
	@extend $column

.row
	@media only screen and (max-width: 767px)
		$column
			display block
```

I would expect this:

```
.one-half,
.one-quarter {
	display: table-cell;
}

@media only screen and (max-width: 767px) {
	.row .one-half, .row .one-quarter {
		display: block;
	}
}
```

But this does not work.  I get:

```
.one-half,
.one-quarter {
  display: table-cell;
}
```

The above works in SASS, starting 3.2.

**Comment by Panya** [comment]
Your example with `@media` doesn't work in Stylus, because Stylus currently extends only the exact selector. Inside the `@media` you have `.row $column` but you tries to extend `$column`.  Sass on the other hand extends all possible selectors that contains `%column`. We have an issue for `@extend-all` semantic support (like in Sass), see #1238.
