### ISSUE TITLE
This should work

### ISSUE THREAD

**Issue by reduxdj** [stylus/stylus#1875]
figure
      display block
      position absolute
      width 725px
      height 725px
      font-size 120px
      font-weight bold
      color white
      text-align center
      backface-visibility hidden
      &.front
        transform translateZ(362px )
        background hsla(   0, 100%, 50%, 0.7 )
      &.back
        transform rotateX( -180deg ) translateZ( 362px )
        background hsla(  60, 100%, 50%, 0.7 )
      &.right
        transform rotateY(   90deg ) translateZ( 362px )
        background hsla( 120, 100%, 50%, 0.7 )
      &.left
        background hsla( 180, 100%, 50%, 0.7 )
        transform rotateY(  -90deg ) translateZ( 362px )
      &.top
        background hsla( 240, 100%, 50%, 0.7 )
        transform rotateX(   90deg ) translateZ( 362px )
      &.bottom
        transform rotateX(  -90deg ) translateZ( 362px )
        background hsla( 300, 100%, 50%, 0.7 )

I have to remove the &, an unindent the transforms to work

**Comment by kizu** [comment]
Well, actually, it works, you can try in at http://learnboost.github.io/stylus/try.html or codepen. Are you sure you don't have mixed indents (spaces and tabs) in your input? If not, which stylus version do you use?

**Comment by Panya** [comment]
I'm pretty sure that it works.
