### ISSUE TITLE
Interpolation inside an attribute selector

### ISSUE THREAD

**Issue by joeldrapper** [stylus/stylus#1876]
It would be great if we could interpolate into attribute selectors, i.e.

```
$foo = bar
[class*='{foo}']
```

Output

```
[class*='bar']
```

**Comment by Panya** [comment]
Yep, it will be possible in 1.0 (#728). Meanwhile, you can escape the quotes:
```styl
$foo = bar
[class*=\'{foo}\']
```
=>
```css
[class*='bar']
```
