### ISSUE TITLE
Strange call in middleware

### ISSUE THREAD

**Issue by dresende** [stylus/stylus#1878]
I was using stylus middleware at version `0.47.0`. When I upgraded to latest (`0.50.x`) my styles stopped working. I then found that I could upgrade to `0.47.1` but no more than that. I then found the culprit but I want to first show you a behaviour:

```js
var express = require("express");
var stylus  = require("stylus");
var http    = require("http");
var app     = express();
var server  = http.createServer(app);

app.use("/public", stylus.middleware({
	src : function (path) {
		console.log("src(%s)", path);
		return path;
	},
	dest : function (path) {
		console.log("dest(%s)", path);
		return "/whatever" + path;
	},
	compile : function (str, path) {
		return stylus(str).set("filename", path);
	}
}));

server.listen(3000);
```

Save this to a file, install the dependencies on top and run it. No need for an actual `/public` folder, just run it and in a different terminal run `curl http://localhost:3000/public/xpto.css`. What do you see? I see this:

```sh
~ master ✎ › node test-file.js
dest(/xpto.css)
dest(s)
src(s)
```

In my application I actually see `dest()` and then it just throws an `EISDIR`. The problem goes away when I go to [lib/middleware.js#L122](https://github.com/stylus/stylus/blob/master/lib/middleware.js#L122) and remove the second condition. It's weird, I'm not sure what that block should do..

Any help is appreciated as I might be doing something wrong. I use the middleware with custom functions as I have a "layered file system" and sometimes the path depends on the filename so it's not straightforward.

**Comment by Panya** [comment]
Actually it is a bug. Thanks for the report. I've fixed it in the `dev` branch. The fix will be in the next release.

**Comment by dresende** [comment]
I thought that too, but as I didn't understand the condition (with the function), I asked. Thank you for the quick fix :)
