### ISSUE TITLE
json() BIF converts strings to idents

### ISSUE THREAD

**Issue by maranomynet** [stylus/stylus#1885]
I have an `icons.json` file:

```json
{
  "menu": ""
}
```

but when I use it, like so:

```stylus
$icons = json('icons.json', { hash:true });
.menu:before {
    content: $icons.menu;
}
```

This is what I get:

```css
.menu:before {
    content: ;
}
```

which breaks the CSS since `content` value should be quoted.

Is there a way to instruct `json()` BIF to leave Strings as is?

My current workaround is this icky hack:

```stylus
for ($n,$c in $icons) { $icons[$n] = ''+$c; }
```

**Comment by Panya** [comment]
Nope, but here is another workaround:
```json
{
  "menu": "''"
}
```

**Comment by maranomynet** [comment]
Double wrapping isn't an option since I'm also consuming the JSON elsewhere.

**Comment by maranomynet** [comment]
Seems like it should be possible to add an option to instruct the  `json` BIF to leave  Strings as is.

**Comment by Panya** [comment]
@maranomynet yep, I added `leave-strings` option in the `dev` branch:
```styl
$icons = json('icons.json', { hash: true, leave-strings: true })

.menu:before {
    content: $icons.menu; // ''
}
```

**Comment by maranomynet** [comment]
Nice! Thanks.
