### ISSUE TITLE
Hash values break compile unless used with colon

### ISSUE THREAD

**Issue by aharris** [stylus/stylus#1888]
If you use a hash as a value and it is not the last property or does not have a semicolon it breaks the selector.

EX:

```
foo = {
  bar: baz,
  baz: raz
}

body
	background foo["baz"]
	color red
```

Won't output anything.

However,

```
foo = {
  bar: baz,
  baz: raz
}

body
	background: foo["baz"]
	color red
```
Outputs correctly as:

```
body {
  background: raz;
  color: #f00;
}
```

Obviously this is an easy workaround (just use the semicolon). Just wanted to point it out.

**Comment by Panya** [comment]
Duplicate of #1405, please use colons.
