### ISSUE TITLE
Variables in @import

### ISSUE THREAD

**Issue by skamaraj** [stylus/stylus#1890]
Does stylus support variables in imports? I do not see it documented in the stylus documentation. If it is not supported, is there a work around for this? Can it be added as enhancement?

**Comment by Panya** [comment]
Yep, but we don't support string interpolation yet (see #728), so you should use concatenation. For example:
```styl
foo = 'some-dir'

@import 'bar/' + foo + '/baz.styl'

quz()
  return foo + '/some-file.styl'

@import quz()
```
