### ISSUE TITLE
Global hash (`window` à la js)

### ISSUE THREAD

**Issue by Calvein** [stylus/stylus#1891]
I was thinking of this feature some times ago but I never really made an issue about it. I've seen myself doing this for quite a lot of projects (that's a real life project made a year ago, with the colors actually comming from a json file):

```stylus
builders = #222
boomers = #444
genx = #666
geny = #888

generationColors = {
    builders: builders
    boomers: boomers
    genx: genx
    geny: geny
}

// Generations cards
for gen, color in generationColors
    [data-card={gen}]
        background color
```

or

```stylus
play = 'base64thing'
pause = 'base64otherthing'

images = {
    play: play
    pause: pause    
}

getImage(image)
    url('data:image/svg+xml;base64,' + images[image])
```
<sup>(yay stylus support in GFM \o/)</sup>

Since Stylus is relatively close to JS, I was wondering if there, or we can have, an equivalent to `window` or `global`, so in my examples I wouldn't have to duplicate useless code (I'll have a map instead of an hash in the first one, and in the second I wouldn't even need a map).

**Comment by Panya** [comment]
Seems like use cases for `lookup` BIF (http://learnboost.github.io/stylus/docs/bifs.html#lookupname).

**Comment by Calvein** [comment]
That's perfect, thanks.
