### ISSUE TITLE
Cannot use 'transparent' with blend() (and probably other functions)

### ISSUE THREAD

**Issue by rimas-kudelis** [stylus/stylus#1894]
When trying to use `blend (transparent, #color)`, I get the following error:

    TypeError: expected rgba or hsla, but got ident:transparent

Meanwhile, `blend (white, #color)` works. It would be nice if `transparent` was also a simple predefined color, just like `white`.

To not mess up color addition and subtraction, it should probably be defined as `rgba(0, 0, 0, 0)`.

**Comment by Panya** [comment]
Thanks. I've added this named color in the `dev` branch. It will be in the next release.

**Comment by rimas-kudelis** [comment]
thank you!
