### ISSUE TITLE
Access to protected scope (property lookup from inside @extend)

### ISSUE THREAD

**Issue by Wexcode** [stylus/stylus#1898]
I'd like to find a way to reference a property from an extended selector. Unfortunately, [property lookup](https://learnboost.github.io/stylus/docs/variables.html#property-lookup) doesn't seem to work for this:

    .foo
      font-size 12px
    .bar
      @extends .foo
      line-height @font-size * 2

    /* Output */
    .foo,
    .bar {
      font-size: 12px;
    }
    .bar {
      line-height: ;
    }

I realize the issue is that font-size is not defined within `.bar`'s scope, but I think it makes sense to give access to the "protected" scope of `.foo` (the selector that is being extended).

**Comment by Panya** [comment]
Sorry, It's not possible currently because `@extend` is evaluated after the property lookup.
