### ISSUE TITLE
Flexbox issues

### ISSUE THREAD

**Issue by xzabitor** [stylus/stylus#1899]
Hello, 

Every-time I try to compile something with flex, IE flex: 1, I get display: flex  instead and other attributes

Here is example:

```css
flexitem()
  -webkit-box-flex arguments     
  -moz-box-flex arguments        
  -webkit-flex arguments       
  -ms-flex arguments             
  flex arguments               
  align-items center

li
  flexitem(1)
```

Outputs

```css
li
  -webkit-box-flex: 1;
  -moz-box-flex: 1;
  -webkit-flex: 1;
  -ms-flex: 1;
  display: -webkit-box;
  display: -moz-box;
  display: -ms-flexbox;
  display: -webkit-flex;
  display: flex;
  align-items: center;
```

Tried adding in : ; with no luck, ie

```css
flexitem()
  -webkit-box-flex: arguments;    
  -moz-box-flex: arguments;       
  -webkit-flex: arguments;       
  -ms-flex: arguments;       
  flex: arguments;    
  align-items: center;
```

Not using the mixin and instead using just the CSS does the same thing.

However when i use @CSS it works

IE
```css
@css {
  -webkit-box-flex: 1;     
  -moz-box-flex: 1;      
  -webkit-flex: 1;      
  -ms-flex: 1;            
  flex: 1; 
}

**Comment by Panya** [comment]
Seems like you have a `flex` mixin defined somewhere in your code.
```styl
flex()
  display: -webkit-box
  display: -moz-box
  display: -ms-flexbox
  display: -webkit-flex
  display: flex
```
Remote it and all will be fine. This feature is called [transparent mixins](http://learnboost.github.io/stylus/#how-about-transparent-mixins). See http://learnboost.github.io/stylus/docs/mixins.html for more information.
