### ISSUE TITLE
Can we add support for non-standard at-rules so PostCSS is happy?

### ISSUE THREAD

**Issue by corysimmons** [stylus/stylus#1900]
The way to assign global vars in PostCSS from your CSS (.styl) is `@your-lib-name your-setting your-settings-value`.

Stylus throws a breaking error when it hits a non-standard at-rule. Is there any way we can just have it fail silently so it works with PostCSS at-rules?

https://github.com/postcss/postcss/issues/306

**Comment by kizu** [comment]
Actually, Stylus supports non-standard at-rules, but have a bug when the at-rule don't have a body. As a temporarily workaround you could just write `{}` after your at-rule like this:

``` styl
@your-lib-name your-setting your-settings-value{}
```

and it would render as

``` css
@your-lib-name your-setting your-settings-value
```

**Comment by Panya** [comment]
Thanks for the report @corysimmons. I've added support of blockless unknown at-rules in the `dev` branch. It will be in the next release.

**Comment by corysimmons** [comment]
Tried updating and it seems to work better but it's still broken it seems:

```stylus
@lost gutter 1000px

html, body
  width: 100%
  height: 100%
  margin: 0
  padding: 0
  font-size: calc( 20px + (8) * ( (100vw - 36em) / (120em - 36em) ))
  background-color: white

.column-third
  lost-column: 1/3
```

Results in:

```css
.column-third {
  width: calc(99.99% * 1/3 - (1000px
html,
body - 1000px
html,
body * 1/3));
```

**Comment by Panya** [comment]
@corysimmons nope, you can try it yourself at http://learnboost.github.io/stylus/try.html

**Comment by corysimmons** [comment]
It seems like Stylus is erasing the semi-colon on the end of at-rules. If I manually add it and escape it, it seems to work: `@lost gutter 1000px \;`

**Comment by corysimmons** [comment]
Can we add a semi-colon on the end of all at-rules?

**Comment by Panya** [comment]
Yep this is fixed in the `dev` branch. Meanwhile you can use `--compress` flag to get compressed output with `;` at the end of these at-rules.

**Comment by corysimmons** [comment]
Awesome, thank you @Panya You're a hero!

**Comment by corysimmons** [comment]
Out of anxiousness, ETA on 0.52?

**Comment by kizu** [comment]
0.52 would be there when there would be enough stuff for it, meanwhile, released this fix (alongside another one) as a patch release: stylus@0.51.1

**Comment by corysimmons** [comment]
Awesome thanks for the help @kizu

**Comment by corysimmons** [comment]
Is this problem back? Can't seem to get CodePen to play nice with it http://codepen.io/corysimmons/pen/rxpywP?editors=110

**Comment by ericimthorn** [comment]
I solved it by typing `@lost gutter 14px{ html: '' };`

**Comment by corysimmons** [comment]
@ericimthorn That's hacky/ugly. Why not just upgrade Stylus?

**Comment by ericimthorn** [comment]
@corysimmons You're right. It's more of a temporary workaround. I'm using the npm packages poststylus and gulp-stylus. Will properly fix it eventually.

**Comment by corysimmons** [comment]
Cool, it's PostStylus, not Gulp Stylus. https://github.com/seaneking/poststylus/blob/master/package.json#L33

I'll ping him about it. =)

**Comment by corysimmons** [comment]
@ericimthorn Fixed. https://github.com/seaneking/poststylus/commit/798f8a9ae664059a89c09f6e2400d8131f74b795

Update your PostStylus

**Comment by ericimthorn** [comment]
@corysimmons Awesome!
