### ISSUE TITLE
Can we define variables with variable names in Stylus?

### ISSUE THREAD

**Issue by skamaraj** [stylus/stylus#1901]
For example in LESS, we could do something like this
@fnord:  "I am fnord.";
@var:    "fnord";
content: @@var;

Can we achieve similar style in Stylus? I tried it but could not do it. Is there a work around or possible enhancement?

**Comment by Panya** [comment]
Yep, see [lookup](http://learnboost.github.io/stylus/docs/bifs.html#lookupname) BIF:

```styl
fnord = "I am fnord."
var = "fnord"

body
  content: lookup(var)
```
