### ISSUE TITLE
j-center

### ISSUE THREAD

**Issue by johnhult** [stylus/stylus#1904]
Using text-align center automatically changes text align to 'j-center' which is an invalid property name.

**Comment by covall** [comment]
I stil heve this issue. Is this resolved?

**Comment by Panya** [comment]
I guess, it's not a Stylus issue. Probably @johnhult has a transparent mixin defined somewhere in his codebase that produces this behavior. Try to find `text-align()` mixin in your codebase.

**Comment by Panya** [comment]
@covall probably related to https://github.com/mojotech/jeet/issues/416 (try to update Jeet).

**Comment by covall** [comment]
Tahnks. I was using Meteor package with older code.

**Comment by ingridoberbuchler** [comment]
How can I fix this issue? I have still same problem.

**Comment by Panya** [comment]
It's a Jeet issue, try to update Jeet version.

**Comment by ingridoberbuchler** [comment]
I have latest version.

**Comment by zif002** [comment]
I try to update Jeet version. But  I have problem j-center

**Comment by zif002** [comment]
/bower_components/jeet/stylus/jeet/_aliases.styl
center = j-center
rename center j_center = j-center
but  in styl files use j_center(max_width = 1410px, pad = 0)

**Comment by rsukochev-ideas** [comment]
confirm, problem in jeet
it added j- for ```center``` and ```column``` (flex-direction)

**Comment by Leolik** [comment]
confirm, problem in jeet
it added j- for ```center``` and ```column``` (flex-direction)

**Comment by alex-shamshurin** [comment]
How to solve this?
