### ISSUE TITLE
Access Arbitraty Result Data

### ISSUE THREAD

**Issue by arb** [stylus/stylus#1905]
I am using [sprite.styl](https://github.com/tommy351/sprite.styl) for Sprite Sheet generation. I can see [here](https://github.com/tommy351/sprite.styl/blob/master/lib/sprite.js#L116-L124) that the mixin returns some JS objects that have a bunch of different properties on them. I've loaded the debugger and examined the results before they are sent back to the calling stylus file and confirmed all kinds of data on the resulting object.

How can I access this JS object in a style sheet? I've tried several different combinations of `hash` `json` `keys` and everything else in between. I need those values to dynamically generate some class names. This problem isn't really specific to that module, it's a general question about how to use mixins that return data.

**Comment by Panya** [comment]
To use some JS object in a Stylus file you need to coerce it to Stylus [object node](https://github.com/stylus/stylus/blob/master/lib/nodes/object.js). For example:
```js
stylus.define('some-mixin', function() {
  return stylus.utils.coerceObject({
    foo: 'bar'
  }, true);
});
```

Or you can create and then return real Stylus object node:
```js
var nodes = stylus.nodes;

stylus.define('some-mixin', function() {
  var obj = new nodes.Object();
  obj.set('foo', new nodes.String('bar'));
  return obj;
});
```

The plugin, that you mentioned uses a custom node `SpriteMap` (defined in https://github.com/tommy351/sprite.styl/blob/master/lib/nodes/sprite-map.js) and this node doesn't have a representation in Stylus, so you can't access its data from a Stylus file.

**Comment by arb** [comment]
`SpriteMap` inherits from the Stylus Node though so shouldn't it have a Stylus representation? Also what could be changed so that it did have a representation in Stylus? There really isn't any documentation about that kind of thing that I've seen.

**Comment by Panya** [comment]
> SpriteMap inherits from the Stylus Node though so shouldn't it have a Stylus representation?

Yep, but its constructor doesn't call `Node`'s constructor and this node doesn't have any visitor methods ([here](https://github.com/stylus/stylus/blob/master/lib/visitor/evaluator.js) and [here](https://github.com/stylus/stylus/blob/master/lib/visitor/compiler.js)).

> Also what could be changed so that it did have a representation in Stylus?

You need to change code of the `SpriteMap` node to return `stylus.nodes.Object` with needed properties.
