### ISSUE TITLE
Maths inside functions

### ISSUE THREAD

**Issue by sevenupcan** [stylus/stylus#1908]
I'm creating a transparent mixin which accepts fractions, however the fraction doesn't look like it's passed through the mixin correctly.

I have the following:

```stylus
span()
    width: 100% * arguments
```

Called like so:

```stylus
.test {
    span: 1/2;
}
```

What should be the expected behaviour? I would expect the 1/2 to be evaluated to 0.5 but that's not what happens, it appears to passed through as some sort of string but when you check what type of node it is, it says it's a unit.

The only way I can think to get around this problem is to pass it through as a string, and try to parse the string. Does anyone have any other suggestions?

**Comment by Panya** [comment]
Well, the `1/2` is literally three arguments now (`1`, `/`, and `2`). To make it a fraction `1/2` (0.5) you should wrap it into brackets (see http://learnboost.github.io/stylus/docs/operators.html#multiplicative---).

```styl
span()
    width: 100% * arguments

.test {
    span: (1/2);
}
```

Or you can just do the math in the mixin:
```styl
span()
    width: (100% * arguments[0] / arguments[2])

.test {
    span: 1/2;
}
```

**Comment by sevenupcan** [comment]
Ah I see, great. Thank you :)
