### ISSUE TITLE
[Feature Request] Change variables within @media queries, reflect changes accross variable uses.

### ISSUE THREAD

**Issue by mrapogee** [stylus/stylus#1910]
If I set a variable, set a attribute to a variable then change the variable within a `@media` query, this isn't reflected in CSS. It would be incredibly convenient if I could do this:
```
foo = bar

h1
  attr: foo

@media screen and (min-width: 500px)
  foo = bar2
```
 
And then have this in CSS:
```
h1{
  attr: bar
}

@media screen and (min-width: 500px){
  h1{
    attr: bar2
  }
}
```

I know I can use smFoo and mdFoo, but I don't see the advantage in having those globally declared. I must admit I'm not familiar with the Stylus source so I don't know how hard this would be to implement or if I'm missing the boat entirely.

What you all think?

**Comment by Panya** [comment]
Why it should reflect any code that placed above the variable declaration? It seems really weird and will be unexpected behavior to many users (I'd say to almost all). Mixins were made exactly for this task.

**Comment by mrapogee** [comment]
Excuse my inexperience, but could you explain how mixens accomplish this?

**Comment by Panya** [comment]
Simple example:
```styl
mixin(foo)
  attr: foo

h1
  mixin(bar)

  @media screen and (min-width: 500px)
      mixin(bar2)
```

**Comment by mrapogee** [comment]
I suppose this works, but it isn't as convenient. I guess I'm of it too much as a pass by ref programming language. Just out of curiosity, is it also a horrible idea to introduce pass by ref for values like pass by ref for objects in JS? I'm just curious. This would also accomplish my goal, though it is rather large feature and probably would take some reworking. You could use some symbol prefixed before a variable to denote that it is pass by ref.

**Comment by Panya** [comment]
> I suppose this works, but it isn't as convenient. I guess I'm of it too much as a pass by ref programming language. 

It's just don't completely clear to me, why if we're overriding some variable (btw Stylus has block scoping and the `foo` inside `@media` is a different variable) we should copy all the code that uses this variable inside the `@media` block and change the value?

> is it also a horrible idea to introduce pass by ref for values like pass by ref for objects in JS? I'm just curious. This would also accomplish my goal, though it is rather large feature and probably would take some reworking. You could use some symbol prefixed before a variable to denote that it is pass by ref.

Well, then we should rewrite all scoping system. But again, I don't understand why it should somehow reflect code that uses that variable before?

**Comment by mrapogee** [comment]
Like the following JS:
```
prop = { val: 100 };
object = { width: prop };
get(prop){
 return object[prop].val
}
get('width') // is 100
if (window.width < 100){
  prop.val = 50 // get('width') is 50
}
```
Because the property is an object, it is pass by ref. Whenever you change prop.val, this is reflected in the object.width property. The equivalent stylus could be:

```
*prop = 100
@media (max-width: 100px)
   *prop = 50

object
   width: *prop
```

It would need to add  `object { width: *prop }` inside the `@media` because, since Stylus isn't run at run time, there's no way of knowing that *prop changed unless you added it. You wouldn't need to rewrite the entire scoping system, just watch for all vars prefixed with * and whenever that is changed inside a @media, repeat the rules that used it. This would just be for conditional rules like @media. 

In my styl files, I always have a vars.styl that contains variables that I use throughout the project. Right now, If I'd like something different for smaller screens, I need to use smThis and mdThat then use them inside my @media queries. If I could just change a single var inside the @media queries, it would make that a lot cleaner and easier to make a variable responsive.

Maybe I'm an unusual case, if you don't see anyone using this pattern then it is not worth it to implement this. It really make sense for my work.

**Comment by Panya** [comment]
>  You wouldn't need to rewrite the entire scoping system, just watch for all vars prefixed with * and whenever that is changed inside a @media, repeat the rules that used it. This would just be for conditional rules like @media.

I understand how pass by reference works :) Your case (with copying styles to `@media` etc). is just implicit and bad practice (overusing global variables instead of mixins).

**Comment by mrapogee** [comment]
Just so I can write better stylus, could you give me an example of how overusing global variables is bad practice? I know I'm being dogged, but I'd rather annoy you for a moment so I can write better stylus in the future.

**Comment by Panya** [comment]
This is bad practice in any programming language not only in Stylus. Just [google it](https://www.google.ru/?#newwindow=1&q=global+variables+bad).

**Comment by mrapogee** [comment]
I understand that globals are problematic in most programming languages, I'm not an idiot . What I don't understand is how this applies to Stylus. Are you saying that the bootstrap is using a bad approach because it uses vars? Your styles is small enough that this simply doesn't apply. Being able to change tons of values from one location is the point of having a preprocessor. And, you can override mixins just as easily.
