### ISSUE TITLE
Issue with transitions

### ISSUE THREAD

**Issue by maartendraijer** [stylus/stylus#1911]
Not sure if I'm submitting this issue to the right repository, but I'm having an issue with `transition all .3s` being compiled to `_transition: all 3s;`. I'm using Gulp to compile stylus to css. This is my gulp task:

```js
gulp.task('stylus', function() {
    return gulp.src(config.destPath + 'css/app.styl')
        .pipe(plumber({
            errorHandler: onError
        }))
        .pipe(stylus({
            use: [jeet()]
        }))
        .pipe(gulp.dest(config.destPath + 'css/'))
        .pipe(reload({ stream: true }));
});
```

Anyone else experiencing the same problem or knowing how to fix?

**Comment by Panya** [comment]
Well, I can't reproduce this. Probably, you have a [transparent mixin](http://learnboost.github.io/stylus/#how-about-transparent-mixins) defined somewhere in your code.
