### ISSUE TITLE
Cannot extend placeholder selector within media query followed by a ID selector starting with certain characters 

### ISSUE THREAD

**Issue by donut** [stylus/stylus#1912]
That title is the best I could do.

Here's code that reproduces the problem:

```stylus
@media only screen and (min-width 60em)
  $troopa
  #a article
  .test
    padding-bottom 67px

.blurg
  @extends $troopa
```

The following code will produce the error message 'Failed to @extend "$troopa"'.

This only happens when `$troopa` is within a media query, is followed by a selector starting with an ID whose first character is a, b, c, d, e, or f and then followed by any other selector and the first two selectors don't end with commas. To verify, just copy the above code, test it and then change `#a` to `#g` and it will work.

`Stylus 0.51.1`

**Comment by Panya** [comment]
Thanks for the report. I've fixed this bug in the `dev` branch. The fix will be in the next release.
