### ISSUE TITLE
Can't escape "\" in strings

### ISSUE THREAD

**Issue by dapetcu21** [stylus/stylus#1913]
This makes it impossible for me to write absolute windows paths:
```
@import "c:\nothing\of\the\kind\works"
@import "c:\\this\\does\\not\\work\\as\\well"
```
It interprets `\n` as a newline and `\\` as two backslashes

My current workaround is
```
@import "c:\" + "this\" + "works"
```

Probably related to #1522

**Comment by Panya** [comment]
Duplicate of #1522
