### ISSUE TITLE
Expose the Javascript API to node land?

### ISSUE THREAD

**Issue by DelvarWorld** [stylus/stylus#1916]
We are using stylus for some of our style sheets and experimenting with [react-styles](https://github.com/js-next/react-style) to make inline styles. It would be helpful if we could use stylus commands like lighten, darken, etc, to massage our javascript variables.

The API is sort of there, but it's not straightforward to access

    var stylus = require('stylus');
    var adjust = require('stylus/lib/functions').adjust
    var hsla = new stylus.nodes.HSLA('red') // this is wrong

The disconnect appears to be that converting of colors to stylus color objects happens in the lexer in a non-portable way https://github.com/stylus/stylus/blob/c2d07a0f117de6144105de8599f620c34713d251/lib/lexer.js#L865 where the operations happen on the state values of the lexer.

Would it be within the scope / desires of this project to expose the same API that you can use with style sheets (like `lighten(red, 10%)`) to javascript?

**Comment by Panya** [comment]
Basically, all algorithms behind the colors functions widely described and implemented in different places (e.g. https://github.com/harthur/color). So, you can just use one of this libraries (or copy-paste some custom functions from `lib/functions/index.js` if implementation is different). I'm not sure that we should expose them.
