### ISSUE TITLE
nested import where the imported file extends a placeholder selector

### ISSUE THREAD

**Issue by neonstalwart** [stylus/stylus#1918]
is there a way to have a nested import find the placeholder selector?

https://gist.github.com/neonstalwart/0730009f37fa58fd59c4

abc.styl
```styl
.abc {
	@import "button.styl";
}

// Failed to @extend "$button"
```

button.styl
```styl
button(bgColor, color) {
	@extends $button;

	background-color: bgColor;
	color: color;

	&:hover {
		background-color: lighten(bgColor, 90%);
		color: bgColor;
	}
}

$button {
	border: 1px solid transparent;
	border-radius: 3px;
	cursor: pointer;
	display: inline-block;
	font-size: 0.8125rem;
	font-weight: 700;
	line-height: 2;
	margin: 0 2px;
}

.button {
	button($blue, #fff);
}

.action {
	button($green, #fff);
}
```

**Comment by Panya** [comment]
Stylus currently can extend exact selectors only. In your case it will be `.abc $button` (because of the nested import inside `.abc`). A working example:
```stylus
button(bgColor, color) {
    @extends .abc $button;

    background-color: bgColor;
    color: color;

    &:hover {
        background-color: lighten(bgColor, 90%);
        color: bgColor;
    }
}
```
However we have an issue for `@extend-all` semantic (see #1238).

**Comment by neonstalwart** [comment]
is there a way to get the parent selector of `$button` since i have an app and a widget and for the app i import buttons.styl into the root context but in the widget i want to use a nested selector to scope it for when someone uses this widget on their own page?

something like:

```styl
scope = selector('&')

button() {
  @extends scope $button
}

$button {

}
```

**Comment by Panya** [comment]
@neonstalwart yep, you can write something like this (hacky way):
```stylus
button(bgColor, color) {
	@extends {split(' ', selector())[0]} $button // split(...)[0] => '.abc'

	background-color: bgColor;
	color: color;

	&:hover {
		background-color: lighten(bgColor, 90%);
		color: bgColor;
	}
}
```

**Comment by neonstalwart** [comment]
> @extends {split(' ', selector())[0]} $button // split(...)[0] => '.abc

i think that will fail when in the root context since the first selector will be `.button` or `.action` when it's not nested.  i think what i asked for will actually work but for some reason i thought i had tried it and failed.

thanks.

**Comment by Panya** [comment]
Actually, you can also use [root reference](http://learnboost.github.io/stylus/docs/selectors.html#root-reference) for the placeholder selector here:
```stylus
button(bgColor, color) {
	@extends $button;

	background-color: bgColor;
	color: color;

	&:hover {
		background-color: lighten(bgColor, 90%);
		color: bgColor;
	}
}

/$button {
	border: 1px solid transparent;
	border-radius: 3px;
	cursor: pointer;
	display: inline-block;
	font-size: 0.8125rem;
	font-weight: 700;
	line-height: 2;
	margin: 0 2px;
}
```

**Comment by neonstalwart** [comment]
ah thanks... i had tried a variation of that which didn't work

```styl
button() {
  @extends /$button;
}

/$button {

}
```

i like this better than the `scope` idea.

**Comment by neonstalwart** [comment]
although the `scope` idea is good if you are extending another selector rather than a placeholder selector.
