### ISSUE TITLE
Import resolution order causes unexpected problems

### ISSUE THREAD

**Issue by kostko** [stylus/stylus#1919]
It seems that files in the local directory can override imports from within plugins like `nib` which may cause unexpected import loops.

To reproduce, create a directory and install `stylus` and `nib`:
```
$ npm install stylus nib
```

In the same directory, create a file called `text.styl` with the following contents:
```stylus
@import 'nib'
```

Then execute the following code via nodejs:
```javascript
var stylus = require('stylus');
var nib = require('nib');

stylus("@import 'text'").use(nib()).render();
```

The process will hang and start consuming CPU. It will only terminate after it runs out of stack space. There are two problems with the import process:
* Files from the local directory can take precedence in imports within plugins. This means that local files can unexpectedly override things in the plugin just by having the same name as some styl file somewhere inside the plugin directory structure. When in the above example, the `nib` plugin does `@import 'text'`, the stylus compiler will import the local `text.styl` instead of having the one in the plugin take precedence.
* Import loops are not detected and needlessly consume CPU.

**Comment by Panya** [comment]
Well, there is obviously a little problem with nib's `@import 'text'`. Stylus currently trying to import `text.styl` if `.styl` is not present in the import path. And if it fails, Stylus trying to import `index.styl` file inside a directory `text`. In our case there isn't `text.styl` inside `nib` dir (but there is `text` dir with `index.styl`). And because of that Stylus imports `text.styl` from the local directory first.

**Comment by Panya** [comment]
I've added a proper check for import loops in the `dev` branch. Thanks for the report.

**Comment by kostko** [comment]
Thanks for adding the import loop check.

> And if it fails, Stylus trying to import index.styl file inside text directory. In our case there isn't text.styl inside nib dir (but there is text dir with index.styl). And because of that Stylus imports text.styl from the local directory first.

Ok, so this then only affects directory-based imports. But shouldn't the resolution order still check the directory where the source file is placed first? Otherwise, it seems like all imports are handled as a flat structure without any regard for where the currently parsed file is. This is especially problematic when you are importing plugins, which may have some unknown folder structure and can unexpectedly conflict with your local style files.

Are there plans to fix the resolution order? As the current import behavior seems really unexpected to me.

**Comment by Panya** [comment]
> Are there plans to fix the resolution order? 

Yep, we'll rewrite importing system in 1.0.
