### ISSUE TITLE
Pass strict mode

### ISSUE THREAD

**Issue by blitzprog** [stylus/stylus#1922]
Stylus should not fail to compile in strict mode (--use_strict).
This requires removing the octal values in the code and changing the variable name "package" to something else, e.g. "pkg".

**Comment by blitzprog** [comment]
Note that mkdirp causes the last remaining error but they already fixed it in their github repo:
https://github.com/substack/node-mkdirp/commit/48e67fce39f1a5f2aba6196301b7be6d4545d6cf

With these changes and the updated mkdir it's possible to compile in strict mode.

**Comment by Panya** [comment]
Thanks. This fix will be in the next release.
