### ISSUE TITLE
Sublime Stylus Autocomplete

### ISSUE THREAD

**Issue by Orbyt** [stylus/stylus#1925]
Are there any plugins for Stylus autocomplete? I love using Stylus but the lack of autocomplete for properties sucks.

**Comment by Panya** [comment]
I think SO or official [sublime-stylus](https://github.com/billymoon/Stylus) project is better place for this question.

**Comment by Orbyt** [comment]
@Panya Ok, now do you know of any? http://stackoverflow.com/questions/30421218/sublime-text-stylus-autocompletion?noredirect=1#comment48928344_30421218
