### ISSUE TITLE
Feature Request: stylus/register

### ISSUE THREAD

**Issue by DylanPiercey** [stylus/stylus#1927]
It would be nice to have the ability to require compiled stylus file's inline in node js similar to the javascript transpilers.

Babel uses:
```javascript
require("babel/register")
// Require es6/7 files.
```

Ideally I could also require stylus files in the same way by doing:
```javascript
require("stylus/register")
// Require in-lined stylus css.
```

What do you guys think?

**Comment by Panya** [comment]
I think this is out of Stylus's scope. Actually you already can require compiled stylus files with something like webpack (see [stylus-loader](https://github.com/shama/stylus-loader)).

**Comment by DylanPiercey** [comment]
I actually already use a browserify transform to make this work in the browser it would just be handy to be able to handle it similarly on the server side.

**Comment by DylanPiercey** [comment]
I think this should be reconsidered, It's very simple to implement.

```javascript
var fs         = require('fs'),
	stylus     = require('stylus'),
	options    = {},
	registered = false;

if (require.extensions) {
	require.extensions['.styl'] = function compileTemplate (module, filename) {
		options.filename = filename;
		stylus.render(fs.readFileSync(filename, 'utf8'), options, function (err, css) {
			if (err) throw err;
			body = 'module.exports = ' + JSON.stringify(css) + ';';
			console.log(body)
			module._compile(body, filename);
		});
	}
}

module.exports = function (customOptions) {
	if (registered) throw new Error('Stylus can only be configured once.');
	for (key in customOptions) options[key] = customOptions[key];
	registered = true;
};
```

**Comment by Panya** [comment]
Well, if we can do something it doesn't mean that we should do it. I still think that this feature has very rare use cases and not so useful (compared to the similar feature of `babel` where it is a must).

**Comment by DylanPiercey** [comment]
Well, if it means anything, my particular use-case is to use scoped styles with react. It works very well in this case.

This also makes isomorphic styling a little bit easier. I'll admit it's not as useful as `babel or coffeescript` but it's a nice convenience to have. `Jade` also supports a way to register within node and in the same way it's easier to write isomorphic code.

I am fine with handling this myself since it's such little code but I can't help but feel that it would be useful to others.
