### ISSUE TITLE
Files used in render.

### ISSUE THREAD

**Issue by trenskow** [stylus/stylus#1928]
Feature request:

It would be great if stulys could do something like this:

    stylus.render(source, { filename: file }, function(err, css, files) {
        // files is an array of all files used to render (mixing, etc.).
    });

**Comment by Panya** [comment]
You can use `stylus.deps` method (not yet documented) to get the dependencies (used imports):
```js
var deps = stylus(fs.readFileSync(file, 'utf-8')).deps(file);
```

**Comment by trenskow** [comment]
Thanks!
