### ISSUE TITLE
How to prepend a class to a selector

### ISSUE THREAD

**Issue by yushengh** [stylus/stylus#1929]
I want to prepend a classname before a selector (there is no space between the classes). I tried the -prefix-classes built-in function, the one below is the result which I want.
![0608132400](https://cloud.githubusercontent.com/assets/12801355/8040834/a8c0a476-0de1-11e5-80cb-f79fcdaecc05.png)

But the function will add a prefix to all the classes, if it has more then one classes, it would become tge one as the image below (.Toolstrip.PushButton.Toolstrip.Disabled), which can't fulfill my demands.
![image](https://cloud.githubusercontent.com/assets/12801355/8040881/05436706-0de2-11e5-8cd0-e610311001bc.png)

I would like to know is there any function or approach that can resolve my requirement?

**Comment by Panya** [comment]
You can write something like this:
```stylus
selectors()
  &.Button
    color: red

  &.ToggleButton, &.PushButton
    color: blue

.Toolstrip
  selectors()
```

It won't change the selectors if the mixin is called on the root level because `&` will be evaluated to an empty string.

**Comment by yushengh** [comment]
Yes. I know this way can work. But our goal is want the author who writes the normal buttons as easy as possible, They probably don't want write a & before each selectors, they don't need to care about what button looks like in Toolstrip, they just need to write a .button. Is there a convenient way that can prepend & to each classes?

**Comment by yushengh** [comment]
I mean is there some way similar like this?

selectors() {
  & {
    .Button
      color: red
  
     ToggleButton, .PushButton
       color: blue
  }
}
.Toolstrip
  selectors()

**Comment by Panya** [comment]
> I mean is there some way similar like this?

Without changing the source code — no. `prefix-classes` is the best solution in this case. Probably you can also use a postprocessor (like PostCSS) for this task.

**Comment by yushengh** [comment]
Thanks, I will take a look.
