### ISSUE TITLE
Web-site style scares me to use the (CSS!) framework

### ISSUE THREAD

**Issue by TWiStErRob** [stylus/stylus#1932]
I'm used to having 50% of my screen filled with background color because of the screen resolution I have, but 85% warrants a bug report here.

The column width on the main page there makes sense (wanted to emphasize simplicity), though still extremely weird. I pulled the window onto my regular-sized (1280x960) laptop and it was still strange. Here's my main screen:
![image](https://cloud.githubusercontent.com/assets/2906988/8097627/0b48c47a-0fe5-11e5-9067-b5a904b4061f.png)

 The same width doesn't make any sense on http://learnboost.github.io/stylus/docs/executable.html for example:
![image](https://cloud.githubusercontent.com/assets/2906988/8097610/b66e5078-0fe4-11e5-8fc8-b2179c667e35.png)

Also even though the column is skinny, it doesn't work on slim screens:
![image](https://cloud.githubusercontent.com/assets/2906988/8097672/a6ef0be6-0fe5-11e5-8672-d1f223206696.png)

Was this page designed on 1024x768 and never tested on any other resolution?

**Comment by Panya** [comment]
Hi, we have a newer version of the site http://stylus-lang.com (in development).

**Comment by Panya** [comment]
P.S. Stylus is not a CSS framework :D

**Comment by TWiStErRob** [comment]
Sorry, didn't mean to degrade your language compiler. I think you got the point because you're already making a new one :) I suggest to get ideas from angular, lodash, underscore, jekyll, and your competitor's docs.
