### ISSUE TITLE
Resolve url relatively to css path

### ISSUE THREAD

**Issue by cakeinpanic** [stylus/stylus#1933]
Now urls are resolved relatively to .styl file.
It works ok when path resulting .css is similar to path to .styl
But as soon as .css is generated one folder deeper(or one folder up), all resolving doesn't make sense
Is there any way to handle this problem?

**Comment by Panya** [comment]
It should work if you're passing `--out` flag (or `dest` option) with path to the CSS and using Stylus >= 0.51.0

**Comment by cakeinpanic** [comment]
What should i pass to `dest` if src looks like `src/component/*/*.styl` and i want to generate each .css at `src/component/*/css/out.css`?

**Comment by Panya** [comment]
I think it should be fixed in the grunt/gulp plugin. For each dest file in this glob pattern it should set `dest` option of Stylus to `dirname(destFile)`.
