### ISSUE TITLE
Inline sourcemaps should specify charset in data URI

### ISSUE THREAD

**Issue by cspotcode** [stylus/stylus#1935]
https://github.com/stylus/stylus/blob/48569e1427696447c7d7aba78f87c5ece1ddec49/lib/visitor/sourcemapper.js#L78

When generating an inline sourcemap, the base64 string is generated from a UTF-8 encoded buffer.  However, the data uri does not specify its charset.  According to the data URI spec, data URIs default to US-ASCII encoding if charset is not specified.
https://developer.mozilla.org/en-US/docs/Web/HTTP/data_URIs
http://tools.ietf.org/html/rfc2397

I believe this means that a proper data URI parser will decode the base64 and interpret the resulting octet stream with US-ASCII encoding instead of UTF-8.

Therefore, I'm pretty sure the data URIs generated by stylus should specify their utf-8 charset.

```
url = 'data:application/json;charset=utf-8;base64,' + new Buffer(map).toString('base64');
```

**Comment by cspotcode** [comment]
I've created a Gist that reproduces the issue:
https://gist.github.com/cspotcode/f95bf540472c7e774e5a

I wrote some Stylus that has:
```
content: "💩" // unicode pile of poo character
```

I compile this Stylus into .css with an inline sourcemap.  The css file is correct, the css rules work correctly, *but* viewing the original .styl file via sourcemap in Chrome's dev tools does not render correctly because Chrome is not interpreting the data URI as UTF-8.

**Comment by Panya** [comment]
Yep, thanks for the report. I've fixed this in the `dev` branch. The fix will be in the next release.
