### ISSUE TITLE
Error converting Stylus into CSS

### ISSUE THREAD

**Issue by Galaxy42** [stylus/stylus#1939]
I have a problem with Stylus, I've never experiented this.
This is my stylus file:

> @import "./nav/styles.styl"

And the styles.styl that mentions there contains these:

https://gist.github.com/adbbd11d7b016117be86.git

And this compile into this:

> nav {
  height: 19px;
}
.login,
background #A30006,
border-radius 5px,
height 30px,
margin-left 32.5em {
  position: absolute;
}
top 1.2em,
right 4.5em,
width 85px,
.login_btn,
color white,
font-size 1em,
font-weight normal,
margin-left .8em,
margin-top .2em,
padding 0,
position absolute,
text-align center,
text-decoration none,
.logo:first-child,
border-right 5px solid white,
content "",
.logo,
margin .5em {
  margin-bottom: 0;
}

How can I solve it?

**Comment by Panya** [comment]
You have bad indentation (messing tabs and spaces). Replace tab with two spaces on `position absolute` (line 9) and remove tab at line 28.
