### ISSUE TITLE
`json` and `convert` can't parse lists

### ISSUE THREAD

**Issue by kizu** [stylus/stylus#1940]
When you have something like `10px 20px` in either json or a string that you're using in `convert`, you get only the first item of the list:

``` styl
.test
  test: convert('10 20')
```

renders as 

``` css
.test {
  test: 10;
}
```

etc.

**Comment by Panya** [comment]
How can we be sure that it is a list (not a string with spaces)?

**Comment by Panya** [comment]
Fixed in the `dev` branch. Thanks for the report.
