### ISSUE TITLE
Compatibility with Polymer 1.0's layout

### ISSUE THREAD

**Issue by curimit** [stylus/stylus#1943]
Sample code:

``` styl
:host
  @apply(--layout-vertical)
```

Which compiles to

``` css
@apply (--layout-vertical);
```

But actually what I want is

``` css
:host {
  @apply(--layout-vertical);
}
```

See more about `@apply` here: https://www.polymer-project.org/1.0/docs/migration.html#layout-attributes

Thanks.

**Comment by maksimkurb** [comment]
+1
This is very must-have fix in Stylus, if you want to use Polymer 1.0+

**Comment by Nonlimit** [comment]
+1

**Comment by mafiuss** [comment]
+1

**Comment by flexmotion** [comment]
+1

**Comment by groenroos** [comment]
The described behaviour no longer occurs in version `0.55.0`, and in any case it seems like Polymer itself has been discontinued.

Closing this issue as stale. Please file a new issue if you still encounter this or any other problems.
