### ISSUE TITLE
Reason for callback in stylus.render( (err, css) => {...} )

### ISSUE THREAD

**Issue by bucaran** [stylus/stylus#1947]
Why does stylus return the CSS through the callback in `stylus.render`? 

Is the `Stylus → CSS` transformation process async? Or is this function called immediately, kind of like the callback for `forEach`, `map`, etc.

**Comment by bucaran** [comment]
> Is the Stylus → CSS transformation process async?

I think this process is sync. I don't know the benefit of using a callback if the process is sync anyway or am I missing something?

**Comment by Panya** [comment]
Yep, this process is sync. And you can use synchronous version of `render`:
```js
var css = stylus(...).render();
console.log(css);
```

**Comment by bucaran** [comment]
Thanks! :+1:

**Comment by pipegris** [comment]
If I use it this way (sync): 
```
var css = stylus(...).render();
console.log(css);
```

How can I know if an error occured?
Thanks
