### ISSUE TITLE
Is there a function in stylus checking if a @import file/directory exists?

### ISSUE THREAD

**Issue by yushengh** [stylus/stylus#1949]
Is there some functionality in stylus like this:
<pre>
file = "dir/stylus-file"
if file exists
    @import file
</pre>

Essentially, I want a @import function. Check if a file or directory exists or not first. If a file or directory exists, import it. If it is not, just continue it, instead of getting compiling error.

**Comment by Panya** [comment]
Currently there's no such built-in function, but you can write a plugin. See solution that I described in #1872.
