### ISSUE TITLE
multi-line property declaration

### ISSUE THREAD

**Issue by zanona** [stylus/stylus#195]
At the moment the following declaration returns an error I think :)

```
-webkit-box-shadow: 1px 0 0 rgba(  0,  0,  0,.2),
                    2px 0 0 rgba(255,255,255, 4);
```

this is nice because it makes easier to visualize your document, not primordial but it does help a bit on the visualization :)

**Comment by ibmua** [comment]
I'm trying to use 

```
	transition			background	0.2s	ease-in-out
					,	opacity		0.4s	ease-in-out
```

And this works fine in one of two stylus files I have.
In the file where it doesn't work 

```
	transition			background	0.2s	ease-in-out	,
						opacity		0.4s	ease-in-out

```
works, but

```
	transition			background	0.2s	ease-in-out	,
						opacity		0.4s	ease-in-out	,
						color		0.4s	ease-in-out

```

and 

```
	transition			background	0.2s	ease-in-out
					,	opacity		0.4s	ease-in-out	

```

doesn't. Somebody's made a bug somewhere.
