### ISSUE TITLE
Caching by contents outputs incorrect sources values for sourcemaps

### ISSUE THREAD

**Issue by Slava** [stylus/stylus#1953]
Hi, I spotted a bug that was causing me problems.

If you render two files, with different values of `'filename'` property, but with the same contents, the output sourcemaps would have identical values in `'sources'` property, which is incorrect, since the filenames are different.

Here is a reproduction:

```javascript
stylus = require('stylus')
stylusString = '.selector { color: red }'
styleA = stylus(stylusString).set('filename', 'a.styl').set('sourcemap', {inline: false, comment: false})
styleA.render(function () { console.log('A:', styleA.sourcemap.sources[0]) })
styleB = stylus(stylusString).set('filename', 'b.styl').set('sourcemap', {inline: false, comment: false})
styleB.render(function () { console.log('B:', styleB.sourcemap.sources[0]) })
```

This prints:

```
A: a.styl
B: a.styl
```

Expected:

```
A: a.styl
B: b.styl
```

**Comment by Panya** [comment]
This is not a bug. It's caching mechanism. You can disable it with `cache: false` option (or `--disable-cache` CLI flag).

**Comment by Slava** [comment]
@Panya I think it is a bug as the correct behavior is different from observed. The resulted sourcemap points to a different source file. It is incorrect, I consider it to be a bug.

I understand that caching is a feature that is optional.

**Comment by Slava** [comment]
@Panya do you plan to response to this? I legitimate think it is a bug that causes a confusing behavior.
