### ISSUE TITLE
Url resolving in imported css via JS API

### ISSUE THREAD

**Issue by cakeinpanic** [stylus/stylus#1957]
This code doesn't resolve urls from imported `.css` files
```js
stylus(str)
	.define('url', stylus.resolver())
	.set('include css', true)
	.render(function(err, css) {
	     console.log(css);
});
```
Otherwise the same process ran from console works properly 
`stylus src.styl --include-css --resolve-url`

**Comment by Panya** [comment]
Yep, prior version `0.52.0` you need to set `resolve url` additionally:
```js
stylus(str)
    .set('resolve url', true)
    .define('url', stylus.resolver())
    ...
```
But in 0.52+ all should work as expected.
