### ISSUE TITLE
Cannot use mixin arguments as hash element id

### ISSUE THREAD

**Issue by seleckis** [stylus/stylus#1958]
Maybe I'm doing something wrong, I don't know, but…
```stylus
$screen = {
	t2: {
		bp: 900px
	}
}
sideblock(scr)
	@media(min-width: $screen[scr].bp)
		position absolute auto auto auto 0
		width: 242px
```
```stylus
.b-filter
	sideblock(t2)
```
causes error `$screen [] ((t2)) has no property .bp`.

It seems I cannot use mixin argument as hash identifier. Any help?

**Comment by seleckis** [comment]
sorry, incorrect mixin calling. Had to use quotes:
```stylus
.b-filter
    sideblock("t2")
```

**Comment by Panya** [comment]
Actually, in the latest version your first example works too. Try to update Stylus.

**Comment by seleckis** [comment]
Ok, thank you
