### ISSUE TITLE
Can a stylus file know who imports it?

### ISSUE THREAD

**Issue by yushengh** [stylus/stylus#1959]
For instance:

There is a A.styl which @import B.styl

Can in B.styl there has a $file-imports-me variable get the filename of A.styl? ($file-imports-me = A)

**Comment by Panya** [comment]
Currently there is no such feature. Can you show a use case for this functionality?

**Comment by yushengh** [comment]
I am currently designing an architecture similar as semantic-UI using stylus.

In semantic-UI, each element like button.styl will define a variable $element  = 'button'; and @import '../../theme.config';

And in theme.config.styl, by knowing the $element is button, it could find the corresponding variables  or overrides file.
For example: @import "@{themesFolder}/@{theme}/@{type}s/@{element}.variables";

But the thing is the name of the file button.styl is button, it obviously same as the variable $element name. It's pretty redundant for user to define it again. 

If the theme.config.styl could know who imports it, we could just assign the filename to $element without defining it.

**Comment by vendethiel** [comment]
-1, seems too magical, too easy to be abused, for no significant benefit

**Comment by Panya** [comment]
Yep, it is a very specific case. I don't think that this feature will be useful, sorry.

**Comment by yushengh** [comment]
Yes, I think it is too specific case. But I am curious can stylus get the current filename?

**Comment by Panya** [comment]
You can write a simple plugin for this:
`get-filename.js`
```js
module.exports = function() {
    return function(style) {
        style.define('get-filename', function() {
            return this.currentBlock.filename;
        });
    };
};
```
And then use like this:
`test.styl`
```styl
use('get-filename.js')

body
  test: get-filename()
```
Compiles to:
```css
body {
  test: 'test.styl';
}
```

**Comment by yushengh** [comment]
Thanks so much！ That helps a lot.
