### ISSUE TITLE
Problem with wildcard requiring

### ISSUE THREAD

**Issue by cakeinpanic** [stylus/stylus#1961]
When you reqiure files like this
```css
@require "two/**"
@require "**/*.styl"
```
and use `--include` and `--resolve-url` options together, only folder `two` is required
Here is my test repo
https://github.com/cakeinpanic/stylus-test/tree/require-issue

**Comment by Panya** [comment]
You should use `--resolve-url-nocheck` in this case. Otherwise each import directory is added to lookup paths (to check that file in `url` exists) and after visiting `test/inner/two` `**/*.styl` in the second `@require` is matching to `test/inner/two/two.styl`.
