### ISSUE TITLE
Don't assume .styl if import contains "css"

### ISSUE THREAD

**Issue by CTimmerman** [stylus/stylus#1965]
I had to do @import "http://fonts.googleapis.com/css?family=Roboto:300,400,500,700&.css" to prevent Stylus trying "http://fonts.googleapis.com/css?family=Roboto:300,400,500,700.styl".

A folder or file named "css" should only contain CSS.

**Comment by Panya** [comment]
It's actually a bug. But you can write it with `url` as a temporary workaround:
```styl
 @import url("http://fonts.googleapis.com/css?family=Roboto:300,400,500,700")
```
I've fixed it in the `dev` branch. The fix will be in the next release. Thanks for the report.
