### ISSUE TITLE
Omit commas in argument list?

### ISSUE THREAD

**Issue by blynx** [stylus/stylus#1976]
What about leaving out the commas in argument-lists in mixins and functions?
I was just leaving them out intuitively because stylus is so ... "deco-less" but that didn't work out ...

```
function(a b c)
  do something with a b and c
```
```
.item
  function(a b c)
```

shouldn't that be possible?

**Comment by Panya** [comment]
This would be ambiguous when a mixin accepts a list as one of its arguments. For example:
```styl
mixin(list)
  body
    color: list[0]
    background: list[1]

mixin(#c00 #00c)
```

**Comment by blynx** [comment]
Uh, I see - haven't worked with lists, yet.
Thx.
