### ISSUE TITLE
Improve string concatenation detection

### ISSUE THREAD

**Issue by a-x-** [stylus/stylus#1977]
now i have to write like this:
```stylus
icon('' + side + '_' + color)
```
but i want go more straight way:
```stylus
icon(side + '_' + color)
```

**Comment by Panya** [comment]
This should work in the latest version of Stylus (0.52.0). You can try it online on http://learnboost.github.io/stylus/try.html.

**Comment by Panya** [comment]
Anyway the current behaviour is consistent with Sass and Less. If we change it, it will only be in 1.0.

**Comment by a-x-** [comment]
Thank you!
