### ISSUE TITLE
Access Stylus inner processes from the JS API

### ISSUE THREAD

**Issue by basharov** [stylus/stylus#1978]
I suppose Stylus parser converts incoming Stylus rules into its own objects before processing and converting to CSS or any other modifying procedures. 

So, I wonder, if it's possible to get into the inner process and get access to the structured data parsed from stylus stylesheet? I'd like to get into it, do something with the objects, then return access to the Stylus. 

Maybe it could be some kind of a middleware?

**Comment by Panya** [comment]
Yep, it's possible. While there is no simple (simple as middleware) way to do this, you still have access to almost all internal parts of Stylus and can monkeypatch or redefine them. See Stylus renderer pipeline [here](https://github.com/stylus/stylus/blob/master/lib/renderer.js#L80-L96) and exported constructors [here](https://github.com/stylus/stylus/blob/master/lib/stylus.js#L55-L59). For example we can redefine `Evaluator.prototype.visitProperty` to return `42` as the property value:
```js
var stylus = require('stylus')
  , Evaluator = stylus.Evaluator
  , nodes = stylus.nodes
  , visitProperty = Evaluator.prototype.visitProperty;

Evaluator.prototype.visitProperty = function(prop) {
  prop = visitProperty.call(this, prop);
  prop.expr = new nodes.Unit(42);
  return prop;
};

stylus('body { color: red }').render(function(err, css) {
  if (err) throw err;
  console.log(css); // => body { color: 42 }
});
```
Another example — viewing AST after parsing:
```js
var Parser = require('stylus').Parser;

console.log(JSON.stringify(new Parser('body { color: red }').parse(), null, 2));
```
