### ISSUE TITLE
Option to use configuration file

### ISSUE THREAD

**Issue by kwiniarski** [stylus/stylus#1979]
It would nice to have possibility to keep Stylus configuration in one file and load  it by passing additional parameter in CLI, ex. `stylus --config myConfig.json -o ./dest ./src`.

This would be handy when working with more complex configurations. For example [poststylus](https://github.com/seaneking/poststylus) with list of plugins where some of them takes additional options.

**Comment by Panya** [comment]
Duplicate of #296
