### ISSUE TITLE
Does Stylus have functionality to write source styl code to a file?

### ISSUE THREAD

**Issue by basharov** [stylus/stylus#1980]
I use `var Parser = require('stylus').Parser;` to parse an input file, then do some processing on it and want to write it back as Styl, not CSS. 
Is it possible?

**Comment by Panya** [comment]
There is no such functionality in the core (because we don't need one). But you can write your own stringifyer using `Visitor` (see [compiler](https://github.com/stylus/stylus/blob/master/lib/visitor/compiler.js) as example).
