### ISSUE TITLE
Nested color operations?

### ISSUE THREAD

**Issue by robmoggach** [stylus/stylus#1981]
This may not be supported...

Defining a new "red" (and others)

    red = spin( desaturate( darken( #f00, 25%), 70%), -5deg)

gives me this error:

    TypeError: expected rgba or hsla, but got call:darken(#f00, 25%)

**Comment by robmoggach** [comment]
Was able to get this working by creating a new function but wondering if there's a one line solution?

    lsh(color, l, s, h)
      lCol = adjust(color, 'lightness', l)
      sCol = adjust(lCol, 'saturation', s)
      hCol = sCol + unit(h, deg)
      return hCol

**Comment by Panya** [comment]
Cannot reproduce this in the latest version of Stylus (`0.52.0`). Which version are you using?
