### ISSUE TITLE
border-radius: inherited is not printed

### ISSUE THREAD

**Issue by Leonidaz** [stylus/stylus#1982]
border-radius: inherited;
is not printed in the css

e.g.

    .test
        border-radius: inherited

results in

    .test {
    }

**Comment by Panya** [comment]
I can't reproduce this with the latest version of Stylus (`0.52.0`). You can try your example online on http://learnboost.github.io/stylus/try.html to make sure that all works fine. I guess you have a transparent mixin named `border-radius` somewhere in your code base that causes this behavior.

**Comment by Panya** [comment]
Also, it's not related to the issue, but `inherited` is not valid CSS value. You mean `inherit`?

**Comment by Leonidaz** [comment]
looks like the issue is with "nib", i'll report it there.

yes, it's inherit, in the styl it was inherit, sorry.
