### ISSUE TITLE
Just some inline images (base 64)

### ISSUE THREAD

**Issue by manobi** [stylus/stylus#1984]
Is there a right way to inform Stylus compiler to convert background base 64 just some images?
I would like to inline some icons but reference external large images.
How can I inform Stylus what images to not convert when using:
```
stylus --inline --watch general.styl
```

**Comment by Panya** [comment]
Default limit is `30kb`, but you currently can't configure `url` function through CLI. You can write custom renderer using JS API and `url` function (see http://learnboost.github.io/stylus/docs/functions.url.html). For example:
```js
var fs = require('fs');
var stylus = require('stylus');

stylus(fs.readFileSync('test.styl', 'utf-8'))
  .set('filename', 'test.styl')
  .define('inline-url', stylus.url({ limit: 5120 })) // 5kb limit
  .render(function(err, css) {
    if (err) throw err;
    console.log(css);
  });
```

And use like this (`test.styl`):
```styl
body
  background: inline-url('bg.png')
```

But I'd recommend you to use a build system (like Gulp or Grunt) for this task.

**Comment by manobi** [comment]
It would be nice to be native in Stylus, but your suggestion might work for while.

Thanks @Panya.
