### ISSUE TITLE
Sourcemaps in Chrome workspace dev tools

### ISSUE THREAD

**Issue by manobi** [stylus/stylus#1985]
I am compiling my stylus file with:
```
stylus --sourcemap --watch general.styl
```
But I have also tried with:
```
stylus --sourcemap-inline --watch general.styl
```

In the last line of the css output I can see (as expected):
general.css
```css
/*# sourceMappingURL=css/general.css.map */
```

But when I map the general.css to a loaded css via [Chrome workspace](https://developer.chrome.com/devtools/docs/workspaces) the lines showed in inspected elements are the ones from .css not .styl.

I'm using stylus for more the 1 year now and it sucks because no one else seems to have the same problem.

What am I doing wrong?

PS: Yes, the sourcemap option is enabled.

**Comment by Panya** [comment]
Are you sure that the map file is loaded? (Do you see request to `general.css.map` in Network tab?). If no, are you sure that path to the map is correct? If no, CLI flags `--sourcemap-base` and `--sourcemap-root` may be useful. I've created a simple project with sourcemaps https://cloudup.com/cCV8-B-alcK (it works for me with Chrome 44).

**Comment by manobi** [comment]
With what params did you used in CLI to generate your css?

**Comment by Panya** [comment]
Just `stylus --sourcemap general.styl`

**Comment by manobi** [comment]
Given the following tree
```
|-- project
    |-- index.html
    |-- css
        |-- general.styl
```

The following command should work?
```
cd project
stylus --sourcemap --sourcemap-base css  --watch css/general.styl
```
I feel that I'm not understanding how --sourcemap-base and --sourcemap-root is works.

**Comment by Panya** [comment]
> The following command should work?

Yep. `--sourcemap-base` is just base directory from which sourcemap are relative. `--sourcemap-root` is value of `sourceRoot` property of the generated source map.

**Comment by Panya** [comment]
After running this command you should get `general.css.map` and `general.css` inside the `css` directory. And on the bottom of `general.css` you will see this comment:
```css
/*# sourceMappingURL=general.css.map */
```
Note that because of we specified correct relative directory with `--sourcemap-base` the path to the map is correct (file on the same level as `general.css`).

**Comment by manobi** [comment]
I have to always use ```--sourcemap-base``` and ```--sourcemap-root``` together ?
Because ```--sourcemap-base``` alone does not work. I will test using both.

**Comment by Panya** [comment]
You don't need to specify `--sourcemap-root` if you're running test server in the root dir (`project` in your case).

**Comment by Panya** [comment]
Read more about `sourceRoot` in [sourcemap v3 spec](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k)

**Comment by Panya** [comment]
Sorry, I can't reproduce your problem. I'm not sure that it's Stylus related. I guess it's somewhere between dev tools workspace and original files mapping. Can you try your project without workspace mapping?

**Comment by manobi** [comment]
I've found the problem. It happens because the map file exists local, but not in the place the page it's being loaded.

Thanks.
