### ISSUE TITLE
Responsive Stylus Site (making the site mobile friendly)

### ISSUE THREAD

**Issue by CKH4** [stylus/stylus#1987]
Basically the stylus site sucks to read on mobile, and while stylus-lang.com is an improvement its not actively updated or supported as the stylus homepage. This has been talked about (a lot) before but as far as I know the project got cancelled.

I've been working on a prototype that is similar to the stylus green color scheme, and fits mobile devices. I'm still working on the desktop version but I plan to keep it true to the current sites layout.

I'm not sure how I'll implement the try stylus online (if I ever will) because I don't really understand how it works. I also suggest that if you keep the try online option updated to switch to the ace editor as it is more mobile friendly (as far as I have tested) than codemirror.

If you would like to see the prototype in action see [here](http://codepen.io/CKH4/pen/xGoNdv?editors=110).

I would also like any feedback on the idea. Any information on if, or if not the creators like the idea of again trying to update the site would also be cool.

**Comment by Panya** [comment]
We have a new responsive site (still in development). See http://stylus-lang.com. It's opensource and you can contribute to https://github.com/stylus/stylus-lang.com

**Comment by CKH4** [comment]
Ah, I didn't know it was still being actively worked on. Thanks.
