### ISSUE TITLE
Throwing error() does not display error message.

### ISSUE THREAD

**Issue by JoshuaWise** [stylus/stylus#1991]
Given this file:
```stylus
func()
	if length(arguments) > 1
		error('foo bar')
	font-size arguments
h1
	position absolute
	func 5px 9px
```

The error is thrown, but the message "foo bar" is not displayed in the console.
The command I'm running to compile this file is `$ stylus < test.styl > test.css`

The console only displays:
```
/usr/local/lib/node_modules/stylus/bin/stylus:593
      if (err) throw err;
```

**Side note:**
When using `$ stylus --watch`, the error message **is** displayed.

**Comment by Panya** [comment]
I'm running your example with Node 0.10.40 and Stylus 0.52.0 (latest) and all works as expected. Which versions of Stylus/Node are you using?

**Comment by JoshuaWise** [comment]
I'm also running Stylus 0.52.0, but Node version 0.12.0.

I'm looking at the Stylus source, and I found 2 thing which might be the culprit.
in [bin/stylus at line 660](https://github.com/stylus/stylus/blob/master/bin/stylus#L660) you have this:
```javascript
 if (err) {
    if (watchers) {
        console.error(err.stack || err.message);
    } else {
        throw err;
    }
}
```

but where my error is being thrown ([line 593](https://github.com/stylus/stylus/blob/master/bin/stylus#L593)), the code only does this
```javascript
if (err) throw err;
```

This makes sense to me, since the error is displayed when using `--watch`, but not otherwise.

**Comment by Panya** [comment]
Well this code works with Node < 0.12, and it's logical (when we're watching some files we don't want to break the watching process by throwing an error). I'm not sure what is changed in Node 0.12+ but I have a workaround (`throw new Error(err)`)

**Comment by JoshuaWise** [comment]
I tried your workaround, and that does fix things. However, it displays quite a lot of useless information by creating a new Error, whose stack is also displayed.
This was able to get exactly the desired results:
```javascript
if (err) {
    console.error(err.stack || err.message);
    throw err;
}
```

Which displays:
```
stdin:3:18
   1| func()
   2| 	if length(arguments) > 1
   3| 		error('foo bar')
-----------------------^
   4| 	font-size arguments
   5| h1
   6| 	position absolute

foo bar
    at func() (stdin:2:6)
    at "h1" (stdin:5:21)

/usr/local/lib/node_modules/stylus/bin/stylus:595
        throw err;
              ^

```

**Comment by Panya** [comment]
Thanks for the PR, but it fixes only CLI error messages. I've added a more general fix for this bug in the `dev` branch. I don't know why old code is not working in Node 0.12+, but it's working now.

**Comment by JoshuaWise** [comment]
You're right, your fix is better. Thanks!

**Comment by iivmok** [comment]
I am using `stylus` from the dev branch. I get the same kind of `throw err;` message as before. Fixing line 661 from `throw err;` to `throw new Error(err)` per @Panya's suggestion makes stylus show proper errors. Are you guys sure this is fixed?

**Comment by ybordag** [comment]
Yea, I basically have the same problem as iivmok with line 661 and 592.

**Comment by cbaron** [comment]
This issue has been annoying me for weeks.  Until I found this page, I was considering removal of stylus from my stack.  Would you like for me to submit a PR ?
