### ISSUE TITLE
How to access functions defined in stylus, in a Node plugin?

### ISSUE THREAD

**Issue by JoshuaWise** [stylus/stylus#1993]
If my `test.styl` file looks like this:
```
special-func(a, b)
    return a + b

use('./plugin.js')
```

How can I access the `special-func` function from within `plugin.js`?

**Comment by Panya** [comment]
You cannot directly access user-defined Stylus functions inside the plugin. The only way to call it — create a `Call` node with name of the function and pass proper arguments (constructed via `Arguments` node).
