### ISSUE TITLE
Convert hex to RGB (unquoted)

### ISSUE THREAD

**Issue by manobi** [stylus/stylus#1994]
For a very specific use case I have to set color inside quotes, but even unquoting this I can't convert a hex color to rgb:
```
$color1_bg = '#080eff'
rgb(unquote($color1_bg))
```

```
error: TypeError: expected rgba or hsla, but got literal:#080eff
```

**Comment by Panya** [comment]
You can use [convert](http://learnboost.github.io/stylus/docs/bifs.html#convertstr) bif for this:
```styl
$color1_bg = '#080eff'
body
  color: rgb(convert($color1_bg))
```
