### ISSUE TITLE
End of line comments broken

### ISSUE THREAD

**Issue by drewloomer** [stylus/stylus#1996]
Commit [ca3de2f](https://github.com/stylus/stylus/commit/ca3de2f98fc61442d582be620a53598e98bcf17d) breaks comments at the end of a line. It's preventing nib from working as [referenced here](https://github.com/tj/nib/issues/315). I don't understand enough about what is happening in the code to know exactly why that happened.

**Comment by Panya** [comment]
Duplicate of #1995. We will release a new version later today.

**Comment by drewloomer** [comment]
Oops. Sorry for the dupe.
