### ISSUE TITLE
expression with variable, given via mixin failed

### ISSUE THREAD

**Issue by a-x-** [stylus/stylus#1999]
version: 0.52

code snippet:
```styl
$gallary__item_size_default = 80px
$root = '.gallery'
{$root}
    size($size)
        flex-basis: $size + 15px
        {$root}__selection
            margin-left: -($size + 10px) / 2 // <------------------ Error here

    size($gallery__item_size_default)
```

error:
```
   11|
   12|         {$root}__selection
   13|             margin-left: -($size + 10px) / 2
----------------------------------------------^
TypeError: expected "undefined" to be a unit, but got ident:$gallery__item_size_default10px
```

i tried also:
`(-($size + 10px) / 2)`
and a lot combinations of unit(...) and so on...

**Comment by Panya** [comment]
Well, this error means that you can use `-` unary operator only with units (yep, the "undefined" part is little confusing, I'll fix it). After concatenation you got `$gallery__item_size_default10px` because `$gallery__item_size_default` is undefined variable. If you change the variable name to `$gallary__item_size_default` (as declared above) all will be fine.

**Comment by a-x-** [comment]
Hi, @Panya 

typo `gallary` is only my this the gh-issue's issue :)

i updated code snippet above.

given:
* `defined-variable`
* `mixin(defined-variable)` call
* `mixin's-argument`
* expression in mixin body with `mixin's-argument` involve

result: `mixin's-argument` (based on `defined-variable`) parsing error in expression

**Comment by Panya** [comment]
Well, I don't see any error: http://codepen.io/anon/pen/XmpWGb

**Comment by a-x-** [comment]
Are you use stylus v0.52 like me?

**Comment by Panya** [comment]
You can try the same code at http://learnboost.github.io/stylus/try.html. I'm sure that this code works fine with 0.52.0.

**Comment by a-x-** [comment]
i'm not sure that stylus/try use 0.52.0
i open in source stylus.min.js and find mention 0.52.4 ...

**Comment by a-x-** [comment]
the confirmation bug in this vesrion will give me knowledge, what i must do next for fixind (try update stylus or something else)

**Comment by Panya** [comment]
OK, you can checkout `0.52.0` tag from the repo:
```
git clone https://github.com/stylus/stylus.git
cd stylus
git checkout 0.52.0
npm i
./bin/stylus <your file>.styl -p
```
But, again, I'm pretty sure that the code works the same way (I tested it with that version).
