### ISSUE TITLE
sudo: unable to execute /bin/stylus: Permission denied

### ISSUE THREAD

**Issue by StCremer** [stylus/stylus#2001]
After updating node I try to run stylus as before 
`sudo stylus -u autoprefixer-stylus -u csso-stylus -o /opt/lampp/htdocs/fish-nn.dev/sites/all/themes/Fish/css/  /home/St.Cremer/Сайты/Fishnn/styles2.styl`

but got for it
`sudo: unable to execute /bin/stylus: Permission denied`
Tryed to reinstall but got the same result

**Comment by Panya** [comment]
I guess you don't have permissions to run it as super user. Try to run `stylus` without sudo. Or try to reinstall it without `sudo`. Anyway, it's not a Stylus issue.

**Comment by alexeyten** [comment]
What `ls -l /bin/stylus` shows?

**Comment by StCremer** [comment]
[st.cremer@localhost ~]$ ls -l /bin/stylus
    lrwxrwxrwx. 1 root root 35 сен  8 01:29 /bin/stylus -> /lib/node_modules/stylus/bin/stylus
    [st.cremer@localhost ~]$ ls -l /lib/node_modules/stylus/bin/stylus
    -rwxr-xr-x. 1 nobody st.cremer 18437 июл 19 20:17 /lib/node_modules/stylus/bin/stylus
