### ISSUE TITLE
Strange and limiting behavior with hashes, when omitting colons.

### ISSUE THREAD

**Issue by JoshuaWise** [stylus/stylus#2005]
When omitting colons from a property declaration (`width 5px` instead of `width: 5px`), there are some strange behaviors that occur when the value of the property is a hash.

These examples use the following hash:
```
foo = {
  bar: {
    baz: 5px
  }
}
```

**You cannot use dot notation**
This works... `margin: foo.bar`
This throws an error... `margin foo.bar`

**You can only go one level deep using bracket notation**
This works... `margin: foo['bar']['baz']`
This works... `margin foo['bar']`
This throws an error... `margin foo['bar']['baz']`

Hashes are excellent for namespacing between modules, so it would be great if these issues could be solved. I'm currently in a situation where I could either
&nbsp;&nbsp;&nbsp;&nbsp;A) not use hashes for namespacing (ugly and dangerous)
&nbsp;&nbsp;&nbsp;&nbsp;B) convert all of my code to use colons everywhere (annoying and time-consuming)

I apologize, I do not know enough about language parsing to offer a pull request on this issue.

**Comment by Panya** [comment]
Unfortunately, colons is required in this case. See #1405.

**Comment by JoshuaWise** [comment]
I see, thanks.
