### ISSUE TITLE
Forward slash in JSON value throws error

### ISSUE THREAD

**Issue by ghinda** [stylus/stylus#2006]
Having a forward-slash value in a JSON file imported with the `json` function, and the `hash: true` option, will throw an error and cause stylus to fail.

Using this JSON file (`test.json`):

```
{"test": "test/test"}
```

and this stylus file (`test.styl`):

```
json('test.json', { hash: true });
```

then running Stylus with `stylus test.styl`, will return:

```
~/.nave/installed/default/lib/node_modules/stylus/bin/stylus:662
              throw err;
                    ^
Error: ~/.nave/installed/default/lib/node_modules/stylus/lib/functions/index.styl:1:6
   1| called-from = ()
-----------^
   2|
   3| vendors = moz webkit o ms official
   4|

cannot perform test / test
...
```

Importing the json with `hash: false`, or removing the slash from the value, fixes the issue.

I'm guessing it could have something to do with the `font-size/line-height` parsing when using forward-slash.

*Update:*
Using `leave-strings: true` also seems to fix it.

**Comment by Panya** [comment]
By default Stylus tries to convert string values of the JSON to Stylus expressions. To leave these values as strings you should pass `leave-strings: true`:
```styl
test = json('test.json', { hash: true, leave-strings: true })
typeof(test.test) // => 'string'
```

**Comment by ghinda** [comment]
Thanks for the details!
