### ISSUE TITLE
How to following error  "expected "indent", got "outdent"?

### ISSUE THREAD

**Issue by Zidcov** [stylus/stylus#2015]
I use the Stylus with Webstorm. Tell me, please, I have to set indents in Webstorm to avoid the following error 
```
"expected "indent", got "outdent"
```
selector
```
.menu
    padding: 0
    margin: 0
    list-style: none
    display: flex
    flex-wrap: wrap
```
The message from consol:
>"An error occurred while compiling css.
>ParseError in plugin 'gulp-stylus'
>Message:
>D:\project\markup\modules\main.styl:797:1
793| color: $color-font-base
794| text-align: center
795| text-transform: uppercase
796|
797| .menu
--------^
798| padding: 1
799| margin: 0
expected "indent", got "outdent"

**Comment by Panya** [comment]
Hmm, I can't reproduce this with your example. I guess you got the error because from the stack trace I see that you have different indentation (actually zero indentation) on the previous selector's group. But it would be better if you show full source of the file that you're trying to compile.

**Comment by Panya** [comment]
Also, the error message can be caused if you're mixing tabs and spaces for indentation.

**Comment by Zidcov** [comment]
Panya, thank you so much! In fact, the error was on the previous selector's group (different indentation).
