### ISSUE TITLE
How to store multi shadows in hashes?

### ISSUE THREAD

**Issue by FezVrasta** [stylus/stylus#2017]
How can I make this working?

```
shadow = {
  z1: 0 1px 6px 0 rgba(0, 0, 0, 0.12), 0 1px  6px 0 rgba(0, 0, 0, 0.12)
  z2: 0 8px 17px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19)
}
```

Looks like it doesn't like the commas...

The only solution I have found is:
```
shadow = {
  z1: unquote('0 1px 6px 0 rgba(0, 0, 0, 0.12), 0 1px  6px 0 rgba(0, 0, 0, 0.12)')
  z2: unquote('0 8px 17px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19)')
}
```

but it looks an hack to me

**Comment by kizu** [comment]
The easiest way to achieve this is to do this:

``` Stylus
shadow = {}
shadow['z1'] = 0 1px 6px 0 rgba(0, 0, 0, 0.12), 0 1px  6px 0 rgba(0, 0, 0, 0.12)
shadow['z2'] = 0 8px 17px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19)
```

Hash values can't contain lists with commas as the comma is a delimiter for hash values.

**Comment by FezVrasta** [comment]
Thanks!

**Comment by FezVrasta** [comment]
@kizu I have noticed this problem but I'm not sure if it's just me or something wrong with stylus, should I ask it here?

http://stackoverflow.com/questions/32845976/hashes-getters-dont-working-properly-in-stylus

**Comment by kizu** [comment]
@FezVrasta See #1405, and there were also a few similar questions at SO too. tl;dr: Hash getters using the dot would work only when you're using the colon between the property and value, otherwise Stylus' parser can't disambiguate it from the selector right now.

**Comment by FezVrasta** [comment]
I see, thanks

**Comment by JonDum** [comment]
> otherwise Stylus' parser can't disambiguate it from the selector right now.

@kizu Wait, what? Can stylus not tell the different between a property and a selector? If it can, then surely it should know that anything after a property won't be a selector and it can interpolate the hash safely. No?

**Comment by Panya** [comment]
@JonDum
>  If it can, then surely it should know that anything after a property won't be a selector and it can interpolate the hash safely. No?

No. See example that I described [here](https://github.com/stylus/stylus/issues/1405#issuecomment-36175169).
