### ISSUE TITLE
Need to remove a property from a custom function

### ISSUE THREAD

**Issue by soubok** [stylus/stylus#2021]
Hello,
I would like to return a value or remove a property from within a custom function (like postfix If operator does).

		var styl = require('stylus')(`
			div
				height 123px if false
				width FOO()
		`);

		styl.define('FOO', function(node) {
			if ( ok )
				return new stylus.nodes.Unit('456', 'px');
			else
				// what should I do here to remove the current property?
		});

		console.log(styl.render());

Thanks

**Comment by Panya** [comment]
You can't do this from custom function. And probably this is out of Stylus scope. I guess tools like PostCSS is better suitable for your task. But could you explain which task you're trying to solve with this function?

**Comment by soubok** [comment]
I am creating a 'tool' that transforms the following stylus code:
```
div
	width FOO({ S:1em, M:2em, L:10em })
	height FOO({ S:10em })
```

into the following CSS:
```
	.S div {
		width:1em;
		height:10em;
	}
	.M div {
		width:2em;
	}
	.L div {
		width:10em;
	}
```

**Comment by Panya** [comment]
Well, after few minutes of thinking I can suggest you a hacky way to do this:
```js
styl.define('FOO', function(node) {
    if (ok) {
        return new stylus.nodes.Unit('456', 'px');
    } else {
        var block = this.currentBlock
           , head = block.nodes.slice(0, block.index)
           , tail = block.nodes.slice(block.index + 1);
        block.nodes = head.concat(tail);
    }
});
```
But this method heavily depends on internal implementation of Stylus' `Evaluator` object. And it can be changed in the future. We will change behavior of properties with `null` values and in the nearest future you could just return `stylus.nodes.null` in this case (see #2019)

**Comment by FranckFreiburger** [comment]
Thanks! I will follow #2019
