### ISSUE TITLE
proposal: Couple tests and documentation

### ISSUE THREAD

**Issue by FranzSkuffka** [stylus/stylus#2022]
Stylus is a well tested software project, but the documentation does not cover all this.
My proposal is to directly integrate the documentation into the tests as comments and then rendering these comments to html using something similar to an [automatic styleguide generator](https://github.com/morishitter/postcss-style-guide).
What do you think?

**Comment by kizu** [comment]
Tests and documentation are wrote for different purposes, while in some cases they can be merged a bit (like using docs in tests, checking if all the examples are actually rendering as written), I'm against using autogenerated docs for describing features in general — the result is often not human readable.

Automatic generation is good for documenting API (jsdoc), or visual styleguides, Stylus is a different beast entirely.
