### ISSUE TITLE
evaluate a stylus expression

### ISSUE THREAD

**Issue by soubok** [stylus/stylus#2023]
I am trying to evaluate a stylus expression: foo(1px) with user-defined function foo().
I use the following code:

		var stylus = require('stylus');
	
		var str = 'foo(1px)';

		var options = { 
			functions: {
				foo:function(n) {
					
					return n;
				}
			}
		}

		var ast = new stylus.Parser(str, options).expression();
		ast = new stylus.Evaluator(ast, options).evaluate();

		console.log('AST:', ast)

but I do not understand the result:
```
log: Expression {
  nodes:
   [ Call {
       name: 'foo',
       args: [Object] },
     Unit {
       val: 1,
       type: 'px',
       raw: '1px' },
     Call {
       name: 'foo',
       args: [Object] } ],
  isList: undefined }
```

I expect to have only one Unit node without both Call nodes.

**Comment by Panya** [comment]
You need to tell the Evaluator that this is a function call (not mixin):
```js
var stylus = require('stylus');
var str = 'foo(1px)';
var options = {
    functions: {
      foo:function(n) {
        return n;
      }
    }
}

var ast = new stylus.Parser(str, options).expression();
var evaluator = new stylus.Evaluator(ast, options);
evaluator.return = true;
ast = evaluator.evaluate();
console.log('AST:', ast)
```
