### ISSUE TITLE
Use of dynamic variables - variable inside variable not possible?

### ISSUE THREAD

**Issue by luxmedia** [stylus/stylus#2025]
I have something like this:

1. Variables like:
```stylus
$shadow-button = 1px 1px 3px #333
$shadow-button-hover = 1px 1px 3px #000
...
```
2. A mixin which accepts a string ( = $type)

3. Inside the mixin i would like to use this string as a name for a variable to avoid an endless if else if ...

```stylus
// $type : switch, button, searchbar, appbar, card, floatingbutton, menu, submenu, navdrawerleft, navdrawerright, modal, dialog
shadow-elevation($type) {
        $shadow = $shadow-{$type}
        $shadow-hover = $shadow-{$type}-hover
box-shadow: $shadow
...
}
```
...
```stylus
.mybutton-with-shadow {
shadow-elevation(button)
}
```

The problem is, that the declaration $shadow-{$type} in the mixin does not compile as $shadow-button and then to the corresponding variable value, instead i get a compilation error somewhere else in my stylus file. But the issue lies in this dynamic declartion.

Is this kind of dynamic variable usage possible with stylus and if so, how?

Regards
Volker

**Comment by Panya** [comment]
You can use [lookup bif](http://learnboost.github.io/stylus/docs/bifs.html#lookupname) in this case.

**Comment by luxmedia** [comment]
Exactly what i was looking for. Thank you very much!!
