### ISSUE TITLE
Сomments in json

### ISSUE THREAD

**Issue by xBrainstem** [stylus/stylus#2026]
In some projects (for example, Cromium) you can use comments in json. json(path[, options]) does not understand comments. The developers have a large json library. It would be very useful for Stylus can work with comments in json.
Can be connect, for example, JSON.minify(https://github.com/getify/JSON.minify) to the Stylus?

**Comment by Panya** [comment]
I think we need to stick to the JSON standard here (there is no support for comments yet). But if you really need this feature you can easily add custom json function using Stylus JS API and libs like https://github.com/aseemk/json5. See [source](https://github.com/stylus/stylus/blob/dev/lib/functions/json.js) of `json` bif for more details.

**Comment by xBrainstem** [comment]
Thanks for information.
I thought about using Stylus JS API, but I really want to use the Stylus from box. Would be a very nice option, if you can give a connection point between JSON.parse and readFile (https://github.com/stylus/stylus/blob/dev/lib/functions/json.js#L55):
var json = JSON.parse(readFile(found, 'utf8')).
What do you think about adding in jsonbif option "path | string": json(path | string[, options]), with path for default and we can work with native jsonbif and with some other parsers before using jsonbif and with JSON inside Stylus?

**Comment by Panya** [comment]
> UPD. I copied the function jsonbif from source, and got different results.
copied jsonbif: {"black":"#000000","white":"#FFFFFF",...
native jsonbif: {"black":"((#000))","white":"((#fff))",...
Faster to use a preprocessor before Stylus for json :)

Then you copied it wrong :) The native function uses `utils.parseString` to coerce JSON strings to Stylus nodes (see https://github.com/stylus/stylus/blob/dev/lib/functions/json.js#L67-L80).

> I think сonnection point between JSON.parse and readFile usefull feature.

I'll will accept a PR with this change.

**Comment by xBrainstem** [comment]
> Then you copied it wrong :)

Yes, Parser don't work. Because I used ```var Parser = stylus.parser``` and ```catch (e)``` block worked in ```parseString(str)```. Must use ```var Parser = stylus.Parser```. Now I can use JSON or JSON5 with jsonbif.

> I'll will accept a PR with this change.

Good news.Will wait for the new extension to work with JSON in Stylus.

Thanks for the help!
