### ISSUE TITLE
Source map points to a wrong line in stylus file in Chrome

### ISSUE THREAD

**Issue by focused** [stylus/stylus#2027]
I have no idea is it a Stylus or a Brunch bug, I use Brunch tool to build css files. Just made issue here https://github.com/jas/stylus-spritesmith-brunch/issues/2

<img width="403" alt="screen shot 2015-10-11 at 13 26 19" src="https://cloud.githubusercontent.com/assets/1449828/10416371/4c43330a-701d-11e5-93e5-b2b0948fa0ab.png">
<img width="490" alt="screen shot 2015-10-11 at 13 26 53" src="https://cloud.githubusercontent.com/assets/1449828/10416372/4c6ba72c-701d-11e5-805a-1939737ca058.png">

**Comment by Panya** [comment]
Well, screenshots of code are not so useful for debugging the issue. Could you provide a minimal test case?

**Comment by Panya** [comment]
I'm closing this issue due lack of response.
