### ISSUE TITLE
media query without content cause error

### ISSUE THREAD

**Issue by atilkan** [stylus/stylus#2035]
if i write and leave a line without content it doesn't preprocess, gives parse error. 

**@media only screen and (max-width: 25em)**

Error:
expected "indent", got "eos"
node_modules/stylus/lib/parser.js:257:11
more lines of error output pointing mostly same file.

I do this to pass it.
**@media only screen and (max-width: 25em)**
    **// staff**

**Comment by Panya** [comment]
That is intended behavior. If you're not using CSS-style syntax, parser expects that after the media query there will be an indented block with code. You can leave the condition with empty brackets:
```styl
@media only screen and (max-width: 25em) {}
```
