### ISSUE TITLE
Error when using @font-face with unicode-range

### ISSUE THREAD

**Issue by ibc** [stylus/stylus#2038]
The following fails to compile to CSS:

```
@font-face
  font-family: 'Russo One'
  src: local('Russo One'),
       local('RussoOne-Regular'),
       url('resources/fonts/russoone-cyrillic.woff2') format('woff2')
  font-style: normal
  font-weight: 400
  unicode-range: U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116
```

error:

```
Message:
   33|        local('RussoOne-Regular'),
   34|        url('resources/fonts/russoone-cyrillic.woff2') format('woff2')
   35|   font-style: normal
   36|   font-weight: 400
   37|   unicode-range: U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116
-----------------------------------^

expected "indent", got "literal U+0400-045F"
```

However that is the correct syntax for `unicode-range`:

https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/unicode-range

**Comment by ibc** [comment]
By adding {  } it works:

```
@font-face {
  font-family: 'Russo One'
  src: local('Russo One'),
       local('RussoOne-Regular'),
       url('resources/fonts/russoone-cyrillic.woff2') format('woff2')
  font-style: normal
  font-weight: 400
  unicode-range: U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116
}
```

**Comment by Panya** [comment]
Hmm, I can't reproduce it with the latest version of Stylus (0.52.4). You can try your example online on http://learnboost.github.com/stylus/try.html or http://codepen.io

**Comment by ibc** [comment]
Strange as I use `gulp-stylus` which depends on `"stylus": "^0.52.4"`.

**Comment by Panya** [comment]
Also, from the error message seems like you have mixed indentation (e.g. tabs and spaces)...

**Comment by ibc** [comment]
Right, by using a single TAB for indentation and the spaces for "format" it does not fail.

Thanks.
