### ISSUE TITLE
Measurements with unknown units rendered with extra space.

### ISSUE THREAD

**Issue by phyllisstein** [stylus/stylus#2044]
Hey there! I've been having some trouble using Stylus with a couple of PostCSS plugins---namely, [`modular-scale`](https://github.com/kristoferjoseph/postcss-modular-scale) and [`vertical-rhythm`](https://github.com/markgoodyear/postcss-vertical-rhythm). The vertical rhythm plugin establishes a new `vr` unit, scanning for CSS like `1vr`; the modular scale plugin looks for expressions like `ms(1)rem`. In both cases, Stylus breaks their functionality by inserting a space before the unit. This Stylus source:

```stylus
.foo-class
  font-size ms(1)rem
  margin 1vr 0
```

...renders to this CSS:

```css
.foo-class {
  font-size: ms(1) rem 0;
  margin: 1 vr 0;
}
```

I'm still familiarizing myself with the source code, so I'm not sure whether or how it _could_ be fixed, let alone if it _should_. But it'd be great to have this resolved, especially given how the conversation in #745 ended.

Thanks for all your work on Stylus! It's my fave.

**Comment by Panya** [comment]
Thanks for filling the issue. Not sure about the second case (`ms(1)rem`) but we defenetly should fix the first one.

**Comment by phyllisstein** [comment]
From what I can see, the lexer assumes that `vr` is an `Ident` because it's not on the units whitelist. A quick fix would be changing the line at <https://github.com/stylus/stylus/blob/dev/lib/lexer.js#L46> from this:

```js
// lib/lexer.js:46
var unit = new RegExp('^(-)?(\\d+\\.\\d+|\\d+|\\.\\d+)(' + units + ')?[ \\t]*');
```

...to something like this:

```js
// lib/lexer.js:46
var unit = new RegExp('^(-)?(\\d+\\.\\d+|\\d+|\\.\\d+)([a-z]+|%)?[ \\t]*');
```

Using `[a-z]` instead of something like `\w` keeps the match _fairly_ conservative. I can't think of a case where Stylus treats `2xx` in the algebraic sense, as "the identifier `xx` multiplied by the number two," so it seems safe to expand the regex. (Which drops `Hz` and `kHz` as units, but the test suite still passes.)

Still trying to think through the modular scale case myself---good luck!
