### ISSUE TITLE
Compile error on filter: alpha()

### ISSUE THREAD

**Issue by nathanhornby** [stylus/stylus#2045]
I'm just trying to include the [Magnific](https://github.com/dimsemenov/Magnific-Popup/blob/master/dist/magnific-popup.css) default stylesheet, however when compiling (in Meteor) I'm getting the following error:

```
   While building the application:
   error: Stylus compiler error:
   client/stylus/801-magnific.import.styl:12:27
   8|   overflow: hidden;
   9|   position: fixed;
   10|   background: #0b0b0b;
   11|   opacity: 0.8;
   12|   filter: alpha(opacity=80);
   ---------------------------------^
   13| }
   14|
   15| .mfp-wrap {

   Cannot read property 'a' of undefined
   at ".mfp-bg " (client/stylus/801-magnific.import.styl:2:25)
```

The CSS itself:
```
.mfp-bg {
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 1042;
  overflow: hidden;
  position: fixed;
  background: #0b0b0b;
  opacity: 0.8;
  filter: alpha(opacity=80);
}
```

Bug or am I missing something obvious? Google isn't helping with this one.

**Comment by Panya** [comment]
You should use `unquote` here. See the [documentation](http://learnboost.github.io/stylus/docs/selectors.html#disambiguation). Also if you leave `.css` extension for the file and use `"include css": true` option (or `--include-css` CLI flag), then Stylus will inline this file as-is (without parsing).

**Comment by nathanhornby** [comment]
Gotcha @Panya - cheers.
