### ISSUE TITLE
Property lookups don't work with !important

### ISSUE THREAD

**Issue by nathanhleung** [stylus/stylus#2046]
I have a utility class, `.facebook`, and I want to have elements with that class have a lightened background on hover.  However, the `@background` property lookup syntax doesn't work with `!important`.  Maybe this could be changed so only the string between `background` and `!important` is gotten, and then `!important` is appended to the end of the property lookup?  Or am I missing something?  Thanks!

```stylus
.facebook
  background #3b5998 !important
  
  &:hover
    background lighten(@background, 10%)
```

**Comment by futekov** [comment]
The problem is that stylus understands this as `lighten(#3b5998 !important, 10%)`, where the first argument is actually not a color.
To achieve what you want you need to tell the property lookup to look at only the first item (the color) like so:
``` stylus
.facebook
  background #3b5998 !important

  &:hover
    background lighten(@background[0], 10%)
```

**Comment by Panya** [comment]
Yep, @futekov is right :)
