### ISSUE TITLE
Prevent prefixing for a function

### ISSUE THREAD

**Issue by ALibrada** [stylus/stylus#2047]
Hello,

I am trying to prevent the generation of prefixes for every vendor when using "linear-gradient". Is there any way to prevent the generation of prefixes just for a function and not globally?

My case is the following:
I have a index.styl
```stylus
@require "nib/lib/nib"

@import "gradients"
```

and a gradients.styl
```stylus
.gradient
    linear-gradient(...)
```

I would like to prevent the generation of every vendor prefix just for linear-gradients. Any help is appreciated. 

Thanks in advance

**Comment by Panya** [comment]
You can redefine `vendor-prefixes` variable (defined in `nib`):
```styl
@require "nib/lib/nib"

_prefixes = vendor-prefixes
vendor-prefixes = official
@import "gradients"
vendor-prefixes = _prefixes
```

**Comment by ALibrada** [comment]
Thanks a a lot! That solved it! :smile:

**Comment by Panya** [comment]
> Would it be any possibility adding that to the documentation? It's a great feature

Well, the question is more related to [nib](https://github.com/tj/nib). Feel free to open an issue there.
