### ISSUE TITLE
@import and @require with glob pattern

### ISSUE THREAD

**Issue by rstoenescu** [stylus/stylus#2051]
I believe it's a good idea to be able to import multiple files at once using a glob pattern.
Otherwise we are required to preprocess .styl files to change their content before being fed to Stylus, which adds unnecessary complexity.

Example:
``` js
@import 'core/*/*.styl'
@import 'features/**/*.styl'
@require 'widgets/*.styl'
```

**Comment by Panya** [comment]
It's already possible see [the documentation](http://learnboost.github.io/stylus/docs/import.html#file-globbing).

**Comment by hiulit** [comment]
Is this possible using the client side version of stylus?  Because I'm getting an error "glob is not defined". Thanks.
