### ISSUE TITLE
ParseError: expected "indent" got "ident nav"

### ISSUE THREAD

**Issue by Ryaba** [stylus/stylus#2055]
47| @media screen and (max-width: 600px)
 48|          nav
-----------^
 49|          height auto
 50|          nav ul
 51|          width 100%

**Comment by Panya** [comment]
You need to indent your code, like so:
```styl
@media screen and (max-width: 600px)
  nav
  ...
```
or you can use CSS-like syntax:
```styl
@media screen and (max-width: 600px) {
nav {
...
}
}
```
