### ISSUE TITLE
Stylus and CoffeeScript? 

### ISSUE THREAD

**Issue by acterhd** [stylus/stylus#2056]
Hello. Can I mix CoffeeScript and Stylus? Make shared constant variables? Custom (programmable) mixins by CoffeeScript? 

```
mixin = (props, arguments)=>
  backgrounds = someAPI.splitBackgrounds(arguments)
  backgrounds.shift() //Remove one layer
  props["background-image"] = backgrounds.join(", ")
```

**Comment by Panya** [comment]
Why not? It is JS after all, therefore you can use [Stylus JS API](http://learnboost.github.io/stylus/docs/js.html) with it. Also you can use [json bif](http://learnboost.github.io/stylus/docs/bifs.html#jsonpath-options) for sharing constant variables.

**Comment by acterhd** [comment]
How I can use calc() in stylus?

**Comment by Panya** [comment]
```styl
.test
  width: calc(100% - 10px)
```
Should works. If you want to use some variable in the `calc()` expression you can write something like this:
```styl
$var = 10px
.test
  width: 'calc(100% - %s)' % $var
```

P.S. StackOverflow is better place for these questions.

**Comment by acterhd** [comment]
I in JS API not found custom mixins. Where I can found?

**Comment by Panya** [comment]
What do you mean by "custom mixins"? You can define a mixin using [define](http://learnboost.github.io/stylus/docs/js.html#definename-fn) method.

**Comment by acterhd** [comment]
I mean mixing with programmable argument usage.

**Comment by Panya** [comment]
Please, read the documentation.

**Comment by acterhd** [comment]
Okay... Can I with browserify use Stylus in browser?

**Comment by Panya** [comment]
We have a special [client](https://github.com/stylus/stylus/tree/client) branch for client-side usage. You can use browserify with its content, but we don't recommend use Stylus in browser. This branch is for dev purposes only (we're using it on [try stylus](http://learnboost.github.io/stylus/try.html) page).

**Comment by acterhd** [comment]
Sorry, but why not make client-side library for operate with CSS defines? 
For example, mixins, operations and etc. with "style" of DOM elements?
