### ISSUE TITLE
Authorise an output with a different extension (eg.: output.css.erb instead of output.css only)

### ISSUE THREAD

**Issue by FuriouZz** [stylus/stylus#2060]
Hello, I am currently working in Ruby. I would like to compile my stylus file into a css file and this css can be readed like an ERB template. 

These lines create a file :
```bash
stylus app/index.styl public/main.css
stylus < app/index.styl > public/main.css
stylus app/index.styl --out public/main.css
```

Theses lines try make `public/main.css.erb/index.css` :
```bash
stylus app/index.styl public/main.css.erb
stylus app/index.styl --out public/main.css.erb
```
I suggest to create a function `isFilename()` like that :
```javascript
function isFilename(path) {
  return extname(path).length > 0
}
```

And replace these two conditions [L412](https://github.com/stylus/stylus/blob/dev/bin/stylus#L412) and [L6693](https://github.com/stylus/stylus/blob/dev/bin/stylus#L693) with :

```javascript
// FROM
extname(dest) === '.css'

// TO
isFilename(dest)
```

**Comment by Panya** [comment]
Well, each path with a dot in it would return true with this check? Even if it's a dir with a dot. Rare case, I know, but anyway it would be a breaking change.

**Comment by FuriouZz** [comment]
`extname()` returns a length equals to 0 when you give a dir with a dot.

**Comment by Panya** [comment]
If it starts with a dot yep, but if you have a dir with name `some.dir` and use Stylus like so:
```
stylus some.styl --out some.dir
```
It would return `.dir`.

**Comment by FuriouZz** [comment]
Oh! OK =( Sad world!
