### ISSUE TITLE
Bug when using CSS calc function (again)

### ISSUE THREAD

**Issue by marvinroger** [stylus/stylus#2062]
The issue is quite the same as described [here](https://github.com/stylus/stylus/issues/687).

With Stylus 0.52.4:

```css
calc(100% + 6em)
```

results in the faulty CSS:

```
calc(0px + 106%)
```

**Comment by Panya** [comment]
I cant reproduce it, sorry. You can try your example online on http://learnboost.github.io/stylus/try.html or CodePen to make sure that all works as expected. I bet you have some mixin or plugin that produces this behavior.

**Comment by marvinroger** [comment]
You're right, this is kouto-swiss's fault. Thanks!
