### ISSUE TITLE
Bug: Partial Reference

### ISSUE THREAD

**Issue by Cactucs** [stylus/stylus#2067]
The code from [example](https://learnboost.github.io/stylus/docs/selectors.html#partial-reference)
``` Stylus
.foo
  &__bar
    width: 10px

    ^[0]:hover &
      width: 20px
```

Compiles to: 
``` Stylus
.foo__bar {
  width: 10px;
}
^[0]:hover .foo__bar {
  width: 20px;
}
```

**Comment by kizu** [comment]
Which Stylus' version do you use? I can't reproduce it in 0.53.0, you can try it yourself at http://learnboost.github.io/stylus/try.html

**Comment by Panya** [comment]
It's new stuff (was added in 0.53.0 yesterday). Try to update Stylus.
