### ISSUE TITLE
Conditional assignment combined with define produces invalid css

### ISSUE THREAD

**Issue by Sivitas** [stylus/stylus#2068]
I'm using gulp-stylus. When I define a variable that has only a conditional assignment, the resulting css has an artifact when combined with define. 

gulpfile.js
```js
var gulp = require('gulp'),
  gulpStylus = require('gulp-stylus'),
  stylus = require('stylus');

gulp.task('default', function() {
  gulp.src('main.styl')
    .pipe(gulpStylus({ define: { random: new stylus.nodes.Literal('#321') } }) // this define
    .pipe(gulp.dest('.'));
});
```

main.styl
```styl
random := #123

div
  color random
```
produces 

main.css
```css
#321 /* The artifact */
.test {
  color: #321;
}
```

If I do `random = #123`, the define isn't applied (assuming it's overwritten)
If I don't use define, the artifact disappears

Tested on 0.52.4 and 0.53.0 (manually updated gulp-stylus to use 0.53.0 but not sure if things lined up properly)

**Comment by Panya** [comment]
Thanks for the report. I've fixed this bug in the `dev` branch. The fix will be in the next release.
