### ISSUE TITLE
Converters from SCSS?

### ISSUE THREAD

**Issue by danielmeng07** [stylus/stylus#2069]
Hey!

Not sure if this is within context, but I'll post it anyway. 

We're building an app using Ionic Framework, and we're noticing they're only supporting SCSS. Quite a few people are requesting that they add support for Stylus, but they haven't gotten around to doing it. 

I was wondering if you guys have plans to make a SCSS converter with glob support?

**Comment by Panya** [comment]
Hi.

I'm not sure if they work with glob, but you can try https://github.com/mojotech/sass2stylus and https://github.com/paulcpederson/sass2stylus
