### ISSUE TITLE
Default relative source maps go back one directory too far when --out is a file name

### ISSUE THREAD

**Issue by jakelucas** [stylus/stylus#2070]
Running the `stylus` command on a file and letting it generate a `.css` file and a `.map` file produces the correct paths to the source files in the `.map`'s `sources` field, and will work correctly when `--out` is set as a directory.

However when `--out` is set as a file path, rather than a directory the source map generation does not take the fact that it is a file into account and appears to treat the file name as a directory as well.

This causes the `sources` values in the `.map`. file to go back (`../`) one too many directories.

To reproduce create a `test.styl` file and next to it create a `compiled` directory.

Then run the following: `stylus -c -m --out "./compiled/new-name.css" "test.styl"`

If you open the generated `.map` file you should see `"sources":["../../test.styl"]` which is incorrect and should be `"sources":["../test.styl"]`.

In my tests I have noticed that the `--sourcemap-root` and `--sourcemap-base` options do nothing to resolve this and can confirm that it is only a problem when `--out` specifies a file rather than a directory.

The change that allowed support for `--out` to take a file path can be seen here: https://github.com/stylus/stylus/commit/fe3a23af5d6c47f19ea4381c6fd95e989596f07d

I will try looking into this myself, but I don't know the Stylus code base at all, so any help pointing me in the right direction would be appreciated, unless someone else knows how to solve this.

**Comment by Panya** [comment]
Thanks for the report. I've fixed this bug in the `dev` branch. The fix will be in the next release.
