### ISSUE TITLE
Can't use global variables as a part of expressions

### ISSUE THREAD

**Issue by vsorrokin** [stylus/stylus#2072]
I use gulp-stylus with globals param
```
stylus({
  globals: {
    "$red": "#E20303"
  }
})
```

And when try to use global var like this
```
.text
  color: rgba($red, .8)
```
Then stylus throws error *Cannot read property 'nodeName' of undefined*

But if to write the style like this (without any additional expression)
```
.text
  color: $red
```
Then style compiles without errors.

**Comment by Panya** [comment]
Thanks for the report. I've fixed this bug in the `dev` branch.
