### ISSUE TITLE
Add function to return keys index in list

### ISSUE THREAD

**Issue by iDev0urer** [stylus/stylus#2077]
SASS has a function called index that returns a keys index in an array. It would be really helpful if Stylus had a similar function. Unless it does and I'm missing something. Thoughts?

**Comment by Panya** [comment]
We don't have a function like Sass' `index` currently, but you can write it using JS API. Something like:
`index-of.js`
```js
var utils = require('stylus').utils;

module.exports = function() {
  return function(style) {
    style.define('index-of', function(list, value) {
      list = utils.unwrap(list);
      value = value.first.val;

      for (var i = 0; i < list.nodes.length; i++) {
        if (value === list.nodes[i].val) {
          return i;
        }
      }

      return style.nodes.null;
    }, true);
  };
};
```
And use it like so:
```styl
use('index-of.js')

body
  color: index-of(('red' 'green' 'blue'), 'green')
  border-style: index-of(1px solid red, solid)
```
Compiles to:
```css
body {
  color: 1;
  border-style: 1;
}
```

I'll add this function to the core.

**Comment by iDev0urer** [comment]
Awesome! When do you think it'll be added to the core and pushed to NPM so I can update? Gotta tell you, it's nice to get  a helpful response so quickly. Keep up the good work!

**Comment by Panya** [comment]
I think we'll release a patch release in January with the function and other fixes.

P.S. It's even easier to write the function in Stylus:
```styl
index($list, $value)
  for $val, $i in $list
    return $i if $list[$i] == $value

body
  test: index(1px solid red, solid) // => 1
  test: index(red green blue, blue) // => 2
```

**Comment by Panya** [comment]
http://stylus-lang.com/docs/bifs.html#indexlist-value
