### ISSUE TITLE
How to generate an error?

### ISSUE THREAD

**Issue by jenius** [stylus/stylus#2082]
Weird issue I know. But I have a library in which I test stylus to make sure that, given some clearly BS code (I use `214m2/3l`, just keyboard mashing really), it will generate an error. This has always worked for me in the past, faithfully giving an error through the callback, until recently. Now it simply returns an empty string.

Is there a more reliable way to produce an error? Is returning an empty string appropriate here? Or is it an error that it's not giving me an error?

**Comment by Panya** [comment]
In 0.53.0 we're supporting unknown units, so `214m2` is valid unit now. To get an error you can use `error()` bif:
```styl
error('some error')
```

**Comment by jenius** [comment]
Perfect, thanks so much :+1:
