### ISSUE TITLE
Several src directories for middleware

### ISSUE THREAD

**Issue by adius** [stylus/stylus#2083]
Is there a way to specify several source directories for the middleware?

**Comment by Panya** [comment]
Well, there is currently no easy way to specify more than one source directory. But you can generate source or destination paths manually by specifying `src` or `dest` option with a function that accepts requested path as a parameter:
```js
app.use(stylus({
    src: function(p) {
        p = p.replace(/\.css$/, '.styl');
        if (...) {
            return path.join(__dirname, 'src', 'one', p);
        } else {
            return path.join(__dirname, 'src', 'two', p);
        }
    },
    dest: path.join(__dirname, 'css')
}));
```

**Comment by devgg** [comment]
Hi @Panya 
could you please elaborate a bit more?
app.use() expects a middleware but stylus({}) does not return one.
Thank you!

**Comment by Panya** [comment]
@devgg, in my answer by `stylus` I mean `var stylus = require('stylus').middleware`, sorry for confustion.
