### ISSUE TITLE
Support passing options to plugins via CLI

### ISSUE THREAD

**Issue by yaycmyk** [stylus/stylus#2087]
Currently you can add a plugin via `stylus -u plugin input -o output`, it would be nice to be able to pass in configuration as well.

Browserify handles this in their CLI with the following syntax:

```bash
browserify input -t [ eslintify --continuous ] > output
```

`eslintify` being the name of the plugin (in Browserify's case, "transform") and `--continuous` being a boolean flag.

Stylus's CLI could be extended to work in a similar way:

```bash
stylus -u [ plugin --option ] input -o output
```

**Comment by yaycmyk** [comment]
So digging into the code I noticed that this is already kind of supported via an undocumented flag `--with`. Perhaps we can just add documentation on this to the site?

**Comment by Panya** [comment]
It's already documented [here](http://stylus-lang.com/docs/executable.html#utilizing-plugins).
