### ISSUE TITLE
connect middleware path flexibility

### ISSUE THREAD

**Issue by devgg** [stylus/stylus#2090]
I would like a feature for modifiying the source and destination paths (example: [less](https://github.com/emberfeather/less.js-middleware/wiki/Examples#modifying-the-less-path)). I think it is to restricting to force the same directory structure on source and destination. At the moment I am working on a modular site where I have multiple directories with stylsheets and there is no good solution to avoid name clashes.

**Comment by Panya** [comment]
Possible duplicate of #2083.
