### ISSUE TITLE
Setting a function as a default argument for a mixin does not work

### ISSUE THREAD

**Issue by juice49** [stylus/stylus#2091]
I've found something that appears to be a bug when setting a function as a default argument for a mixin.

[Here is a CodePen demonstrating the issue](http://codepen.io/Ash/pen/PZQNyy).

CodePen uses Stylus 0.50.0, however I get the same results when testing with 0.53.0.

Hopefully the CodePen make sense. If I can provide any more details, or if examples placed directly here would be more useful, let me know 😊.

**Comment by Panya** [comment]
Thanks for the report. I've fixed this bug in the `dev` branch. The fix will be in the next release.

**Comment by juice49** [comment]
Thanks Panya!
