### ISSUE TITLE
Error reporting not working as supposed.

### ISSUE THREAD

**Issue by iammarkoradak** [stylus/stylus#2092]
First of - ```ensure function``` that you showcased in the documentation is not acting as supposed - *see first screenshot*. There are braces added around ```'type'```.

Other than that, any error is thrown from the line that defined it, instead of the line where you actually made an error - *see second screenshot*. Error should occur at ```body { border-radius: '5px' } ```. It's same with whatever error I tried, as well as if error is defined in the same file, or in an import.

**Comment by iammarkoradak** [comment]
![screenshot 2016-01-23 10 36 48](https://cloud.githubusercontent.com/assets/9327301/12529621/673a5bf0-c1be-11e5-99b6-fec7a5197c88.png)

![screenshot 2016-01-23 10 37 28](https://cloud.githubusercontent.com/assets/9327301/12529622/6ad0acba-c1be-11e5-9cc4-59633461426c.png)

**Comment by Panya** [comment]
Yep, outdated information in the docs + small bug. Thanks for the report.
