### ISSUE TITLE
Using Regular Expressions with If / Else Statements

### ISSUE THREAD

**Issue by moshemo** [stylus/stylus#2094]
Is it possible to use regular expressions with If / Else statements?

Basically, what I would like to do is to test if an argument for a mixing begins with certain characters.  For instance: 'hor' or 'horiz' or 'horizontal' would all register true for one option and 'ver', 'vert', and 'vertical' would register true for a different option.

Is this possible?  If so, how?

Thanks.

**Comment by Panya** [comment]
Yep, you can use `match(pattern, str)` bif (not yet documented, #1855). See examples of usage in the tests ([.styl](https://github.com/stylus/stylus/blob/dev/test/cases/bifs.match.styl), [.css](https://github.com/stylus/stylus/blob/dev/test/cases/bifs.match.css)).

**Comment by moshemo** [comment]
Thanks.
