### ISSUE TITLE
Throw error if "@import xyz.css" is not at beginning of file

### ISSUE THREAD

**Issue by dominiklenne** [stylus/stylus#2095]
While @import "xyz.styl" can be everywhere, "@import xyz.css" cannot. 

It would be a mere enhancement for clueless people like me, saving time in debugging, thank you for considering.

**Comment by Panya** [comment]
You can use `--hoist-atrules` flag to move imports to the top.

**Comment by dominiklenne** [comment]
Thanks - - -

Dominik
  ----- Original Message -----
