### ISSUE TITLE
CSSComb support

### ISSUE THREAD

**Issue by corysimmons** [stylus/stylus#2096]
It doesn't seem like the maintainer is going to implement it himself.

Anyone up for the challenge?

https://github.com/csscomb/csscomb.js/issues/159#issuecomment-48598982

**Comment by solovets** [comment]
+1
Csscomb is quite popular tool, it'll be cool to help comb team to implement interpretation of Stylus.

**Comment by corysimmons** [comment]
Use stylelint instead.
