### ISSUE TITLE
Using functions inside @media

### ISSUE THREAD

**Issue by acauamontiel** [stylus/stylus#2100]
Any chance to use [functions](http://stylus-lang.com/docs/functions.html) inside `@media`?

People are using [Rupture](https://jenius.github.io/rupture/) a lot, but it's ugly!

**This is worse...**

```styl
header
footer
	some-property value

	@media print
		display none

.element
	some-property value

	+from-width(3)
		another-property value
```

**...than this**

```styl
header
footer
	some-property value

	@media print
		display none

.element
	some-property value

	@media from('lg')
		another-property value
```

Currently is possible to use [variables](http://stylus-lang.com/docs/variables.html) inside `@media`, but it would be a good feature be able to use [functions](http://stylus-lang.com/docs/functions.html) too.

**Comment by acauamontiel** [comment]
Today I'm using this way: [Mantis Querist](https://github.com/mantisjs/mantis-querist)

**Comment by acauamontiel** [comment]
Today I'm using this way: [Mantis Querist](https://github.com/mantisjs/mantis-querist)

**Comment by Panya** [comment]
I don't understand how more abstracted `+from-width(...)` or `+media(...)` is uglier than `@media from(...)`. It's very subjective opinion, sorry. BTW you can also use hashes inside `@media`:
```styl
$from = {
  lg: '(max-width: 420px)'
}

@media $from.lg
  body
    color: red
```
Anyway, it would be possible in 1.0 (with new syntax for interpolation).
