### ISSUE TITLE
Best way to put variables inside of calc?

### ISSUE THREAD

**Issue by corysimmons** [stylus/stylus#2105]
Right now I'm doing `width: s('calc(100% * %s)', $fraction)` but that gets really hairy when I have several variables.

We should probably standardize variable interpolation as well. I think Sass does this pretty well. Their version looks like: `width: calc(100% * #{$fraction});` and is much more readable/enjoyable to work with.

**Comment by Panya** [comment]
You can simplify it a bit:
```styl
width: 'calc(100% * %s)' % $fraction
```
We'll change syntax of interpolation (see #728), so Sass' variant will be possible.

**Comment by corysimmons** [comment]
It's been open since 2012. I hate to complain since I know how hard you work @Panya but I think once https://github.com/postcss/postcss/issues/495 is fixed I'm gonna stop using Stylus. It would've been nice if Automattic dumped some resources into revitalizing/maintaining this project when they acquired it.

It's been fun Stylus. Thanks for being the best tool for CSS processing for so long.

**Comment by coloradude** [comment]
@Panya This fix only works like 1/3 of the time for me. Calc is constantly plaguing me.

**Comment by Panya** [comment]
@coloradude what do you mean by 1/3 of the time? This fix works in all cases where `s()` works. If you have more than one argument just wrap the arguments into brackets:
```styl
body
  width: 'calc(100% - %s * %s)' % (40px 10em)
```

**Comment by coloradude** [comment]
@Panya

```styl
$chevronSpacing = 40px
.white-space
    width 'calc(100% - %s)' % $chevronSpacing

$searchBarMargin = '20px'
.hero-header-search-wrapper
    width 'calc(100% - %s)' % $searchBarMargin

$buttonWidth = 225px
 input[name='email']
   width 'calc(100% - %s)' % $buttonWidth

```

The first two work, although in different ways (i had to make $searchBarMargin a string for some reason) and the last doesn't work either way. So 2/3 times I guess. At first I thought it could be the minifier i'm using but that doesn't explain why two work and one doesn't.

**Comment by Panya** [comment]
@coloradude hmm, I'm 100% sure that it's not Stylus' fault. See http://codepen.io/anon/pen/QyzXQK (view compiled CSS).

**Comment by coloradude** [comment]
@Panya Yeah you're right it must be the minifier removing spaces. The randomness is strange though. Thanks for your help.

**Comment by corysimmons** [comment]
@Panya Thoughts on adding better interpolation?

Something similar to this syntax would be awesome:

```styl
$fraction: 1/2

.column
  width: calc(100% * {$fraction})

// returns
.column {
  width: calc(100% * 1/2); // note it doesn't convert 1/2 to .5 automagically
}
```
