### ISSUE TITLE
Cannot call `.deps` before `.render`; incorrect sourcemaps

### ISSUE THREAD

**Issue by cspotcode** [stylus/stylus#2108]
Full reproduction case here: https://gist.github.com/cspotcode/27b0c93885864508f273

Basically, given a stylus instance:

    var styl = stylus(someCode);

if you call `styl.deps()` before calling `styl.render()` then the sourcemap will be wrong.  If you call `styl.deps()` *after* `styl.render()` then the sourcemap is fine.

If this isn't a bug, then it should probably be mentioned in the documentation.

I think the reproduction code illustrates the problem well, but let me know if you'd like further explanation.

**Comment by Panya** [comment]
Thanks for the report. I've fixed this bug in the `dev` branch. The fix will be in the next release.
