### ISSUE TITLE
Custom units will fails

### ISSUE THREAD

**Issue by LestaD** [stylus/stylus#2113]
example:

```styl
// demo.styl
.class
  width: 12dp
```

run:

```bash
stylus demo.styl -p
```

in output:

```css
.class {
  width: 12 dp;
}
```

![image](https://cloud.githubusercontent.com/assets/5620073/12887085/07c318a2-ce83-11e5-8c6d-7815f8dcbab1.png)

I want use stylus with [postcss](https://npmjs.com/postcss) with plugin [postcss-define-units](https://npmjs.com/postcss-define-units)

**Comment by Panya** [comment]
Unknown units are supported since 0.53.0. Try to update Stylus version.

**Comment by LestaD** [comment]
@Panya Thanx!!
