### ISSUE TITLE
Weird import bug with --resolve-url? Not getting any CSS output

### ISSUE THREAD

**Issue by thybzi** [stylus/stylus#2119]
I have the following file structure (minimal set to reproduce bug):
```
styl
|-- _base
|   `-- test
|       |-- index.styl
|       |-- main.styl
|       `-- vars.styl
|-- mobile
|   `-- test
|       |-- index.styl
|       |-- main.styl
|       `-- vars.styl
`-- mobile.styl
```

And the files content:

`_base/test/index.styl` and `mobile/test/index.styl`:
```styl
@import 'vars'
@import 'main'
```

`_base/test/main.styl` and `_base/test/vars.styl`: 
*no matter, may be even empty.*

`mobile/test/test.styl`
```styl
@import '../../_base/test/main'
.test
  color: red
```

`mobile/test/vars.styl`
```styl
@import '../../_base/test/vars'
```

`mobile.styl`
```styl
@import 'mobile/test'
```

All the `@import` constructs may be changed to `@require`, that doesn't change the thing. Which is:

**When I compile `mobile.styl`** to `mobile.css` **with `--resolve-url` flag, the output is empty** (no error, but just nothing is output)

Now, if I **remove import line from `mobile/test/vars.styl`** (which imports `_base/test/vars.styl`), I can **see my output** in CSS file!

And if I **change import lines order in `mobile/test/index.styl`** (putting `main` first and `vars` second), I also can **see my output** in CSS file!

```css
.test {
  color: #f00;
}
```

What is the trick? Why auxiliary import prevents my `.styl` file to output any CSS? Looks very weird.

**Comment by Panya** [comment]
I can't reproduce it with Stylus 0.53.0 (the latest version, CLI). Maybe you're using some flags or plugins?

**Comment by thybzi** [comment]
Whoa, completely right idea! Yes, I've checked the flags, and it ONLY reproduces with `--resolve-url`!

**Comment by thybzi** [comment]
I've changed the head post and issue title to mention `--resolve-url`

**Comment by Panya** [comment]
Yep, it's known issue, try to use `--resolve-url-nocheck` instead, it should work the same way but without this unexpected behavior.

**Comment by thybzi** [comment]
Is there any duplicate issue about that, which I should watch?
Or this `--resolve-url-nocheck` is not temporary but the final solution?

**Comment by Panya** [comment]
It will be the default behavior for `--resolve-url` in 1.0, so yep, it's final.

**Comment by thybzi** [comment]
Thank you for the help!
And I confirm that using `--resolve-url-nocheck` fixes my situation.
