### ISSUE TITLE
A shortcut for ^[-1..-1] in selectors?

### ISSUE THREAD

**Issue by thybzi** [stylus/stylus#2120]
It's sometimes very handy to mention current selector without parent context.
For example, if I want to set some margin to `<small>` when it goes next to `<strong>`.

But with current syntax of partial reference in selectors, it should look like:
```styl
small
  font-size: 12px
  line-height: 16px

  ../ strong + ^[-1..-1]
    margin-left: 8px
```

This selector line is quite consistent, but the syntax is just mind-blowing, isn't it?

Alternatives ways:
1. I can re-mention selector name `small` (but it can be much longer and more complicated, and — the main thing — it wouldn't change if rules selector changes)
2. I can write it outside the `small` rule, that would remove '../' also, but makes losing the logical context, and inevitable selector re-mention, again

Another situation:
```styl
.my-list

  .my-item
    some: styles
    go: here

    & + ^[-1..-1]
      some: other styles
```

So, may we have some shortcut for `^[-1..-1]`, such as `^`, or `$`, or `&&` or whatever?

**Comment by Panya** [comment]
Looks like a good case for a partial modifier from [the spec](https://github.com/stylus/stylus/issues/1240). Not yet implemented, but we have it in our plans.

**Comment by thybzi** [comment]
So, if I understood correctly, with partial modifier my last example will look like:
```styl
.my-list

  .my-item
    some: styles
    go: here

    & + ^^[-1]
      some: other styles
```

I mean to have it rendered to:
```css
.my-list .my-item {
  some: styles;
  go: here;
}

.my-list .my-item + .my-item {
  some: other styles;
}

```

Or did I misunderstand the idea of partial modifier?

**Comment by evenfrost** [comment]
:+1:  Would be super handy to eventually have partial modifier implemented.
