### ISSUE TITLE
OFFER: FIX URL: It's need for inline SVG

### ISSUE THREAD

**Issue by vruzin** [stylus/stylus#2122]
FILE:
stylus/lib/functions/url.js

May be:
```javascript
// Encode
return new nodes.Literal('url("data:' + mime + ';base64,' + buf.toString('base64') + hash + '")');
```

FIX TO:
```javascript
if(ext=="svg"){
  buf=';base64,' + buf.toString('base64');
}else{
  buf = ';charset=utf8,' + String(buf)
    .replace(/<\?xml(.+?)\?>/, '')
    .replace(/<!--.+?-->/g, '')
    .replace(/(<svg[^>]*?)\s+version=".*?"/, '<svg')
    .replace(/(<svg[^>]*?)\s+id=".*?"/, '<svg')
    .replace(/(<svg[^>]*?)\s+x=".*?"/g, '$1')
    .replace(/(<svg[^>]*?)\s+y=".*?"/g, '$1')
    .replace(/(<svg[^>]*?)\s+style=".*?"/g, '$1')
    .replace(/(<svg[^>]*?)\s+xml:space=".*?"/g, '$1')
    .replace(/(<svg[^>]*?)\s+xmlns=".*?"/g, '$1')
    .replace(/(<svg[^>]*?)\s+xmlns:xlink=".*?"/g, '$1')
    .replace(/(style=".*?);"/g, '$1"')
    .replace(/^\s+|\s+$/g, '')
    .replace(/>\s+</g, '><')
    .replace(/\s+/g, ' ')
    .replace(/(\r\n|\n|\r)/gm, '')
    .replace(/\"/g, "'")
    // .replace(/#|<|>|&/g, escape) // I think this line is not required
    ;
}
// Encode
return new nodes.Literal('url("data:' + mime + buf + hash + '")');
```

I think it's even easier....

I use this version of this file
https://github.com/stylus/stylus/blob/c2d07a0f117de6144105de8599f620c34713d251/lib/functions/url.js

**Comment by Panya** [comment]
We already added this feature via https://github.com/stylus/stylus/pull/2084. It will be in the next release (0.54.0).

**Comment by vruzin** [comment]
1. Yes, but your code without SVG optimization.
2. I think if you make the default encoding for each mime-type, it will be more userful
3. For SVG you can make options:

> - compress=0 - SVG as-is
> - compress=1 - SVG replace <?xml>, spaces
> - compress=2 - SVG replace <?xml>, spaces, <svg same attributes, style="...;" (DEFAULT)
> - escape = 0/1 - false/true

**Comment by Panya** [comment]
Optimization of SVG files is out of Stylus scope and should be done by other tools (e.g. SVGO).

**Comment by vruzin** [comment]
SVGO - very good tool ! ))) I agree with you )))
I just think if you make such a simple optimization is in stylus, it will be very convenient!
If the user needs to be the most powerful optimization SVG, then the user will use SVGO.

You decide what functions are endowed with stylus
