### ISSUE TITLE
Wrong errors logged when --include-css and --resolve-url used concurrently

### ISSUE THREAD

**Issue by cspotcode** [stylus/stylus#2125]
Here is a simple reproduction case, ready to fork and run: https://gist.github.com/cspotcode/19a42c629944f4e074d5

This bug occurs when:
1. One .styl file `@require`s another
2. The second .styl file has a syntax error
3. Both --include-css and --resolve-url are enabled (or the equivalent is done with the JavaScript API)

Instead of logging a normal error message, which is useful and shows exactly what's wrong:
> `unexpected "}"`

...it logs this error, which I'm pretty sure is a stylus bug and not an intentional error:

> `Cannot read property 'nodeName' of undefined`

**Comment by Panya** [comment]
Thanks for the report. I've fixed this bug in the `rc-0.54` branch. The fix will be in the next release.
