### ISSUE TITLE
[others] what's meaning of `stylus`?

### ISSUE THREAD

**Issue by XGHeaven** [stylus/stylus#2126]
I use `Stylus` long time ago.
A interesting question occured in my heart.

<strong>What's meaning of `Stylus`? </strong>

Such as `Vue`. It come from `view` in France pronunciation.

@tj

**Comment by Panya** [comment]
If google translate is correct it means 唱针 :)

**Comment by XGHeaven** [comment]
@Panya 唱针？ meaning?? Have a relationship with `CSS`?

**Comment by kizu** [comment]
I guess the name came just as a variation of a word `stylesheet` from the CSS, often used as just “styles”.
