### ISSUE TITLE
[Question] Can we load a stylus in the browser?

### ISSUE THREAD

**Issue by es6Test** [stylus/stylus#2129]
Can we load a stylus in the browser and run it as a css?

**Comment by Panya** [comment]
Yep, see https://gist.github.com/Panya/ba1886399d40bd6878d5 as example. Also you can build client-side version of Stylus from the repo, see my answer [on StackOverflow](http://stackoverflow.com/questions/35636849/build-stylus-from-the-git-repo) about it.
