### ISSUE TITLE
Question: how to compile stylus config to js object?

### ISSUE THREAD

**Issue by droganov** [stylus/stylus#2135]
Hi
I need to share a config between stylus and react. How can I pull stylus variables to js?

I know I can use json in stylus, it's static and it sucks, I want to reuse in js variables from stylus.

**Comment by cspotcode** [comment]
According to the contribution guide, this question should be asked on StackOverflow.

https://github.com/stylus/stylus/blob/dev/Contributing.md#asking-questions

**Comment by droganov** [comment]
http://stackoverflow.com/questions/35873359/how-to-compile-stylus-config-to-js-object
