### ISSUE TITLE
@import order and overriding hashes

### ISSUE THREAD

**Issue by badlydrawnrob** [stylus/stylus#2136]
I could be misunderstanding how Stylus `@imports` files, but coming from Less, and changing from global `@variables` to Stylus hashes, the import order is confusing me a lot.

For example, I have a [Codekit framework](https://incident57.com/codekit/help.html#codekit-frameworks) which contains the following hash in `./base/_typography`:

```stylus
$heading = {
  font: {
    family: $default-font-family-sans-serif,
  },
  text: {
    color: $default-color-black,
  }
}
```

So I assumed including the framework (a master file which includes all accompanying `@includes` with globbing `@import './base/_variables/*'`) would allow overriding hashes with dot notation:

```stylus
@import 'stylus/master'
@import './changes'
```

`changes.style` includes the following:

```stylus
$heading.text.color = red
```

But it doesn't affect the master framework. Another few examples of what works and what doesn't:

#### Works

```stylus
@import 'stylus/base/_mixins/*'
@import 'stylus/base/_variables/*' // original hash
@import './changes' // overriding hash
@import 'stylus/base/*'
```

#### Doesn't work

```stylus
@import 'stylus/base/_mixins/*'
@import 'stylus/base/_variables/*' // original hash
@import 'stylus/base/*'
@import './changes' // not overriding hash
```

#### Works

```stylus
@import 'stylus/base/_variables/_typography' // original hash
@import 'stylus/base/_variables/_buttons'
@import './changes'  // overriding hash
```

#### Doesn't work

```stylus
@import 'stylus/base/_variables/_typography' // original hash
@import 'stylus/base/_variables/_buttons'
@import 'stylus/base/*'
@import './changes'  // not overriding hash
```

#### Works

```stylus
@import 'stylus/base/_variables/_defaults'
@import 'stylus/base/_variables/_typography'
@import 'stylus/base/_variables/_base'
@import 'stylus/base/_variables/_colors'
@import 'stylus/base/_variables/_buttons'

$heading.text.color = red
$heading.font.family = Times New Roman
```

#### Doesn't work

```stylus
@import 'stylus/cardinal'

$heading.text.color = red
$heading.font.family = Times New Roman
```

### Wrap up

So my questions would be:

1. Why can't hashes be overriden everywhere, if this is not a bug?
2. Is there a definitive way to `@include` files to make overriding hashes work reliably?
    - I understand there are some documented issues with [relative urls](http://stylus-lang.com/docs/import.html#resolving-relative-urls-inside-imports) but it's definitely not obvious in the docs or the issues I've searched for why my particular tests would not be working. It all seems quite random. 
3. **Hashes in hashes**: Also, it seems it's best not to use hashes inside hashes, right? i.e. `$var = { foo: $bar.foo }`. If anything, having to worry about cascade order for this is a nightmare.

**Comment by badlydrawnrob** [comment]
I realise I might be being a bit dumb here, do hashes have to be overriden and compiled **before** they're used? Most of my Less projects add in the `@variables` after including the master framework.

**Comment by Panya** [comment]
I think you misunderstand how variables in Stylus and Sass working. In Less there's a concept of lazy variables (you can use a variable before defining it):
```less
.vars-at-bottom-work {
  foo: @var; // this would work.
}

@var: bar;
```

BUT in Stylus and Sass variables should be defined before they're being used. So the order of imports that defining variables and imports that changing them is important.

**Comment by Panya** [comment]
Basically, you need to import files which defining the hashes, then files which change the hashes and only after that files which use the hashes values.

**Comment by badlydrawnrob** [comment]
@Panya Ah, perfect. Thanks for explaining that to me :)
