### ISSUE TITLE
Feature request: Reversed @extend

### ISSUE THREAD

**Issue by B7th** [stylus/stylus#2138]
Hi! 

This is a feature request that I feel has been missing from all CSS preprocessor.

Simply put, it is a reversed @extend.

When the reversed @extend symbol (maybe an exclamation or a question mark) is appended to a selector, the program will look for the last previous occurence of the same selector and add the content to it rather than create a duplicated selector. If none exist, then it will output as usual.

Here is examples of usage.

```
global-reset()
html!
  box-sizing border-box
```

I do believe that this can drastically improve code rendering. It could probably even reduce @media redundancy without the need for intricate caching mixins.

Obviously, bad usage creates drawbacks, but that is the case for most new implementations.

What do you think?

**Comment by kizu** [comment]
There were some thoughts about something like this at #1296, not sure if and when we could get to this though. Closing this as a duplicate.
