### ISSUE TITLE
Bad npm publish? No index.js

### ISSUE THREAD

**Issue by Aaronius** [stylus/stylus#2143]
When I `npm install stylus@0.54.1` the installed package does not have an `index.js` (which is what `main` in `package.json` points to) and there are a lot of other files not typically in the package. If I `npm install stylus@0.54.0` it looks good. Looks like the last publish that went out a half hour ago is bad?

**Comment by gkoberger** [comment]
This took our entire site down when we pushed.

**Comment by Panya** [comment]
Yep, sorry for the inconvenience, published 0.54.2.
