### ISSUE TITLE
Variable + string interpolation or concatenation inside background-image url()

### ISSUE THREAD

**Issue by gusaiani** [stylus/stylus#2147]
Hi all,

thanks for Stylus. Love it.

I've been trying to do

```
image-base-url = 'http://domain.com/images/'
body
    background-image url({image-base-url + 'image.png'})
```

and variations of that, so I can interpolate or concatenate the url.

Is that possible? If so, how do I do it?

Many thanks.

**Comment by Panya** [comment]
Hi.
> Is that possible? If so, how do I do it?

Yep, everything inside the `url` call is an expression, so you can do:
```styl
image-base-url = 'http://domain.com/images/'
body
    background-image url(image-base-url + 'image.png')
```

You can also use [sprintf-like operator](http://stylus-lang.com/docs/operators.html#sprintf), or [s()](http://stylus-lang.com/docs/bifs.html#sfmt-) built-in function.

**Comment by gusaiani** [comment]
Thank you. Easier than I thought (and perhaps the documentation leads us to believe?).

**Comment by trusktr** [comment]
> Easier than I thought (and perhaps the documentation leads us to believe?).

I agree this is easier than docs lead us to believe. The [Interpolation](https://stylus-lang.com/docs/interpolation.html) page does no mention this sort of stuff.
