### ISSUE TITLE
Strange behaviour when using negative import glob

### ISSUE THREAD

**Issue by tremby** [stylus/stylus#2148]
I want to import files with a glob

```styl
@import 'components/*'
```

which works, but I need a particular one of those components to come first

```styl
@import 'components/main'
@import 'components/*'
```

and I don't want that `main.styl` component to be included twice

```styl
@import 'components/main'
@import 'components/!(main)'
```

This appeared to be working perfectly until I added a new component called `main-features.styl`. This file is not being included by the above statements. I'm guessing that the negative `!(main)` is excluding it since it starts with `main`, but this is, to me at least, unexpected.

Is this a bug, or am I doing something wrong?

**Comment by Panya** [comment]
Seems like a bug in `node-glob` version which we're using (`3.2.11`). I've updated it to the latest and the bug is disappeared.

**Comment by tremby** [comment]
Lovely! Thanks.

**Comment by kizu** [comment]
BTW, as a workaround could use `@require` instead of `@import` — it should import everything just once.

**Comment by tremby** [comment]
Yeah, `@require` does the trick. Thanks!
