### ISSUE TITLE
Can't access previous array index from within a loop

### ISSUE THREAD

**Issue by darsain** [stylus/stylus#2149]
This:

```
printargs()
	for val, i in arguments
		if i > 0
			{i}: arguments[i-1]


printargs(foo 5% bar)
```

Should not produce this:

```
1: ;
2: ;
```

Simply removing `-1` from index lookup makes it work properly (although it prints current, not previous index obviously).

**Comment by Panya** [comment]
`i-1` was parsed as an ident, you need spaces there:
```styl
printargs()
    for val, i in arguments
        if i > 0
            {i}: arguments[i - 1]
```

**Comment by darsain** [comment]
Ugh. Thx for the quick reply tho! :)
