### ISSUE TITLE
replace css-parse by css

### ISSUE THREAD

**Issue by alteholz** [stylus/stylus#2152]
As css-parse has been merged into css, would it be possible to use css instead of the css-parse dependency?

  Thorsten

**Comment by Panya** [comment]
We need only CSS parser for our CSS to Stylus conversion tool. `css` package provides parser and stringifier (which is useless in our case).

**Comment by alteholz** [comment]
But the current css-parse package already does only a "require('css').parse;"[1]. So you gain nothing by still using css-parse!?

[1]https://github.com/reworkcss/css-parse/blob/master/index.js

**Comment by Panya** [comment]
A version of `css-parse` which we're using doesn't use `css` package. It contains only the parser.
