### ISSUE TITLE
Add support for currentColor inside functions

### ISSUE THREAD

**Issue by jlmakes** [stylus/stylus#2153]
Excerpt from [MDN’s Color Value documentation](https://developer.mozilla.org/en/docs/Web/CSS/color_value#currentColor_keyword)

>"The currentColor keyword represents the calculated value of the element's color property. It allows to make the color properties inherited by properties or child's element properties that do not inherit it by default."

Below is an example of non-working Stylus code that would use `currentColor` for more flexible styles.

```stylus
a
    color: inherit
    text-decoration: underline
    cursor: pointer

    &:hover
        color: lighten(currentColor, 25%)
        text-decoration: none
```

However, this code throws  `TypeError: expected rgba or hsla, but got ident:currentColor`

**Comment by Panya** [comment]
The `currentColor` value will be defined only in the browser runtime (_calculated value of the element's color property_). We can't get the value at the moment when Stylus code compiles to CSS. So, it's impossible to do in preprocessors.

**Comment by jlmakes** [comment]
![my_dreams_shattered_they_are](https://cloud.githubusercontent.com/assets/2044842/14089881/8c54df8a-f537-11e5-8902-9e852ea3d775.gif)
