### ISSUE TITLE
Incredibly slow due to long loops

### ISSUE THREAD

**Issue by iammarkoradak** [stylus/stylus#2161]
It appears that long loops make compile time extremely slow, which I don't remember was the case earlier.

I've experienced it on the following structure:

- single stylus file with ~20 imports
- loops within import files:
  - 3 loops with 100 iterations
  - 4 loops with 20 iterations

=> ~64kb @ ~8sec

- same with loops mentioned above removed

=> ~34kb @ ~1.5sec

---

So, my question is - is it possible that loops could add to compile time so drastically, because it doesn't seem so realistic to me, to be honest, but results prove differently..?

Also, as already mentioned, I used to use long loops for quite some time, but haven't experienced any performance issues until recently. I don't recall which version of Stylus I was using until recently, but this was tested on latest - 0.54.2

**Comment by Panya** [comment]
Could you show a code example?
Anyway, loops and function calls always were a slow part of compilation because on each call/iteration we need to make a deep copy of the function/loop body. I haven't noticed any performance regressions in latest releases.

**Comment by Panya** [comment]
Could you also check it with previous versions?

**Comment by iammarkoradak** [comment]
Ok, after further investigating, I realized it was my own piece of code in combination with loops that was causing slow compile time.

I'm using my own library (something similar to nib which I plan on publishing, when ready) on personal projects, and one of the features is auto prefixing. Now, when you try to auto prefix a property that's within a loop iterating hundreds of times, I guess it's safe to say you can expect something like this to happen.

Just to be sure, I've checked it with a couple of previous versions (though only down to 0.52.0), but they all perform the same.

So it's my bad for not checking this earlier. Latest of those loops contains `transition-delay` property, which library was auto-prefixing - so I'll look into optimizing this on my end. Sorry for the trouble...

**Comment by Panya** [comment]
No problem. Btw I think autoprefixer is better suitable for the prefixing problem.

**Comment by iammarkoradak** [comment]
Yeah, I think I'll have to agree on that. So I'll probably add it as a dependency and use that instead.

Thanks!
