### ISSUE TITLE
Alternate Tint function

### ISSUE THREAD

**Issue by coreyworrell** [stylus/stylus#2163]
Right now the `tint` function **adjusts** ("relative" action) the tint based on the value you provide. `tint(black, 30%)` is saying tint the color black 30%. But it would be great to **set** ("absolute" action) the tint of a color as well: `tint(black, 70%)`. Both of these result in a 70% tint of black. But the latter makes it easy when working with color palettes and "syncing" your CSS to how your vector artwork is created.

I can easily create a mixin function to do this:

```stylus
// what to call it though?
set-tint(color, amount)
  tint(color, 100 - amount)
```

`set-tint` doesn't feel like the right thing to call it though. And as far as I can tell there is no way to override builtin functions (is this possible through a plugin?)

So I'm just wondering if this is something that could be in core or if I should continue to use a mixin?

**Comment by Panya** [comment]
> set-tint doesn't feel like the right thing to call it though. And as far as I can tell there is no way to override builtin functions (is this possible through a plugin?)

You can redefine a builtin function by saving its value to another variable. E.g.:
```styl
_tint = tint

tint(color, amount)
  _tint(color, 100 - amount)

body
  color: tint(#c00, 40%)
```

**Comment by coreyworrell** [comment]
Didn't think to ever try that :facepalm:

Thank you @Panya. I notice that aliases are documented, but I don't see any mention of this working with builtin functions in the documentation (unless I missed it)? Might be worth noting somewhere.
