### ISSUE TITLE
unexpected "}"  in media query

### ISSUE THREAD

**Issue by dominiklenne** [stylus/stylus#2164]
I tried the following code:

@media screen and (max-width: 550px) {
  #termine
    td        { display: block; width: 100%; }
}

It contains no tabs, no trailing spaces. the "td ..." is indented with 2 spaces.

Stylus crashes on this, but runs smoothly when i just write all in one line.

**Comment by Panya** [comment]
You can't mix indent and bracket nested blocks in a block. You can write:
```styl
@media screen and (max-width: 550px) {
  #termine {
    td { display: block; width: 100%; }
  }
}

body
  color: red
```

OR:
```styl
@media screen and (max-width: 550px)
  #termine
    td
      display: block; width: 100%

body {
  color: red
}
```

But you cannot write:
```styl
@media screen and (max-width: 550px) {
  #termine
    td
      display: block; width: 100%
}
```

**Comment by dominiklenne** [comment]
Thanks for the answer.
This mixed notation:
```stylus
#impressum
  nav                { background: #d4ecf6;    }
```
compiles perfectly to
```css
#impressum nav {
  background: #d4ecf6;
}
```
only within the media query, the way i chose to write them, it fails with the "unexpected '}' " - error.
So it seems that mixing is o.k. when curled brackets come last, while it fails, when they come first.
So i can write
```stylus
@media screen and (max-width: 550px) 
    #impressum
      nav                { background: #d4ecf6;       }
```
which is faster and clearer anyway! 
btw, is there a formal syntax definition of stylus?
