### ISSUE TITLE
Feature request: @at-root function

### ISSUE THREAD

**Issue by mike3run** [stylus/stylus#2165]
Could we get the function @at-root from sass I think its the only function missing here for stylus to truly kick sass ass on every single possible way.

Thanks

http://alwaystwisted.com/articles/2014-03-08-using-sass-33s-at-root-for-piece-of-mind

**Comment by Panya** [comment]
We have [root reference](http://stylus-lang.com/docs/selectors.html#root-reference) for simple cases (about 90% usage of `@at-root`). And for more complex cases we have a feature proposal (see #1296).
