### ISSUE TITLE
Extends within extends using placeholders not compiled

### ISSUE THREAD

**Issue by BenChirlin** [stylus/stylus#2167]
I'm using some extends within extends yet the nested rules within don't seem to get rendered. Not sure if this is intentional but seems broken. See example below:

```
$my-font = 'Helvetica'
$my-font-italic = 'Helvetica Italic'

$italic-rules
	font-family $my-font-italic
	font-style normal

$my-font-class
	font-family $my-font

	em
		@extends $italic-rules

.font-class
	@extends $my-font-class
```

Strangely, when I put this in a single file as above it seems to compile fine. However in my actual use case the font names are declared in one file, the font rules and classes in another, and the actual `.font-class` in yet another. This may be what is causing the issue.

When I switch `$italic-rules` to a mixin (i.e. `italic-rules()`) it then works fine so I'll do that for now.

**Comment by Panya** [comment]
I can't reproduce it with your example and Stylus 0.54.2. I've tested it with this setup:
`fonts.styl`
```styl
$my-font = 'Helvetica'
$my-font-italic = 'Helvetica Italic'
```

`font-rules.styl`
```styl
$italic-rules
    font-family $my-font-italic
    font-style normal

$my-font-class
    font-family $my-font

    em
      @extends $italic-rules
```

`common.styl`
```styl
.font-class
  @extends $my-font-class
```

and `style.styl`
```styl
@import 'fonts'
@import 'font-rules'
@import 'common'
```

And after compiling (`stylus style.styl`) it yields to:
```css
.font-class em {
  font-family: 'Helvetica Italic';
  font-style: normal;
}
.font-class {
  font-family: 'Helvetica';
}
```
Seems all is fine.

**Comment by BenChirlin** [comment]
Never mind. Tracked this down to a dependency issue in my Gulp. My bad!
