### ISSUE TITLE
css-modules?

### ISSUE THREAD

**Issue by aft-luke** [stylus/stylus#2170]
After digging around the issues here I was unable to find any mentions to the following; please disregard if this issue has already been raised.

~~Is there any plan to support [css-modules](https://github.com/css-modules/css-modules) via stylus? While using stylus might seem counter to css modules, what with the whole nesting, `&` operators, `mixins()` and the like... the idea of "totally isolated modules" is a big one. That being said, writing plain css after using stylus's awesome stripped-down DSL is just painful.~~

~~For stylus to interop with css modules, it would only need to support a handful of css-modules-specific keywords (`:global`, `:composes`, etc). My particular use case would be `stylus -> css-modules syntax -> css-js modules -> clojurescript namespaces`, but any chain involving stylus and css-modules could work if we found a way to support those keywords.~~

I suppose disregard the above. After playing around for a bit I discovered that stylus already appears to support this syntax (i.e. do nothing to clobber it). I'll leave this issue here so others in the future might benefit.

```
:global
    .base
        background-color blue

.extends
    composes: base
    border 1px solid green

-->

:global .base {
  background-color: #00f;
}
.extends {
  composes: base;
  border: 1px solid #008000;
}
```

**Comment by Panya** [comment]
Yep, it already supported.
