### ISSUE TITLE
Unable to lint files pre-processed by stylus

### ISSUE THREAD

**Issue by doberkofler** [stylus/stylus#2171]
I very much love stylus but I creates some problems when using in conjunction with stylelint. I for example do not understand why the following stylus file:
```
$myclass = '.myClass';
{$myclass} {
   box-shadow: 0 5 10 rgba(0, 0, 0, 0.25);
}
```

is converted to:
```
.myClass {
  box-shadow: 0 5 10 rgba(0,0,0,0.25);
}
```

and no longer has the black after each argument in the rgba function?

**Comment by Panya** [comment]
You mean it looses spaces after the commas? Stylus never tried to preserve the original CSS format as it was written in the source, because Stylus doesn't save meaningless tokens while parsing the source file. Sorry, but it won't be fixed in the near future.
