### ISSUE TITLE
cannot mix and match curly braces and indentation

### ISSUE THREAD

**Issue by sundarj** [stylus/stylus#2172]
If you try this:

```css
h1 {
  color red

  p
    color blue
}
```

it doesn't compile. I like curly braces for the root selectors as it helps you distinguish between them, but with child selectors it's not as important, so it'd be nice to be able to mix and match the two styles.

**Comment by Panya** [comment]
Sorry, but it would make parsing very hard. And we would not be able to write things like:
```styl
body {
  color red
    background: blue
  cursor default
}
```
(which is possible now)
