### ISSUE TITLE
LESS-like variable scope usage

### ISSUE THREAD

**Issue by thybzi** [stylus/stylus#2174]
Yet another "make this work like in LESS" feature request.

In LESS, I can use variables defined below, but available in the current scope.
That may be strange practice for programming languages, but enables cool things when defining some logical blocks of constants.

That means, in LESS I can easily write the following code, and everything is calculated fine.

``` less
@container-width: 980px;
@container-height: max(@leftcol-height, @rightcol-height);
@cols-gap: 25px;

@leftcol-width: @container-width - @rightcol-width - @cols-gap;
@leftcol-height: /* some complicated calculations here */;

@rightcol-width: 300px;
@rightcol-height: @leftcol-width * 1.5; // why not?
```

In Stylus, that wouldn't work, and I'm coerced to write everything in a very unreadable order:

``` styl
$container-width = 980px
$cols-gap = 25px

$rightcol-width = 300px

$leftcol-width = $container-width - $rightcol-width - $cols-gap
$leftcol-height = /* some complicated calculations here */

$rightcol-height = $leftcol-width * 1.5  // why not?

$container-height = max($leftcol-height, $rightcol-height)
```

Of course, real things are even more complicated and thus unreadable in Stylus than this abstract example.

Is there any chance to do that in Stylus in a more elegant way?

**Comment by Shyam-Chen** [comment]
```styl
$container-width = 980px
// ...
```

**Comment by thybzi** [comment]
@Shyam-Chen sorry? Didn't understand you position clearly

**Comment by FezVrasta** [comment]
I think he refers to your Stylus example, you have declared variables with `$var: 10px` instead of `$var = 10px` (note the equal)

**Comment by thybzi** [comment]
Oh, of course, it's copy-paste error
Corrected the example

**Comment by thybzi** [comment]
@FezVrasta @Shyam-Chen  
Oh, of course, it was a copy-paste error. Corrected the example, the idea is still the same

**Comment by kizu** [comment]
I don't think we would ever support this style of variable usage as it would be far from easy to implement and would surely break the backwards compatibility. If someone would like to try it — PR is welcome, but not guaranteed to be merged (at least until the closest major release).
