### ISSUE TITLE
Chaos in data types

### ISSUE THREAD

**Issue by thybzi** [stylus/stylus#2175]
I’ll just leave this here (things I dislike the most are: no data type for lists, and no difference between plain numbers and numbers with units):
```styl
/*! bool, null */
typeof()                          // -> "null"
typeof(null)                      // -> "null"
typeof(undefined)                 // -> "ident"
typeof(false)                     // -> "boolean"
typeof(no)                        // -> "ident"

/*! color */
typeof(#ff0000)                   // -> "rgba"
typeof(#f00)                      // -> "rgba"
typeof(red)                       // -> "rgba"
typeof(rgba(255, 0, 0, 0.5))      // -> "rgba"
typeof(hsla(0, 100%, 50%, 0.5))   // -> "hsla"
typeof(hsl(0, 100%, 50%))         // -> "hsla"
typeof(invert(red))               // -> "rgba"
typeof(invert(hsl(0, 100%, 50%))) // -> "rgba"

/*! ident, string, unit, call */
typeof(foobar)                    // -> "ident"
typeof('foobar')                  // -> "string"
typeof(15)                        // -> "unit"
typeof(15px)                      // -> "unit"
typeof(15deg)                     // -> "unit"
typeof(rotate(15deg))             // -> "call"
typeof(url('http://example.com')) // -> "call"

/*! function, mixin o_O, property */
foobar($a, $b)
  $a + $b
typeof(foobar)                    // -> "function"
typeof(foobar(1, 2))              // -> "unit"
foobar($a, $b)
  {$a}: $b
typeof(foobar)                    // -> "function"
typeof(foobar(1, 2))              // -> "property"

/*! object, list o_O */
typeof({ a: 42 })                 // -> "object"
typeof({ a: 42 }.a)               // -> "unit"
typeof(a, 42)                     // -> "ident"
typeof(42, a)                     // -> "unit"

/*! list variables */
a = 1px solid red
typeof(a)                         // -> "unit"
typeof(a, 42)                     // -> "unit"
b = italic 15px serif
typeof(b)                         // -> "ident"
c = (1 2 3)
typeof(c)                         // -> "unit"
typeof(a, b, c)                   // -> "unit"
typeof(b, a, c)                   // -> "ident"
typeof(c, b, a)                   // -> "unit"
b = c
typeof(b, a, c)                   // -> "unit"
b = rotate(45deg) scaleX(2)
typeof(b)                         // -> "call"
typeof(c)                         // -> "unit"
c = a, 42
typeof(c)                         // -> "unit"
```
https://gist.github.com/thybzi/520e993f22ffd0dc6c6c
http://codepen.io/thybzi/pen/MKMGoK

**Comment by vendethiel** [comment]
except for the "list variables" part, I don't see what's surprising...

**Comment by Panya** [comment]
TBH it all seems fine to me (except lists/objects, see #1333). 

In Stylus there is no such thing as `undefined` or `no`, so:
```styl
typeof(undefined)    // -> ident
typeof(no)           // -> ident
```
is correct output (undeclared variable is just an ident, otherwise Stylus would break on things like `border-style: solid`).
```styl
foobar($a, $b)
  {$a}: $b
typeof(foobar)                    // -> "function"
typeof(foobar(1, 2))              // -> "property"
```
It is also correct (function call returning a property).

> no difference between plain numbers and numbers with units

Same as in Sass/Less

**Comment by thybzi** [comment]
>> no difference between plain numbers and numbers with units
> Same as in Sass/Less
Yes, you're right. I was thinking about `isnumber` and `isunit`, but that's about another things.

For me, `rgba` type name (matching all but `hsla()` and `hsl()`) seems very confusing. Looks like some hack for internal use, am I right? 
If so, I thing it would be better to introduce `rgb` type matching all opaque color values (leaving `rgba` only for real `rgba()` values). 
So `rgb`, `rgba` and `hsla` altogether will match `color`. Isn't it good idea?

And, I believe, `list` type is needed. Didn't understood clearly, should that be done in #1333 or not.

**Comment by Panya** [comment]
> So rgb, rgba and hsla altogether will match color. Isn't it good idea?

Yep, I think we will change it to `color` in 1.0

> And, I believe, list type is needed.

Sure, it will be added in 1.0
