### ISSUE TITLE
simple @font-face does nothing...

### ISSUE THREAD

**Issue by cjaoude** [stylus/stylus#2177]
this does bubkus, i'm not seeing a reason why. only @import works, but only in the main.style file. @import doesn't work in a partial.

```
@font-face
  font-family Pacifico
  font-style normal
  src url(https://fonts.googleapis.com/css?family=Open+Sans)
```

**Comment by Panya** [comment]
I can't reproduce it with Stylus 0.54.5 (latest). See http://stylus-lang.com/try.html#?code=%40font-face%0A%20%20font-family%20Pacifico%0A%20%20font-style%20normal%0A%20%20src%20url(https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DOpen%2BSans)
