### ISSUE TITLE
[Question] how to import from other directories

### ISSUE THREAD

**Issue by rogervila** [stylus/stylus#2185]
Hello,
Given that directory structure:
```
a/first.styl
b/second.styl
```
How can I import `first.styl` into `second.styl`? 
I have tried with `@import ../first.styl` but it outputs this as a literal css.
Thank you!

**Comment by Panya** [comment]
```styl
@import '../a/first.styl'
```

**Comment by rogervila** [comment]
But when I add it, it puts  `@import '../a/first.styl'` into the compiled css instead of importing the assets

**Comment by Panya** [comment]
I'm 100% sure that it works (I've tested it with CLI, Stylus 0.54.5)

**Comment by Panya** [comment]
Could you share a more specific test case that fails?
