### ISSUE TITLE
Webstorm Setting and compile error.

### ISSUE THREAD

**Issue by leeeco610** [stylus/stylus#2187]
I use stylus in webstorm 11.
**Find the error:   [90mcompiled[0m** 
Webstorm 11 setting like that:
File --> Settings --> Tools --> File Watchers --> Add
------------------------------------------------------------------
Name:Stylus
File type: Stylus
Scope: Project Files
Program: C:\Program Files\nodejs\node.exe
Arguments: C:\Users\Administrator\AppData\Roaming\npm\node_modules\stylus\bin\stylus       $FilePath$
Working directory:$FileDir$
Environment variables: 
Output paths to refresh:$FileParentDir$/$FileNameWithoutExtension$.css

[Setting image](http://o7msdws2v.bkt.clouddn.com/error_stylus.png)
![error_stylus](https://cloud.githubusercontent.com/assets/18615161/15472191/70c8a906-212c-11e6-9c20-f80864c790fc.png)

**Comment by Panya** [comment]
Please file this issue in WebStorm issue tracker (https://youtrack.jetbrains.com/issues/WEB).

**Comment by leeeco610** [comment]
But I use less in WebStorm.
And the same setting.
There is no error in.

**Comment by Panya** [comment]
Why do you think that it's a Stylus problem? Are you tried to compile the file through CLI or gulp/grun?

**Comment by Lmster** [comment]
deselect "Create output file from stdout"
![7](https://cloud.githubusercontent.com/assets/22146307/18431196/fc7a8ec0-78ec-11e6-9264-4fd909d53f8b.jpg)
