### ISSUE TITLE
stylus.nodes.Literal asks for path?

### ISSUE THREAD

**Issue by FezVrasta** [stylus/stylus#2190]
When I try to define a variable with:

```js
style.define(
  'accent',
  new stylus.nodes.Literal('red')
);
```

I get

    Path must be a string. Received undefined

I have tried with `Ident`, with it I can use the variables in my Stylus sheets, but when I try to use them inside a color function I get

    Cannot read property 'r' of undefined

I'm not using `Color` because I'm importing variables automatically from a JS file and I don't know the type.
What am I doing wrong?

**Comment by Panya** [comment]
I guess you're using Node >= 6 and outdated version of Stylus (< 0.54.3). Anyway you won't get the color node with this approach and it won't work with color functions. You should use [`convert()`](http://stylus-lang.com/docs/bifs.html#convertstr) or [`json()`](http://stylus-lang.com/docs/bifs.html#jsonpath-options) in this case.

**Comment by FezVrasta** [comment]
I'm on Stylus 0.54.5 and Node 6.

May you give me an hint to use `convert` in JS? Thanks!

**Comment by Panya** [comment]
You need to use `convert` inside Stylus file and define JS variables as strings.

**Comment by FezVrasta** [comment]
No other ways? It's annoying to have to use `convert` everytime I want to use a variable..

**Comment by Panya** [comment]
Another way is `json()` :)

**Comment by Panya** [comment]
Also you can try to use https://github.com/pressly/stylus-coerce from #1448

**Comment by FezVrasta** [comment]
Thanks, I'll give `json` a try.
