### ISSUE TITLE
Difference between multi-line $placeholders and @blocks? 

### ISSUE THREAD

**Issue by kevinSuttle** [stylus/stylus#2193]
Using the [following example](http://stylus-lang.com/try.html#?code=squee%20%3D%20%40block%20%7B%0A%20%20width%3A%2020px%0A%20%20height%3A%2020px%0A%7D%0A%0A%24foo%0A%20%20color%3A%20%23FFF%0A%20%20font-size%3A%201px%0A%0A.baz%0A%20%20%40extends%20%24foo%0A%0A.dee%20%0A%20%20%7Bsquee%7D%0A%0A.womp%20%0A%20%20%7Bsquee%7D%0A%20%20%40extends%20%24foo), notice that the `.womp` and `.dee` styles aren't grouped. 

I'm just wondering what the differences are between the two approaches.

**Comment by Panya** [comment]
> Using the following example, notice that the .womp and .dee styles aren't grouped.

They shouldn't. Basically, `@block` is a mixin without arguments that could be stored in a variable (or a hash value) and used in any place where a normal variable can be used.
