### ISSUE TITLE
space separated values interpreted as list...

### ISSUE THREAD

**Issue by FezVrasta** [stylus/stylus#2195]
I'm trying to write a function that takes a comma separated list of box-shadows and converts them to `filter: drop-shadow`.

I'm having a problem, if I pass a single shadow to my function, Stylus interprets it as an array instead of a string, and then it get parsed by the `for` loop.

```
drop-shadow($array...)
  $dropShadows = ()

  for $shadow in $array
    push($dropShadows, 'drop-shadow(' + $shadow + ')');

  filter: unquote(join(' ', $dropShadows))

drop-shadow: 0 0
```

$array is of type `unit`, but the result is:

```
filter: drop-shadow(0) drop-shadow(0)
```

Why?

**Comment by vendethiel** [comment]
arrays are a bit of :( in Stylus still...

**Comment by FezVrasta** [comment]
Are you aware of any workaround to get the result?

**Comment by vendethiel** [comment]
see #1440

**Comment by FezVrasta** [comment]
For now I've found this workaround:

```
drop-shadow($array...)
  dropShadow($array...)
    $dropShadows = ()

    for $shadow in ($array)
      push($dropShadows, 'drop-shadow(' + $shadow + ')');

    pop($dropShadows)

    filter: unquote(join(' ', $dropShadows))

  dropShadow($array, 0)
```

In pratice, you call `drop-shadow`, it calls `dropShadow` adding a dummy element to the list of passed arguments.
Doing so, we are sure that our `dropShadow` function always gets a "real" array.
Then, before we return the result, we `pop` the last item (the fake one).

**Comment by vendethiel** [comment]
That's a fine way. I believe you could also check if the first element of `$array` (... which might want to be `$list`?) is a list itself.

**Comment by FezVrasta** [comment]
I need to accept as list only comma separated values (this is why I'm using the rest params instead of `arguments`). I think that this kind of check would return true even if the argument is just one (`0 0`)

**Comment by vendethiel** [comment]
The problem is that your "workaround" is broken for more-than-one-element lists (since you don't splat-call `_drop-shadow`, the 1st argument is always the `$array`).

**Comment by FezVrasta** [comment]
oh right.. it's getting tricky..

**Comment by Panya** [comment]
Actually  `0 0` is a list from the Stylus perspective. If I understand your problem correctly, you can use `list-separator` bif to check if the given list is separated by comma:
```styl
drop-shadow()
  if list-separator(arguments) == ','
    $dropShadows = ()
    for $shadow in arguments
      push($dropShadows, 'drop-shadow(' + $shadow + ')');
    filter: unquote(join(' ', $dropShadows))
  else
    filter: arguments
```

**Comment by FezVrasta** [comment]
Oh awesome thanks! 

The else part should be tho:

    filter: unquote('drop-shadow' + arguments + '')

**Comment by FezVrasta** [comment]
Oh, wait.

It doesn't work if you pass to `drop-shadow` a variable...

**Comment by Panya** [comment]
Hmm, [this example](http://stylus-lang.com/try.html#?code=drop-shadow()%0A%20%20if%20list-separator(arguments)%20%3D%3D%20'%2C'%0A%20%20%20%20%24dropShadows%20%3D%20()%0A%20%20%20%20for%20%24shadow%20in%20arguments%0A%20%20%20%20%20%20push(%24dropShadows%2C%20'drop-shadow('%20%2B%20%24shadow%20%2B%20')')%3B%0A%20%20%20%20filter%3A%20unquote(join('%20'%2C%20%24dropShadows))%0A%20%20else%0A%20%20%20%20filter%3A%20arguments%0A%0Alist%20%3D%200%2C%200%0Alist2%20%3D%200%200%0Abody%0A%20%20drop-shadow%3A%20list%0A%20%20drop-shadow%3A%20list2) works for me.

**Comment by Panya** [comment]
I guess, you can leave just `drop-shadow: arguments` for the else branch.

**Comment by FezVrasta** [comment]
I'm using a variable imported with `json`, and it doesn't work. It returns `filter: drop-shadow;` when I do: `drop-shadow: $SHADOW-Z1`

```json
{
  "$SHADOW": {
    "Z1": "0 01px 03px rgba(0,0,0,0.12), 0 01px 02px rgba(0, 0, 0, 0.24)",
    "Z2": "0 03px 06px rgba(0,0,0,0.16), 0 03px 06px rgba(0, 0, 0, 0.23)",
    "Z3": "0 10px 20px rgba(0,0,0,0.19), 0 06px 06px rgba(0, 0, 0, 0.23)",
    "Z4": "0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0, 0, 0, 0.22)",
    "Z5": "0 19px 38px rgba(0,0,0,0.30), 0 15px 12px rgba(0, 0, 0, 0.22)"
  }
}
```

**Comment by Panya** [comment]
Cannot reproduce with Stylus 0.54.5 (CLI).

```styl
json('shadows.json')

drop-shadow()
  if list-separator(arguments) == ','
    $dropShadows = ()
    for $shadow in arguments
      push($dropShadows, 'drop-shadow(' + $shadow + ')');
    filter: unquote(join(' ', $dropShadows))
  else
    drop-shadow: arguments

body
  drop-shadow: $SHADOW-Z1
```

Compiles to:
```css
body {
  drop-shadow: 0 01px 03px rgba(0,0,0,0.12), 0 01px 02px rgba(0, 0, 0, 0.24);
}
```

**Comment by FezVrasta** [comment]
No idea, it works if I do `drop-shadow: shadow = $SHADOW-Z1`...

I'm using `stylus-loader` with webpack tho.

**Comment by FezVrasta** [comment]
@Panya I've tried with the CLI 0.54.5 and it doesn't work neither there.

```body {
  background-color: #fcf8e3;
  border-radius: 2px;
  drop-shadow: 0 01px 03px rgba(0,0,0,0.12), 0 01px 02px rgba(0, 0, 0, 0.24);
  padding: 0.2em 0.5em;
}```

this is the result of your last example.

**Comment by FezVrasta** [comment]
Opened a dedicated bug for it https://github.com/stylus/stylus/issues/2196
