### ISSUE TITLE
Interpolation in string

### ISSUE THREAD

**Issue by vontio** [stylus/stylus#2201]
how to translate this less syntax to stylus:

`<path fill='#@{colorHex}'`

**Comment by vendethiel** [comment]
That doesn't look like LESS.

**Comment by vontio** [comment]
hi
just a snippet of.
`i.icon-next.color-@{colorName}, i.icon-next.theme-@{colorName}, .theme-@{colorName} i.icon-next {
        .encoded-svg-background("<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 15 15'><g><path fill='#@{colorHex}' d='M1,1.6l11.8,5.8L1,13.4V1.6 M0,0v15l15-7.6L0,0L0,0z'/></g></svg>");
    }`

**Comment by Panya** [comment]
You can use concatenation:
```stylus
$colorHex = red

.body
  background: encoded-svg-background('<svg fill="' + $colorHex + '">')
```

**Comment by vendethiel** [comment]
also see #728

**Comment by vontio** [comment]
Thanks @Panya  @vendethiel 
+1 for #{}
