### ISSUE TITLE
Problem in built-in functions with another built-in function

### ISSUE THREAD

**Issue by andersonaguiar** [stylus/stylus#2206]
I have this example:

background rgba(green(#f0f), 0.5)

The same problem happens if I put a variable in the place of built-in function.

This generate the error:

48| background rgba(green(#f0f), 0.5)
---------------------------------------------^

TypeError: expected rgba or hsla, but got unit:0

Any idea?

**Comment by Panya** [comment]
`green` bif returns green's channel value of the given color (it is a number from 0 to 255, 0 in our case). But `rgba` accepts a color as a first argument. I think the error message is pretty clear. What do you expect from this expression?

**Comment by andersonaguiar** [comment]
If I put #f0f inside a variable, the same error persist. But if I put #f0f directly, this works.

**Comment by Panya** [comment]
It shouldn't work, because this expression is invalid. See example with a variable at http://codepen.io/anon/pen/JKyGxR

**Comment by Panya** [comment]
Can you show an example that works?

**Comment by andersonaguiar** [comment]
$color = #f0f
body
  background: rgba($color, 0.5)

This works in codepen but not in my local. Maybe stylus version?

**Comment by Panya** [comment]
Yep, try to update Stylus, also make sure that you're defining (|| importing) the variables before using them.

**Comment by andersonaguiar** [comment]
I have that structure:

main.styl -> with variables and after the import of a component child
componentchild.styl -> see the variables defined in main but on rgba function the variable is not visible

If I define the variable on the componentchild.styl this works.

Have that limitation in imported variables in rgba function?

**Comment by Panya** [comment]
> Have that limitation in imported variables in rgba function?

Nope, I can't reproduce it with Stylus 0.54.5 (CLI or JS API) and the same structure.

`main.styl`:
```styl
$color = #f0f

@import 'child'
```

`child.styl`:
```styl
body
  background: rgba($color, 0.5)
```

Compiles to (main.css):
```css
body {
  background: rgba(255,0,255,0.5);
}
```

**Comment by andersonaguiar** [comment]
I have an variables.styl also, this works for you too?

**Comment by Panya** [comment]
Yep.

**Comment by Panya** [comment]
The same way (through JS API):
`main.js`:
```js
var stylus = require('stylus');
var fs = require('fs');

stylus(fs.readFileSync('main.styl', 'utf-8'))
  .set('filename', 'main.styl')
  .render(function(err, css) {
    if (err) throw err;
    console.log(css);
});
```

`main.styl`:
```styl
@import 'variables'
@import 'child'
```

`variables.styl`:
```styl
$color = #f0f
```

`child.styl`:
```styl
body
  background: rgba($color, 0.5)
```

Compiles (`node main.js`) to the same output.

**Comment by andersonaguiar** [comment]
For me doesn't work 😞 

![](http://i.imgur.com/3FHVi07.png)

I'm using gulp-stylus.

**Comment by Panya** [comment]
Well, the only thing I can suggest in this case — prepare a minimal test case to reproduce the problem and open an issue in gulp-stylus repo.

**Comment by andersonaguiar** [comment]
I did that...

https://github.com/stevelacy/gulp-stylus/issues/179

**Comment by Panya** [comment]
> prepare a minimal test case to reproduce the problem 

you didn't do this. The example that you've posted is invalid (and misleading, because the problem is about imports and variables).

**Comment by andersonaguiar** [comment]
Sure, I will do that, thanks for the help.

**Comment by andersonaguiar** [comment]
I guess this is a limitation of Stylus.

I have: 

`main.styl`

```stylus
@import 'helpers/variables'
@import 'pages/home'
```

`home.styl`

```stylus
@import '../components/header-content-right'
```

`header-content-right.styl`

```stylus
.element
  background rgba($color-dark, 0.5)
```

The variable in header-content-right.styl is not compiled.

**Comment by andersonaguiar** [comment]
But if I do: 

```stylus
background $color-dark
```

This works, I don't know if that problem is in stylus.

😕

**Comment by Panya** [comment]
> I guess this is a limitation of Stylus.

It's really easy to check. Install latest version of Stylus with this command:
```
npm install stylus -g
```

Then try to compile `main.styl` from your example:
```
stylus main.styl
```

It should compile the file to `main.css`. I've checked it, my output of the compilation is:
```css
.element {
  background: rgba(0,255,0,0.5);
}
```

**Comment by Panya** [comment]
I've also checked it with JS API, same result...

**Comment by Panya** [comment]
I created a small example project with gulp-stylus ([gulp-test.zip](https://github.com/stylus/stylus/files/352837/gulp-test.zip)). Unzip it, run `npm install` inside the unzipped dir, and `gulp stylus` after that. The result of compilation will be in `build` directory. And again, no error...

**Comment by andersonaguiar** [comment]
Yes, I found the problem...

When I use via glob:

```javascript
gulp.task('stylus', () => {
  gulp.src(config.path.src + '/assets/stylus/**/*.styl')
```

The problem happens. But if I use:

```javascript
gulp.task('stylus', () => {
  gulp.src(config.path.src + '/assets/stylus/main.styl')
```

This works. So, I can't use glob in this case?

**Comment by Panya** [comment]
> This works. So, I can't use glob in this case?
Yep, the problem is: If you're using the glob pattern gulp will compile each `.styl` file in the src directory one by one and eventually will try to compile `components/header-content-right.styl` (which contains rgba($color-dark, 0.5), but without the `variables.styl` import `$color-dark` will be undefined).

**Comment by andersonaguiar** [comment]
Of course, thanks for the help!
