### ISSUE TITLE
Cant acces to functions from a conditional @import

### ISSUE THREAD

**Issue by JustPepper** [stylus/stylus#2211]
Hey guys im trying to make something like an autoload.

![1](https://cloud.githubusercontent.com/assets/7258205/16969198/c8f0e8c2-4dd8-11e6-9635-b4ddd46ade65.jpg)

```stylus
dependencies( list, path = "components" )
    if list
        for num in range(0,(length(list) - 1))
            route_path = "/" + path + "/" + list[num]
            @import route_path + "/*"


dependencies( bar )

bar()
```

And here is my file inside bar folder.

```stylus
bar()
    .baz
        color red

.bar
    color red
```
But i cant access to this function inside the file, here is the css final file.

```css
.bar {
  color: #f00;
}
```

is there something wrong with my code?

**Comment by Panya** [comment]
This import has evaluated in the function scope (Stylus has lexical scoping), so all variables are inaccessible outside the function body. You can try to use `define` bif and anonymous functions to define global variables and mixins inside the import.
