### ISSUE TITLE
@import only import necessary classes

### ISSUE THREAD

**Issue by rahbari** [stylus/stylus#2214]
I want to add a new style file to a web application using JS, which import and use some classes in a common.styl file which is already imported by the main style of the web application. So it would be nice if the @require could only import neccessary classes like those which are only extended in the current styl file.

**Comment by bkjohnson** [comment]
I realize this is a late response, but here's a potential workaround:

**imported.styl**
```
nav()
  .nav
    color: black
    float: left
    font-size: 14px

sidebar()
  .sidebar
    float: right
    font-size: 20px
    height: 600px
```

**main.styl**
```
@require "imported.styl"

// Inject individual classes from the imported file
nav()

.container
  text-align: center
  padding: 12px
```

This "injection" pattern would allow you to have a separate file filled with classes nested inside mixins, and by only using certain mixins you can control what is in the output.
