### ISSUE TITLE
Variables in Comments

### ISSUE THREAD

**Issue by juicyarts** [stylus/stylus#2217]
Hey there.
I just ran into something while getting http://warpspire.com/kss/ to work with a framework im building.

It would be great if you could Include variables into comments like you can do in sass:
http://sass-lang.com/documentation/file.SASS_REFERENCE.html#comments

So Kss can use those for the Styleguide generation and i can just pass the variables instead of putting static content into the comments.

in:

``` stylus
$var = #fff
// Colors
//
// somefancyvars {$var} $var
//
```

out:
`somefancyvars  {$var} $var`

is there a way to do this?

thanks,
hü

**Comment by bkjohnson** [comment]
Have you tried using a multi-line comment with `!` in it?  For example:

```
/*!
 * somefancyvars {$var} $var
 */
```

Documentation [here](http://stylus-lang.com/docs/comments.html#multi-line-buffered)

**Comment by juicyarts** [comment]
That also just outputs given comment 'as is' rather then the variable value i want.
This also seems to be a general issue with [KSS](https://github.com/kss-node/kss-node/issues/50).
So i think there is no chance to do this without duplicating the variable values in the comment.

Thanks for the reply anyway!

**Comment by kizu** [comment]
BTW, you can always write a custom function to return a CSS comment that would be formatted as you like, for example:

``` Stylus
// Definition
comment($string)
  unquote('/*! ' + replace('(?![\t ])\s\s*', '\n * ', $string) + '\n */')

// Usage
$var = #FFF
comment('Colors \
         \
         somefancyvars %s $var' % $var)

```

Would produce this:

``` CSS
/*! Colors 
 * somefancyvars #fff $var
 */
```

But yeah, I guess we need interpolation in comments, but that's probably a task for a future 1.0.0.

**Comment by juicyarts** [comment]
Thanks for the advice. Im going to try this when i have time for to the project.
