### ISSUE TITLE
How to output rgb(n,n,n) ? 

### ISSUE THREAD

**Issue by phun-ky** [stylus/stylus#2219]
I am struggling to get this to work as expected:

    $color-black = rgb(0,0,0) // #000000
    $color-white = rgb(255,255,255) // #FFFFFF
    $color-red = rgb(201,37,49); // #c92531

    $colors = primary-red $color-red, primary-white $color-white, primary-black $color-black;

    generatestuff($c)
      for $pair in $c
       .color-{$pair[0]}
          color: rgb($pair[1])
    generatestuff($colors)

The output is:

    .color-primary-red {
      color: #c92531;
    }
    .color-primary-white {
      color: #fff;
    }
    .color-primary-black {
      color: #000;
    }

What I expect/wants/desire...

    .color-primary-red {
      color: rgb(201,37,49);
    }
    .color-primary-white {
      color: rgb(255,255,255);
    }
    .color-primary-black {
      color: rgb(0,0,0);
    }

How can I achieve this if this is not intended behaviour?

**Comment by Panya** [comment]
This is intended behaviour. The only way you can achieve this is by saving `r, g, b` values as lists and use `unquote('rgba(' + join(',', $color) + ')')`:

```styl
$color = 0, 0, 0

body
  color: unquote('rgba(' + join(',', $color) + ')')
```

**Comment by phun-ky** [comment]
Is this by design? If so, why? IMHO, the output of rgb, should be rgb(n,n,n), not hex. For me, it seems very confusing. 

For my scenario right now, I found that I do not require this, but my point is still valid. Thanks for all the good work, keep it up!

**Comment by srsgores** [comment]
I've had a think about this, and I think, for now, we can use the [`rgba` function](https://stylus-lang.com/docs/bifs.html#rgbacolor--rgba) as intended to better indicate the colour anyway (IMO, it does make the code a bit more readable at the expense of deviating from the CSS spec):

```stylus
$themePrimaryColour ?= #651010

:root
	--header-background-colour rgba($themePrimaryColour, 0.25)
```

**Comment by phun-ky** [comment]
@srsgores  yeah, rgb is more readable than hex (hex is more readable IMHO than hsl)

And what puzzles me is that stylint for example, warns that "hex" should be rgb or a variable.

**Comment by phun-ky** [comment]
@Panya  @srsgores Sorry for bringing up an old issue, encountered the use case again today. 

I was trying to interpolate color variables:

From:

```stylus
a
  border-bottom-color rgba(37, 116, 168, 0.9)
  background-image linear-gradient(180deg,rgba(37, 116, 168, .4) 0,transparent 1px,transparent)
```

To:

```stylus

$color-a = rgb(37, 116, 168)
$size-b = 1px
a
  border-bottom-color rgba($color-a, 0.9)
  background-image "linear-gradient(180deg,rgba(%s, .4) 0,transparent %s,transparent)" % ($color-a $size-b)
```

And since the `border-bottom-color` color works, why wouldn't it work in string interpolation. But it struck me, the interpolation is sent straight trough the parser, right?

Because this is the desired outcome:


```css
a{
  border-bottom-color: rgba(37, 116, 168, 0.9);
  background-image: linear-gradient(180deg,rgba(37, 116, 168, .4) 0,transparent 1px,transparent);
}
```

But we get this:

```css
a{
  border-bottom-color: rgba(37, 116, 168, 0.9);
  background-image: linear-gradient(180deg,rgba(#2574a8, .4) 0,transparent 1px,transparent);
}
```

One way is to do this:


```stylus

$color-a = rgb(37, 116, 168)
$size-b = 1px
a
  border-bottom-color rgba($color-a, 0.9)
  background-image "linear-gradient(180deg,%s 0,transparent %s,transparent)" % (rgba($color-a, .4) $size-b)
```

But it's not very readable.

And this does not either work:


```stylus

$color-a = rgb(37, 116, 168)
a
  color rgba($color-a, 0.9) // results in rgba(37, 116, 168, 0.9)
  color rgba($color-a, 1) // results in #2574a8
```

Which makes things a bit inconsistent when searching and debugging the code.

Dunno if this is a rant or a real issue, but needed to jot down my thoughts about this..
