### ISSUE TITLE
Use semver

### ISSUE THREAD

**Issue by TimothyGu** [stylus/stylus#2220]
As is the npm tradition, packages are usually versioned with [Semantic Versioning](http://semver.org/) in mind. Stylus however does not conform with this custom, and that makes upgrading Stylus a constant task for fear of possible issues that may arise with the use of `"stylus": "*"` as a dependency. As a result, would it be possible for the development team to use Semantic Versioning in the next releases? Thanks.

**Comment by Panya** [comment]
We're using semver. https://github.com/stylus/stylus/blob/dev/Contributing.md#releasing-workflow

**Comment by TimothyGu** [comment]
But since Stylus still uses 0.x, the semver usage is basically moot, as it explicitly allows _anything_ to happen in 0.x stage. Indeed, semver recommends getting to 1.0.0:

> #### How do I know when to release 1.0.0?
>
> If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backwards compatibility, you should probably already be 1.0.0.

More pragmatically, staying in 0.x stage disallows the use of `^` version specifier in npm, which is the default for `npm install --save`.
