### ISSUE TITLE
Hash values are not usable inside the hash itself

### ISSUE THREAD

**Issue by tarekis** [stylus/stylus#2222]
Using a hash's variable in the hash itself throws an error:

    variable = {
       color: red,
       alphacolor: alpha(variable.color,0.5)
    }
    variable has no property .variableName

However, using a seperate hash and accessing it works.

    fakeVariable = {
       color: red
    }

    variable = {
       alphacolor: alpha(fakeVariable.color,0.5)
    }

Is it intended that hash values are inaccessible in themself, even if the required variable is defined before the one that uses it?

I am using the nib@1.1.0 compiler, which uses stylus@0.49.3.

**Comment by Panya** [comment]
Yes, it is intended behaviour. As in JS and many other languages you can't reference a hash key in another key's value while defining this hash.

**Comment by tarekis** [comment]
Makes perfect sense now, thanks!
