### ISSUE TITLE
sprintf not working as expected

### ISSUE THREAD

**Issue by corysimmons** [stylus/stylus#2225]
According to the docs, Stylus' sprintf runs through `s()`, but I'm getting mixed results.

```styl
$letters = a b c
$number = 1

content: '%s %s' % $letters $number
content: s('%s %s', $letters, $number)
```

```styl
content: a b 1;
content: a b c 1;
```

`s()` works as expected, but sprintf clips the `c` for some reason.

The problem seems to get worse when interweaving with other characters:

```styl
$letters = a b c
$number = 1

content: 'foo(%s)[%s]' % $letters $number
content: s('foo(%s)[%s]', $letters, $number)
```

```styl
content: foo(a)[b] 1;
content: foo(a b c)[1];
```

If I try to wrap the letters in an unquote like so `$letters = unquote('a b c')`, `s()` continues to work as expected, but the sprintf returns `content: foo(a b c)[] 1;`.

Seems like a bug.

**Comment by Panya** [comment]
You need to wrap the values into brackets (if number of values > 1):
```styl
$letters = a b c
$number = 1

body
  content: '%s %s' % ($letters $number)
```

**Comment by vendethiel** [comment]
Lol, what happens is that it takes `$letters` as the whole array, so print a b (and then the $number is just there, detached from % which is binary). Funny.

**Comment by corysimmons** [comment]
@Panya Bless you.
