### ISSUE TITLE
Compile-time errors when using undefined variables

### ISSUE THREAD

**Issue by jeffijoe** [stylus/stylus#2229]
Currently, Stylus does nothing when using an undeclared variable:

```stylus
button
  color: $color
```

I think compile-time errors when using undeclared variables would be nice - if anything behind a flag?

**Comment by Panya** [comment]
Duplicate of #809

**Comment by jeffijoe** [comment]
@Panya apologies, I did see that issue but it didn't seem it suggested throwing on undefined variables. Any progress on #809?

**Comment by xmedeko** [comment]
Duplicate of #811
