### ISSUE TITLE
Get the name of stylus file in current block where mixin call

### ISSUE THREAD

**Issue by werty1001** [stylus/stylus#2230]
Hi, i know how to get the name of stylus file in current block (from [issues#1959](https://github.com/stylus/stylus/issues/1959))
```
module.exports = function() {
    return function(style) {
        style.define('get-filename', function() {
            return this.currentBlock.filename;
        });
    };
};
```
It work, but if use this function in mixin:
```
// mixins.styl

mymixin()
    test: get-filename()
```

And call mixin in another files
```
// main.styl

body
    mymixin()

// Result

body {
    test: 'mixins.styl'; // need main.styl
}
```
get-filename() always return mixins.styl, becouse this mixin in mixins.styl file.

it is possible to fix?

**Comment by Panya** [comment]
No, sorry. I won't fix it.
