### ISSUE TITLE
Transparent mixins don't accept arguments the same way that explicit mixins do

### ISSUE THREAD

**Issue by bkjohnson** [stylus/stylus#2236]
I have a mixin defined for transitions:
```
transition(val)
  -webkit-transition: val
  -moz-transition: val
  -ms-transition: val
  -o-transition: val
  transition: val
```

This is the input/output when I call it as an explicit mixin

### Input
```
.container
  transition(background 0.25s linear)
```

### Output
```
.container {
  -webkit-transition: background 0.25s linear;
  -moz-transition: background 0.25s linear;
  -ms-transition: background 0.25s linear;
  -o-transition: background 0.25s linear;
  transition: background 0.25s linear;
}
```

This is fine and expected.  However, using a transparent mixin results in incorrect output:

### Input
```
.container
  transition: background 0.25s linear
```

### Output
```
.container {
  -webkit-transition: background;
  -moz-transition: background;
  -ms-transition: background;
  -o-transition: background;
  transition: background;
}
```

This is  unexpected behavior since everything after the first space is cut off.  Clearly a workaround is to not use transparent mixins, but adding a feature shouldn't break things if you decide to use it.  I also realize that I could change the mixin so that it wrote `unquote(val)` and call it like `transition: "background 0.25s linear"` but then I think it ceases to be a 'transparent' mixin.

**Comment by Panya** [comment]
You should use `arguments` in this case. That's documented [here](http://stylus-lang.com/docs/mixins.html).
```styl
transition()
  -webkit-transition: arguments
  -moz-transition: arguments
  -ms-transition: arguments
  -o-transition: arguments
  transition: arguments
```

**Comment by bkjohnson** [comment]
Thank you for pointing that out, sorry I didn't catch it on my own!
