### ISSUE TITLE
1.0.0 Release?

### ISSUE THREAD

**Issue by wayneashleyberry** [stylus/stylus#2237]
Hi :) Is there a planned 1.0.0 release, or milestone, for Stylus? I'm not questioning stability or usability, the exact opposite. I think this project is very mature. We've been using Stylus to write production styles for ages. I think that semantic versioning is important and seeing the project still on `0.*` gives the wrong impression to newcomers or people investigating the technology.

**Comment by bkjohnson** [comment]
I'm also interested in this.  I read the [wiki page](https://github.com/stylus/stylus/wiki/1.0.0) which talks about the 1.0.0 release.  Would pull requests for some of these changes be accepted, or is that kind of core work meant to come Stylus members rather than contributors?

**Comment by wayneashleyberry** [comment]
Thanks for pointing out that wiki page @bkjohnson, I wasn't aware of it. Considering that entry is almost a year old, I wonder what's been happening since...

**Comment by bkjohnson** [comment]
@Panya any news on this?

**Comment by kizu** [comment]
Both I and @Panya don't have much free time these days (and I didn't have it even to check the issues until now), so we can't estimate when the 1.0.0 would be complete. We, of course, always welcome PRs!
