### ISSUE TITLE
possibility of placeholders doubling as css classes

### ISSUE THREAD

**Issue by cjaoude** [stylus/stylus#2247]
it may be interesting to have placeholders also render as classes. ex:

```
// placeholder
$hidden
    display none

// ...could also be used as .hidden
```

right now it would have to be duplicated, or done like this

```
.hidden
    @extend $hidden
```

**Comment by Panya** [comment]
Sorry, but I don't understand the feature request. The whole idea of placeholder selectors is to use with `@extend` (while they don't render in the output CSS). If you need a normal class — use normal class (your second example is ok).
