### ISSUE TITLE
bug: expected "indent", got "outdent" -- stylus

### ISSUE THREAD

**Issue by EryouHao** [stylus/stylus#2249]
I use vue-cli, webpack, stylus, stylus-loader.the stylus-loader's version is 2.3.1 and the stylus's version is 0.54.5
the DOM
``` html
         <div class="logo">
            <i class="icon-shopping_cart"></i>
         </div>
        </div>
        <div class="price">0 元</div>
        <div class="desc">
```
the Stylus
``` stylus
.logo
  width: 100%
  height: 100%
  border-radius: 50%
.price
  display: inline-block
  vertical-align: top
.desc
  display: inline-block
```
the Error
``` shell
Module build failed: ParseError: E:\FED\project\sell\src\components\shopcart\shopcart.vue:72:7
   68|         border-right: 1px solid #rgba(255, 255, 255, 0.1)
   69|         font-size: 16px
   70|         font-weight: 700
   71|         color: rgba(255, 255, 255, 0.4)
   72|       .desc
-------------^
   73|         display: inline-block
   74|         vertical-align: top
   75|         line-height: 24px

expected "indent", got "outdent"
```

**Comment by vendethiel** [comment]
Your `.logo` is indented.

**Comment by EryouHao** [comment]
@vendethiel oh,sorry, I copyed is wrong.

**Comment by Panya** [comment]
Seems like you are mixing tabs and spaces or different levels of indentation. Your code is ok, see an [example](http://stylus-lang.com/try.html#?code=.logo%0A%20%20width%3A%20100%25%0A%20%20height%3A%20100%25%0A%20%20border-radius%3A%2050%25%0A.price%0A%20%20display%3A%20inline-block%0A%20%20vertical-align%3A%20top%0A.desc%0A%20%20display%3A%20inline-block).

**Comment by EryouHao** [comment]
@Panya  OK, It's my fault,  I writed `border-right: 1px solid #rgba(255, 255, 255, 0.1)`  delete the `#` is ok.
thanks.
