### ISSUE TITLE
Do you have like sass usage  @content

### ISSUE THREAD

**Issue by wanghuaDev** [stylus/stylus#2251]
@mixin media-breakpoint-up($name, $breakpoints: $grid-breakpoints) {
  $min: breakpoint-min($name, $breakpoints);
  @if $min {
    @media (min-width: $min) {
      @content;
    }
  } @else {
    @content;
  }
}

**Comment by Panya** [comment]
Yes, see [block mixins](http://stylus-lang.com/docs/mixins.html#block-mixins).

P.S. StackOverflow is better for this kind of questions.
