### ISSUE TITLE
Problem with the watch on windows10

### ISSUE THREAD

**Issue by Makio64** [stylus/stylus#2252]
Hello,

After using the watch option and the first compilation success if I want rewrite the file or the folder, I get : 
EPERM: operation not permitted, unlink 'C:\.....\css'

This doesnt happen if I manually compile at each change.

My guess its the watch stream create problem, this kind of problem doesnt happen with other watch task like webpack.

**Comment by Makio64** [comment]
Was exploring the pull request and this pull request fix the bug : 
https://github.com/stylus/stylus/pull/2168

**Comment by iChenLei** [comment]
closed by #2168
