### ISSUE TITLE
Commas in variable definitions break rendering

### ISSUE THREAD

**Issue by jjcm** [stylus/stylus#2254]
`$var = rgba(255,255,255,0.5) `

this will result in everything after the first comma being inserted as is on a new line, and the variable only having the 'rgba(255' stored.

**Comment by jjcm** [comment]
As a workaround you can use

`$var = unquote('rgba(255,255,255,0.5)')

Feels a bit hacky though.

**Comment by jjcm** [comment]
Actually closing this for now as I can't get it to replicate all the time. Something else is going on here. I'll re-open this when I can reliably replicate it.

**Comment by Panya** [comment]
Hmm, it's strange. I'm 100% sure, that this code [works](http://stylus-lang.com/try.html#?code=%24var%20%3D%20rgba(255%2C255%2C255%2C0.5)%0A%0Abody%0A%20%20color%3A%20%24var).
