### ISSUE TITLE
Negative variable without colon ignored by render

### ISSUE THREAD

**Issue by alekspetrov** [stylus/stylus#2255]
Negative variable issue.
If no colon after property, this property will ignored":

```
value = 100px

.foo 
    width 10px
    margin-left -(value)
```

wil render as: 
```
.foo {
    width: 10px;
}
```

**Comment by Panya** [comment]
Hmm, all works as [expected](http://stylus-lang.com/try.html#?code=value%20%3D%20100px%0A%0A.foo%20%0A%20%20%20%20width%2010px%0A%20%20%20%20margin-left%20-(value)). Try to update Stylus version.
