### ISSUE TITLE
Browsers support?

### ISSUE THREAD

**Issue by bernex** [stylus/stylus#2256]
I make client version, do you test it in browsers? Do you have capability list?
Good for production? I wanna you stylus in css preview editor.

**Comment by Panya** [comment]
It tested and works in IE11+ and all modern browsers.

**Comment by bernex** [comment]
What's about ie 9, 10?

**Comment by kizu** [comment]
The client-side version was not even meant for production. You can test it in ie 9/10 by yourself (at http://stylus-lang.com/try.html), but we're not planning on fixing any of the issues that can appear in old browsers.
