### ISSUE TITLE
Exclude folders starting with (anything) using glob

### ISSUE THREAD

**Issue by phaistonian** [stylus/stylus#2258]
Hello.

Is it possible to, say, `import 'path/**/index.styl' but exclude the folders that their name starts with a pattern?

For example match `path/folder/index.styl' but NOT 'path/_folder/index.styl`?

Thank you.

**Comment by Panya** [comment]
Yep, something like this:
```styl
@import 'path/[!_]**/index.styl'
```

**Comment by phaistonian** [comment]
Works like a charm, however, if no matching file is found then a module build error is spawned on Webpack.

In other words, at least one matching file *should* be found.

This is perhaps a stylus loader issue,  not a stylus one per se.

**Comment by Panya** [comment]
It is not Webpack. Any Stylus import should load at least one file (in other words we don't support optional imports currently).

**Comment by phaistonian** [comment]
Thank you for the heads up. 

Is such a feature planned?
