### ISSUE TITLE
Support for scrollbar styling

### ISSUE THREAD

**Issue by pierrebonbon** [stylus/stylus#2261]
As far as I know neither `Stylus` nor any of its plugins support scrollbar customization. If I'm right, I wonder if it could be implemented?

Scrollbar customization is done via the scrollbar pseudo-element in -webkit browsers. This allows easy styling of the scrollbar [features](https://webkit.org/blog/363/styling-scrollbars/). In Internet Explorer (ie8 and above), the same can be done with the [`scrollbar-xxx-color` properties](https://msdn.microsoft.com/pt-pt/library/ms531160(v=vs.85).aspx). Unfortunately, Gecko-based browsers don't have anything similar. Despite this, I think it might make sense to support scrollbar styling.

**Comment by Panya** [comment]
What do you mean by:
> As far as I know neither Stylus nor any of its plugins support scrollbar customization.
?

Stylus supports these properties and pseudo-elements you can use them as in normal CSS:
```styl
::-webkit-scrollbar
    width: 13px
    height: 13px

body
    scrollbar-highlight-color: aqua
    scrollbar-face-color: blue
    scrollbar-arrow-color: blue
```

See [an example](http://stylus-lang.com/try.html#?code=%3A%3A-webkit-scrollbar%0A%20%20%20%20width%3A%2013px%0A%20%20%20%20height%3A%2013px%0A%0Abody%0A%20%20%20%20scrollbar-highlight-color%3A%20aqua%0A%20%20%20%20scrollbar-face-color%3A%20blue%0A%20%20%20%20scrollbar-arrow-color%3A%20blue).

**Comment by pierrebonbon** [comment]
Sorry for that! I obviously didn't find that page when looking around for scrollbar styling support in `Stylus`.

**Comment by pierrebonbon** [comment]
I didn't articulate my question well. Maybe we could have a shorthand of various properties so that if we wrote something like this:

    body
        scrollbar 12px 12px blue red yellow
      
It would compile to this:

    ::-webkit-scrollbar {
         width: 12px;   /* vertical scrollbars */
         height: 12px;   /* horizontal scrollbars */
    }

    ::-webkit-scrollbar-track {
        background: blue;
    }

    ::-webkit-scrollbar-thumb {
        background: red;
    }

    ::-webkit-scrollbar-button {
        background: yellow;
    }

    body {
        scrollbar-track-color: blue;
        scrollbar-face-color: green;
        scrollbar-track-arrows: yellow;
    }

 
   `

**Comment by Panya** [comment]
Well, you always can write a mixin like this:
```styl
scrollbar(width, height, track-color, thumb-color, button-color)
  /::-webkit-scrollbar
     width width
     height height

  /::-webkit-scrollbar-track
    background track-color

  /::-webkit-scrollbar-thumb
    background thumb-color

  /::-webkit-scrollbar-button
    background button-color

  &
    scrollbar-track-color track-color
    scrollbar-face-color thumb-color
    scrollbar-track-arrows button-color


body
  scrollbar 12px 12px blue red yellow
```

Anyway, this should be in libraries like nib, not in the Stylus core.

**Comment by pierrebonbon** [comment]
Yep, I will suggest a mixin for `nib`. Thanks!
