### ISSUE TITLE
The reverse of @import ( feature suggestion )

### ISSUE THREAD

**Issue by wamoyo** [stylus/stylus#2262]
Making a quick feature suggestion. One of the things I do repeatedly is that every time I add a page to a section of my site, with its own styles (which reside in a `.styl` file), I have to go back to my `main.styl` and add an `@import` statement.

If I only have one layout, I'd simply import a whole directory of individual `.styl` files, but I often use a mobile and desktop, or a standard and minimal layout, and it would be relevant to be able to include only the relevant `@import`s in the appropriate `main.styl` file (in my case `standard.styl` and `minimal.styl`). 

What I'm currently getting set up to do is read a comment at the top of the `.styl` file that simply says `// extend standard` or `// extend minimal` then building up two stylus command to run, one for each of my resulting CSS files.

It's worth debating the wording here. 

```
// sendto main.styl
// exportto main.styl
// goto standard.styl
// markfor minimal
// for standard
// something else...?
```

**Comment by kizu** [comment]
I'm not sure this kind of thing is a wide-enough case to support natively in Stylus, and there are already some ways to achieve this using native stuff ([using conditions](http://stackoverflow.com/questions/41337449/can-i-do-the-reverse-of-import-in-stylus/41343083#41343083) or using the existing glob import's features).
