### ISSUE TITLE
Middleware force option doesn't work!

### ISSUE THREAD

**Issue by ivands** [stylus/stylus#2265]
The middleware force option doesn't work!
Is this a bug or am i doing something wrong?

```coffeescript
compile = (str, path)->
	s = stylus str
	s.set 'filename', path
	s.use nib()
	s.import 'nib'
	return s

module.exports = stylus.middleware
	src: 		path.join process.cwd(), 'resources/styles/frontend'
	dest: 		path.join process.cwd(), 'public/assets'
	sourcemap: 	true
	force: 		config.debug
	compile: 	compile
```

**Comment by Panya** [comment]
I've checked it and all work as expected. Can you try to run your server with `DEBUG=stylus:*` before the command (e.g. `DEBUG=stylus:* node server.js`) and see if there is a call to Stylus middleware after the second request to a Stylus file?

**Comment by ivands** [comment]
Fails alert.
The issue was my route ordering.
