### ISSUE TITLE
Web fonts getting inlined

### ISSUE THREAD

**Issue by k1sul1** [stylus/stylus#2266]
For whatever reason,  Stylus is inlining my @font-face web fonts when using the `--inline` option. 

Before you call me a donkey for using the `--inline` option and wondering why web fonts are getting inlined, this is clearly stated in the docs: 

`-U, --inline            Utilize image inlining via data URI support`

This is pretty bad. Why? 

Browsers only load the web font file that they use, inlining inlines *all* source files if they fit under the magical 30KB limit, potentially making the css file *massive*. Just last week I noticed my css file was over 250KB!  

Consider this. All referenced files are 25KB, thus inlined by Stylus. My browser would only load the woff2 files, but because they are all inlined, the browser loads 100KB worth of fonts instead of 50KB. 
```
@font-face {
  font-family: 'somefont'
  src:  url('fonts/regular.woff2') format('woff2'),
        url('fonts/regular.woff') format('woff')
  font-weight: 400
}

@font-face {
  font-family: 'somefont'
  src:  url('fonts/bold.woff2') format('woff2'),
        url('fonts/abold.woff') format('woff')
  font-weight: 700
}
```

I'm suggesting adding a new option that excludes web fonts, no matter what size from being inlined, because I'm assuming changing this now would break a lot of existing projects.

**Comment by Panya** [comment]
You can disable `--inline` and use [embedurl](http://stylus-lang.com/docs/bifs.html#embedurlpath-encoding) when needed.

**Comment by k1sul1** [comment]
That's a great alternative. Didn't know about that! 

Thanks.
