### ISSUE TITLE
bug with some selector having "+" operator

### ISSUE THREAD

**Issue by jbdemonte** [stylus/stylus#2267]
This piece of code doesn't works:

    div
        span + span
        a + a
            margin 10px

We need to separate as follow:

    div
      span + span
        margin-left 10px
      a + a
        margin-left 10px

To get:

    div span + span {
        margin-left: 10px;
    }
    div a + a {
        margin-left: 10px;
    }

**Comment by Panya** [comment]
No need to separate, you can just add a comma:
```styl
div
    span + span,
    a + a
        margin 10px
```
