### ISSUE TITLE
Two initial reference on line without space between them

### ISSUE THREAD

**Issue by akellbl4** [stylus/stylus#2268]
Bug:
https://dl.dropboxusercontent.com/s/xavxyz1fv8hm7nh/InitialReference.png?dl=0

I solved this with use partial reference, but initial reference with equal conditions not work.
https://dl.dropboxusercontent.com/s/yu5or421kb7k14t/PartialReference.png?dl=0

**Comment by Panya** [comment]
That's correct behavior. From the [documentation](http://stylus-lang.com/docs/selectors.html#initial-reference):
> The only drawback is that you can use initial reference only at the start of a selector.

**Comment by akellbl4** [comment]
@Panya thanks, sorry
