### ISSUE TITLE
deps() missing some dependencies which has same name

### ISSUE THREAD

**Issue by kei-ito** [stylus/stylus#2269]
The [`deps()`](http://stylus-lang.com/docs/js.html#deps) missing some dependencies in some cases.

This issue is only for `deps()`. `render()` works fine: the compiled result contains the missed files. 

## Steps to reproduce the issue
Here's a sample to reproduce the issue.
https://github.com/kei-ito/stylus/tree/same-name-deps-resolver/test/deps-resolver/same-name

### 1. Create files
- **index.styl**  imports `b1`, `b2`, `a` in this order.
- **a**
  - **index.styl**
- **b1**
  - **index.styl** imports `a`.
  - **a.styl**
- **b2**
  - **index.styl** imports `a`.
  - **a.styl**

### 2. List dependencies
```
$ stylus --deps index.styl
```

## Expected result
```
b1/index.styl
b1/a.styl
b2/index.styl
b2/a.styl
a/index.styl
```

## Actual result
```
b1/index.styl
b1/a.styl
b2/index.styl
b2/a.styl
```

## Workaround
Fix the last line of `root/index.styl` from `@import 'a'` to `@import 'a/index'`.

**Comment by kei-ito** [comment]
It seems to be related to #1403.

**Comment by iChenLei** [comment]
colsed https://github.com/stylus/stylus/issues/1403
