### ISSUE TITLE
stylus hash with key as integer 

### ISSUE THREAD

**Issue by roji430** [stylus/stylus#2272]
i am facing an issue with stylus hash.
i wrote a something like following
`$a = {25:25%,50:50%,75:75%}` but its not working and prepros app get crash when i compile it.i can not literate  over the hash 
` for key,size in $a`
     `{key} size ` 
not working

**Comment by Panya** [comment]
According to [the documentation](http://stylus-lang.com/docs/hashes.html), you can't use numbers as keys of a hash:
> the keys should be either proper idents or strings:

**Comment by Arlen22** [comment]
But how would someone convert an integer to a string?
