### ISSUE TITLE
parameter inconsistency with linenos vs lineno

### ISSUE THREAD

**Issue by bmcminn** [stylus/stylus#2279]
OS: Win7 Pro 64-bit 
Stylus version: `^0.54.5`
-----

~~Stylus' internal Javascript API has a discrepancy between the documented `linenos` option and it's actual parameter name `lineno` as defined in `lib/rendere.js`:~~

~~https://github.com/stylus/stylus/blob/dev/lib/renderer.js~~

~~All references to documented option parameters should be consistent in all parts of the utility and should be changed to `linenos`.~~

nvm, realized the variable `options` in the `lib/render.js` context is actually config for the error formatter.

**Comment by bmcminn** [comment]
OS: Win7 Pro 64-bit 
Stylus version: `^0.54.5`
-----

~~Stylus' internal Javascript API has a discrepancy between the documented `linenos` option and it's actual parameter name `lineno` as defined in `lib/rendere.js`:~~

~~https://github.com/stylus/stylus/blob/dev/lib/renderer.js~~

~~All references to documented option parameters should be consistent in all parts of the utility and should be changed to `linenos`.~~

nvm, realized the variable `options` in the `lib/render.js` context is actually config for the error formatter.

**Comment by Panya** [comment]
Yep, `linenos` is the right option name (see https://github.com/stylus/stylus/blob/9fa99d1ed8346414d8cf9e8b4b5638459cfbc9de/lib/visitor/compiler.js#L31).
