### ISSUE TITLE
How to @import absolute path directly?

### ISSUE THREAD

**Issue by qingmingsang** [stylus/stylus#2281]
webpack
```
    resolve: {
        alias: {
            $variables: path.resolve('./styles/variables.styl')
        }
    }
```

xx.styl
```
@import  '$variables '

//error
```

How to `@import`  absolute path directly?

**Comment by Panya** [comment]
You should define a variable using `define` in stylus-loader options:
```js
stylus: {
  define: {
    $variables: path.resolve('./styles/variables.styl')
  }
}
```

And then inside a stylus file:
```styl
@import $variables
```

You can also use `import` option to auto-import these variables:
```js
stylus: {
  import: [
    path.resolve('./styles/variables.styl')
  ]
}
```

**Comment by qingmingsang** [comment]
thx,that's very helpful

**Comment by shammellee** [comment]
@Panya can you point me to documentation for `define` in your example? Is this a webpack or stylus property?

**Comment by Panya** [comment]
It's not documented(?) property of the stylus-loader options object. It corresponds to `define` method of the stylus JS API (see http://stylus-lang.com/docs/js.html#definename-node). See https://github.com/shama/stylus-loader/blob/master/index.js#L77-L81

**Comment by aseem2625** [comment]
Strange, `@import $variables` throws me error `failed to locate @import file $variables.styl`
