### ISSUE TITLE
Possible to update global variable from mixin or function?

### ISSUE THREAD

**Issue by sevenupcan** [stylus/stylus#2286]
Hi, I've encountered a situation where I need to modify a variable used inside a function, which the result of, is then used by another function inside that function.

Here is my (arbitrary) example
````stylus
default-font-size = 16px

calc-font-size()
    font-size / default-font-size

font-scale(font-size-multiplier)
    font-size = font-size-multiplier * 2
    font-size: calc-font-size()
````

However this will error because the `font-size` variable referenced in the `calc-font-size()` function is presumably looking for a global variable (because there is not local variable called font-size)?

What's the correct way to handle a situation like this?

I was hoping to avoid having to pass the `font-size` variable as an argument through the `calc-font-size` function like the example below.

````stylus
default-font-size = 16px

calc-font-size(font-size)
    unit(font-size / default-font-size, em)

font-scale(font-size-multiplier)
    font-size = font-size-multiplier * 2
    font-size: calc-font-size(font-size)
````

**Comment by Panya** [comment]
You can use [`define`](http://stylus-lang.com/docs/bifs.html#definename-expr-global) bif with `global` flag set to true to define/redefine global variable from local scope:
```styl
default-font-size = 16px

calc-font-size()
  font-size / default-font-size

font-scale(font-size-multiplier)
  define('font-size',  font-size-multiplier * 2, true)
  font-size: calc-font-size()
```

**Comment by sevenupcan** [comment]
Ah awesome. Thank you very much @Panya
