### ISSUE TITLE
Problem with embedurl(path) using a path with white spaces

### ISSUE THREAD

**Issue by SamuelGaona** [stylus/stylus#2287]
embedurl("../img/a space.svg", 'utf8');

**Comment by maranomynet** [comment]
This gets compiled to `url("../img/a%20space.svg");` in the CSS file - even though the file exists.

However, if I rename the file to `a%20space.svg` the above `embedurl()` command finds the file, reads it and returns a `data:` URI

**Comment by AzureusSme** [comment]
So, we stick to the %20 solution?

**Comment by maranomynet** [comment]
The only workaround I've found is to remove spaces from the filenames of images you intend to parse with `embedurl()`

**Comment by AzureusSme** [comment]
There is no urlencode(string) function?

**Comment by maranomynet** [comment]
In this case a urlencode function wouldn't help. This is a bug in stylus, and the only workaround ATM is to rename your file.

**Comment by iChenLei** [comment]
see https://github.com/stylus/stylus/issues/2287#issuecomment-297402658
