### ISSUE TITLE
There is a difficulty to write mixin with "flex"

### ISSUE THREAD

**Issue by toxichl** [stylus/stylus#2289]
like this example:
```
$flex-fixed-width($width)
  flex 0 0 $width px
  width $width px

.flex-fixed-child
  $flex-fixed-width(80)
```
the compiled result as follows：
```
.flex-fixed-child {
  flex: 0 0 80 px;  // Wrong
  width: 80px;
}
```
This is not what I want, How to write this can I get the result as follows ?
 ```
.flex-fixed-child {
  flex: 0 0 80px;  // Right
  width: 80px;
}
```
I have tried many different writing patterns but did not find a solution, very hoping to get a solution for this.
thanks.

**Comment by futekov** [comment]
You can write either:
`flex 0 0 unit($width, px)`
...or:
`flex 0 0 ($width)px`
...or even:
`flex 0 0 ($width * 1px)`

PS: Just fyi, stackoverflow is probably a better place to ask such questions, and always read the docs ([they often contain the answer](http://stylus-lang.com/docs/bifs.html)).
