### ISSUE TITLE
Stylus is treating variables in media query as media types

### ISSUE THREAD

**Issue by k1sul1** [stylus/stylus#2292]
I keep my media queries in a json file, which I import to variables using the built-in `json()` function. It works great, but...

This doesn't work.
```
@media tablet, hybrid, phone {
  display: none
}
```

The end result looks something like this: `@media tablet,hybrid,phone{#main-header{display:none}}`

This on the other hand works:

```
mq = {
  desktop: desktop,
  laptop: laptop,
  tablet: tablet,
  hybrid: hybrid,
  phone: phone
}

@media mq.tablet, mq.hybrid, mq.phone {
  display: none
}
```

Output: `@media (min-width: 769px) and (max-width: 1024px),(min-width: 481px) and (max-width: 768px),(min-width: 0px) and (max-width: 480px){#main-header{display:none}}`

So it seems that Stylus is treating those variables as media types, but handles properties from hashes correctly. Is this fixable?

**Comment by Panya** [comment]
> Is this fixable?
ATM no, sorry.

Another workaround:
```styl
cond = join(',', tablet, hybrid, phone)

@media cond
  display: none
```

**Comment by k1sul1** [comment]
Fair enough.

Thanks for the tip!
