### ISSUE TITLE
grid-template-areas problem

### ISSUE THREAD

**Issue by kameas** [stylus/stylus#2293]
in example: https://codepen.io/anon/pen/OmNEzQ

if i write 
grid-template-areas "header header"
                                 "navigation content"
                                 "footer footer"

style is not compile, but
grid-template-areas "header header" "navigation content" "footer footer" 

 work fine, but its not pretty :(

**Comment by maranomynet** [comment]
Beause Stylus allows bracket- and (semi)colon-less syntax it has to treat newlines as significant by default.

You can work around this by adding `\` to the end of each line you want to soft-break
...like so:

```stylus
.wrapper
    display grid
    grid-template-columns 1fr 1fr
    grid-template-areas "header header"\
                        "navigation content"\
                        "footer footer"
```

Example: http://stylus-lang.com/try.html#?code=.wrapper%0A%20%20display%20grid%0A%20%20grid-template-columns%201fr%201fr%0A%20%20grid-template-areas%20%22header%20header%22%5C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22navigation%20content%22%5C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22footer%20footer%22

**Comment by kameas** [comment]
@maranomynet Спасибо, товарищ!

**Comment by maranomynet** [comment]
Добро пожаловать.

**Comment by Messiahhh** [comment]
Thanks
