### ISSUE TITLE
'px' change to 'rem'

### ISSUE THREAD

**Issue by Jesonhu** [stylus/stylus#2294]
I want  'px' change to 'rem'
`
px2rem($name, $val)
  $name: $val / 75 * 1rem
`
use method
`
px2rem('height', 55px)
`
but has a error , what I should to improve

**Comment by Panya** [comment]
```stylus
px2rem($name, $val)
  {$name}: ($val / 75) * 1rem
```

P.S. Please, use StackOverlow for this kind of questions.
