### ISSUE TITLE
stylus watch small bug with @require './*'.

### ISSUE THREAD

**Issue by Lee182** [stylus/stylus#2302]
I've noticed a small bug in the the stylus watch code for version 0.54.5
```
@require './components/*'
```
I use the line above to require all the stylus code for components. Basically when I add a new .styl file the watcher doesn't register that an change has happened, so i have to cancel and restart my css npm script.

(heres my npm script line just incase)
```
"watch-css": "stylus -w ./app/*.styl -o ./dist/"
```

**Comment by Panya** [comment]
Duplicate of #742
