### ISSUE TITLE
@extend with &

### ISSUE THREAD

**Issue by Jorenm** [stylus/stylus#2311]
I have this selector that I want to use @extend on:

```
.icon
	display: inline-block
	margin: 0 14px
	&.diamond
		width: 9px
		height: 9px
		&.grey
			bgimage('diamond-embelishment-dark-gray.svg', true)
			background('contain')
		&.red
			bgimage('diamond-embelishment-red.svg', true)
			background('contain')
```

I'm trying to extend it using @extend .icon .diamond and @extend .icon.diamond, both fail. Am I using this wrong, or is this not supported?

**Comment by Panya** [comment]
Please, provide an example that is not working. Are you trying to write:
```styl
.icon
	display: inline-block
	margin: 0 14px
	&.diamond
		width: 9px
		height: 9px
		&.grey
			bgimage('diamond-embelishment-dark-gray.svg', true)
			background('contain')
			@extend .icon.diamond
		&.red
			bgimage('diamond-embelishment-red.svg', true)
			background('contain')
```
? If so, this example works as expected in the latest version of Stylus.

**Comment by Jorenm** [comment]
Ok so the css I'm trying to use for @extend is in the OP. This is where I'm trying to extend it:

ul.link_list
	reset-list()
	text-align: center
	li
		display: inline-block
		a
			font-size: 14px
			color: $color_dark
			text-decoration: none
		&:before
			content: ' '
			@extend .icon.diamond.red
		&:first-child:before
			display: none

That produces this output in Chrome's style view:

ul.link_list li:before {
    content: ' ';
}
(index):42
.icon.diamond.red, ul.link_list li:before {
    background-image: url(/wp-content/themes/serra/css/images/diamond-embelishment-red.svg);
    -webkit-background-size: contain;
    -moz-background-size: contain;
    background-size: contain;
    background-position: center center;
    background-repeat: no-repeat;

It's lacking the styles from .icon and the ones from .diamond, only showing the ones from .red.

If I instead try to use

@extend .icon, .icon.diamond, .icon.diamond.red

It only has the styles from .icon

**Comment by Jorenm** [comment]
Perhaps I misunderstand how this is supposed to work? As I understand it, this is meant to import the styles for a given selector?

**Comment by Panya** [comment]
Well, it's because Stylus currently extends only exact selector (while Sass/Less tries to extend the whole selector tree). See an issue #951.

**Comment by Jorenm** [comment]
Hmm. I can see what you mean, but then wouldn't this work?

@extend .icon, .icon.diamond, .icon.diamond.red

Seems like that should pull all the styles since each is an exact selector?
