### ISSUE TITLE
Stylus not working with nib? expected "indent", got ";" error

### ISSUE THREAD

**Issue by ybordag** [stylus/stylus#2313]
So I'm pretty new to stylus and I'm trying to run a piece of stylus using nib.
When I run this
C:\Users\ybord\Documents\Code\MyWebsite>stylus menu-btn.styl --out /css --compress

I get the error:
C:\Users\ybord\AppData\Roaming\npm\node_modules\stylus\bin\stylus:661
              throw new Error(err);
              ^

Error: ParseError: node_modules/nib/lib/nib.js:15:108
   11| var stylus = require('stylus'),
   12|     path = require('path'),
   13|     nodes = stylus.nodes,
   14|     utils = stylus.utils,
   15|     Canvas;
------------------------------------------------------------------------------------------------------------------^
   16|
   17| exports = module.exports = plugin;
   18|

expected "indent", got ";"

    at C:\Users\ybord\AppData\Roaming\npm\node_modules\stylus\bin\stylus:661:21
    at Renderer.render (C:\Users\ybord\AppData\Roaming\npm\node_modules\stylus\lib\renderer.js:107:12)
    at C:\Users\ybord\AppData\Roaming\npm\node_modules\stylus\bin\stylus:655:15
    at tryToString (fs.js:512:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:500:12)

I'm pretty certain that this is not being caused by my code, however, I'm not sure what to make of this error message.

I'm running node v8.1.0, stylus 0.54.5, and nib 1.1.2

**Comment by atilkan** [comment]
Can we see your code?
Look there are similar issues. I assume you are using Windows.

**Comment by Femonzor** [comment]
please see the stylus document.
[http://stylus-lang.com/docs/executable.html#utilizing-plugins](url)
u should use `--include` or `-I` flag to add the path of nib to to the stylus lookup paths.
