### ISSUE TITLE
Document :export syntax

### ISSUE THREAD

**Issue by daniel-shuy** [stylus/stylus#2316]
It seems that the recommended way to share variables between Stylus and JavaScript is to declare them in a JSON file and import them into Stylus. However, the issue with that approach is that you cannot declare "computed" variables in JSON, unlike in Stylus, eg.
```stylus
$text-color = lighten(black, 17%)
```

After spending weeks scouring the internet for a solution, I discovered that the `:export` syntax can be used to export variables from Stylus to JavaScript, eg.
```stylus
// variables.styl
$text-color = lighten(black, 17%)

:export
    textColor $text-color
```
Then in JavaScript:
```javascript
import variables from 'variables'

alert(variables.textColor)    // displays #2b2b2b
```

I noticed that many others have this issue as well. It would really help if this syntax was officially documented.

**Comment by Panya** [comment]
There is nothing to document in this repo because `:export` is not a Stylus feature. The feature is from css-modules.

**Comment by daniel-shuy** [comment]
Oh, I see. Apparently the `css-loader` module for Webpack was converting it to a css-module. Thanks.

Even though it isn't a Stylus feature, could this be documented as the recommended way to export Stylus variables to JavaScript?
