### ISSUE TITLE
Remove comments on compile with --compress option

### ISSUE THREAD

**Issue by amiut** [stylus/stylus#2318]
Is there a way to remove comments when generating minified CSS with the CLI? 
I'm using `stylus -w -m --compress styles.styl --out ../` but comments remain in the compiled CSS file,
if it's not possible, is there a way to give the minification job to [csso](https://github.com/css/csso-cli) ?
I appreciate any help

**Comment by Panya** [comment]
They should be removed. Except the comments start with `/*!` see (http://stylus-lang.com/docs/comments.html#multi-line-buffered).

> if it's not possible, is there a way to give the minification job to csso ?

yep, see [stylus-csso](https://github.com/sapegin/csso-stylus). You can also use Stylus as a grunt/gulp/webpack/browserify/whatever plugin/loader and use csso with it.

**Comment by amiut** [comment]
yes it was a `/*!` comment, thanks, problem solved
