### ISSUE TITLE
Stylus chokes on filter: alpha(opacity=50) (IE hack)

### ISSUE THREAD

**Issue by wildeyes** [stylus/stylus#2319]
http://stylus-lang.com/try.html#?code=body%20%7B%0A%20%20filter%3A%20alpha(opacity%3D40)%3B%0A%7D

`filter: alpha(opacity=50)` is a hack for [ie 5-7](https://css-tricks.com/snippets/css/cross-browser-opacity/).

stylus v.54.4

**Comment by Panya** [comment]
It's a known issue. You should use `unquote` in this case. See [the documentation](http://stylus-lang.com/docs/selectors.html#disambiguation).

P.S. It's 2017 now, no one supports IE 5-7 :)

**Comment by wildeyes** [comment]
Is this an issue that can be detected? Perhaps a friendly developer warning
is in order?
