### ISSUE TITLE
Concatenating variables in a Stylus mixin

### ISSUE THREAD

**Issue by mikem33** [stylus/stylus#2322]
I'm trying to make a mixin that generates some styles with variables, and I would like to concatenate two variables and I can't make it work. Here is an example:

```
centerSprite($icon)
    margin-top -(($ico_+$icon+_height) / 2)
    margin-left -(($ico_+$icon+_width) / 2)
```
I have a variable with the height and the width of an icon and I would like to to put the name in the arguments of the mixin to get that variable and make the operation...

I have made this question in Stackoverflow too... https://stackoverflow.com/questions/45752401/concatenating-variables-in-a-stylus-mixin

Thanks in advance!

**Comment by admannon** [comment]
Use [`lookup`](http://stylus-lang.com/docs/bifs.html#lookupname) is enough for this situation.

**warning**: please add `:` between `property name` and `property values` for prevent some bug.

``` stylus
$ico_test_width  ?= 20px
$ico_test_height ?= 15px

centerSprite($icon)
  margin-top : -(lookup('$ico_' + $icon + '_height') / 2)
  margin-left: -(lookup('$ico_' + $icon + '_width')  / 2)

body  
  centerSprite('test')
```
