### ISSUE TITLE
Support Cloud Sync/Storage

### ISSUE THREAD

**Issue by pwd-github** [stylus/stylus#2323]
Support cloud storage between devices via the browser.storage.sync API so that all devices can share the same userstyles.

**Comment by Panya** [comment]
I don't understand your request. Stylus is a CSS preprocessor, we don't store any userstyles. Maybe your request is better suitable for [Stylus Extension](https://github.com/openstyles/stylus)?

**Comment by jcklpe** [comment]
@Panya What's the difference between stylus extension and stylus? They aren't both under the same orgs? And their repos are both named stylus?

**Comment by jcklpe** [comment]
oh nvm, sorry now I see.
