### ISSUE TITLE
Feature for one line rule

### ISSUE THREAD

**Issue by kerrytazi** [stylus/stylus#2324]
Wasting space ->
```
.col0
    background #000
.col1
    background #111
.col2
    background #222
.col3
    background #333
```

Better to add something like "one rule syntax" and use for example `|` symbol ->
```
.col0 | background #000
.col1 | background #111
.col2 | background #222
.col3 | background #333
```

It is easily to read and looks nice (imao)

P.S. `.col0 { bacground #000 }` doesnt work, it is bad, i think

**Comment by vendethiel** [comment]
-1 for adding a feature where a loop would work better

**Comment by kerrytazi** [comment]
In this case, may be but what about ->
```
.flexparent | display flex
.flexchild | flex auto
.f2 | flex-grow 2
```
etc.

**Comment by lichenhao** [comment]
I don't think this is better.
The break line is more short and clean for your code~

**Comment by crisward** [comment]
`.col0 { bacground #000 }`
above doesn't work but this does.
`.col0 { bacground:#000 }`

If you want one line, just use valid css as in example 2.
