### ISSUE TITLE
Possible to install without command line access?

### ISSUE THREAD

**Issue by Alpha17x** [stylus/stylus#2326]
I've currently got a shared hosting plan and I'm entirely new to the concept of a 'preprocessor'.
I do not have anything bearing even the most remote resemblance to any form of command line or shell access.  I have a control panel. I can make adjustments to things like php settings.  Are there any alternative methods of 'installing' stylus? 

To be honest I'm not clear on if 'install' is even the right term. Can I for example. download a bunch of files, shove them into appropriate folders on the 'server' and have things work that way?  I read that it runs off of or requires node.js.   Is it a simple matter of literally having the node.js file present?

Odds are that I'll be abandoning my web host quite soon, as they've refused to keep up with anything other than the basics. but if I can avoid the aggravation of moving everything, I'd love to do so.

If not, then I'll have to abandon the concept and stick with css3 or something that has a far more broad range of support and instantaneous compatibility. But Stylus does look good, so if not now, perhaps some day.

**Comment by Panya** [comment]
You shouldn't install Stylus on your hosting. Stylus is for development environment only (compile `.styl` files and then upload resulting `.css` files to the hosting).
