### ISSUE TITLE
Feature: variable for identifier lines

### ISSUE THREAD

**Issue by JhonnyJason** [stylus/stylus#2328]
Hello, 
Just was looking for this feature and could not find a way to make it work.

My Scenario was to deal conveniently with `@media` queries. 
I like the nesting as it allows me to have the `@media` queries on the Object which is responsible for the style of that certain component.

So I do it this way:
```
#master-object
    mobilestyle
    @media screen and (min-width: mindesktopwidth)
        desktopstyle

#other-object
    mobilestyle
    @media screen and (min-width: mindesktopwidth)
        desktopstyle
```

What I was looking for was some way of:
```
desktop-version = @media screen and (min-width: mindesktopwidth)

#master-object
    mobilestyle
    desktop-version
        desktopstyle

#other-object
    mobilestyle
    desktop-version
        desktopstyle

```
I guess also for other long and verbouse identifiers that would be a nice enhancement and probably not too much a hassle to implement ;-)

Or is there any reason why one wouldn't want to use such feature - like performance etc.?

**Comment by Panya** [comment]
We don't want such feature because of it ambiguous with normal selectors (e.g. body, table etc). You can use a hash or normal variables in media queries like so:
```styl
mindesktopwidth = 768px
desktop-version = 'screen and (min-width: %s)' % mindesktopwidth
bp = {
  desktop-version: 'screen and (min-width: %s)' % mindesktopwidth
}

@media desktop-version
  body
    color: red

@media bp.desktop-version
  body
    color: blue
```

**Comment by JhonnyJason** [comment]
ok thnx that snippet works cool enough for the `@media`s ;-)
