### ISSUE TITLE
Would you provide the vscode support?

### ISSUE THREAD

**Issue by hstarorg** [stylus/stylus#2333]
I think the `vs code` is the very popular editor, would you provide the `vs code` plugin for code suggestion, format and highlight?

**Comment by Panya** [comment]
What about:
https://marketplace.visualstudio.com/items?itemName=sysoev.language-stylus
https://github.com/AlanCezarAraujo/vs-code-stylus
https://github.com/ThisIsManta/vscode-stylus-supremacy
