### ISSUE TITLE
Style name as the injected elements' attribute

### ISSUE THREAD

**Issue by SyntaxErrol** [stylus/stylus#2334]
Something like:

`<style id="stylus-21" data-name="My cool userstyle" type="text/css" class="stylus"></style>`

maybe?

**Comment by sheriffderek** [comment]
?

**Comment by vendethiel** [comment]
I guess they want the dataset to be stylus variables?

**Comment by Panya** [comment]
I guess you've mistaken this repo with https://github.com/openstyles/stylus.

**Comment by SyntaxErrol** [comment]
Wow. Yes, indeed.
