### ISSUE TITLE
How to escape/ignore a variable?

### ISSUE THREAD

**Issue by aconrad** [stylus/stylus#2337]
I'm trying to do this:

```css
flex-direction: column
```

... but it yields:

```css
flex-direction: 80px
```

... because somewhere we have legacy code that does:

```stylus
column = 80px
```

I tried doing string interpolation such as:

```stylus
flex-direction: '%s' % 'column'
```

but it renders as:

```css
flex-direction: 'column'
```

... which is invalid CSS when it contains quotes. I'm not sure how to get around this?

**Comment by Panya** [comment]
You can use [unquote](http://stylus-lang.com/docs/bifs.html#unquotestr--ident).

**Comment by aconrad** [comment]
Excellent, thanks @Panya!!
