### ISSUE TITLE
CLI - Hide output stats

### ISSUE THREAD

**Issue by peteringram0** [stylus/stylus#2349]
Is there a way with the CLI to hide the output? At the moment i get the following:

<img width="260" alt="screen shot 2018-01-10 at 11 41 39" src="https://user-images.githubusercontent.com/6588942/34771092-3e53181c-f5fb-11e7-8bd3-0097b75b43e4.png">

**Comment by vendethiel** [comment]
`stylus ... > /dev/null`?
