### ISSUE TITLE
How to strip units from a division?

### ISSUE THREAD

**Issue by nachocab** [stylus/stylus#2350]
I'm trying to calculate a `line-height` ratio by dividing two pixel values. Is there a way to remove the unit?

    $absolute-line-height = 15px
    $font-size = 10px

    body
      line-height: ($absolute-line-height / $font-size) // outputs 1.5px instead of 1.5

**Comment by Panya** [comment]
You can use `unit` bif with an empty second argument:
http://stylus-lang.com/try.html#?code=%24absolute-line-height%20%3D%2015px%0A%24font-size%20%3D%2010px%0A%0Abody%0A%20%20line-height%3A%20unit(%24absolute-line-height%20%2F%20%24font-size%2C%20'')

**Comment by nachocab** [comment]
Nice, thank you!

**Comment by atilkan** [comment]
@Panya link broken.
