### ISSUE TITLE
New and improved Vim plugin for Stylus

### ISSUE THREAD

**Issue by iloginow** [stylus/stylus#2355]
Hi guys. I've done a new and better vim plugin for Stylus, including proper and up-to-date syntax highlighting, indentation and autocomplete. The previous one https://github.com/wavded/vim-stylus was pretty poor and the repo is probably not alive anymore (last commit 2 years ago).

I just thought that you might want to check it out and probably change the link in the README file from  https://github.com/wavded/vim-stylus to https://github.com/iloginow/vim-stylus.

Thanks)

**Comment by vendethiel** [comment]
Feel free to submit a PR to the readme :).

**Comment by Panya** [comment]
Thanks for the PR.
