### ISSUE TITLE
Nested variable doesn't compile without colons

### ISSUE THREAD

**Issue by Yska** [stylus/stylus#2357]
Why doesn’t it compile without colons? If I have more than one call to nested variable it throws an error.
[Doesn't compile](http://stylus-lang.com/try.html#?code=%24ui%20%3D%20%7B%0A%20colors%3A%20%7B%0A%20%20%20%20blue%3A%20red%0A%20%7D%0A%7D%0A%0A.foo%0A%20%20color%20%24ui.colors.blue%0A%0A.foo1%0A%20%20color%3A%20%24ui.colors.blue)
[It is compile](http://stylus-lang.com/try.html#?code=%24ui%20%3D%20%7B%0A%20colors%3A%20%7B%0A%20%20%20%20blue%3A%20green%0A%20%7D%0A%7D%0A%0A.foo%0A%20%20color%3A%20%24ui.colors.blue%0A%0A.foo1%0A%20%20color%3A%20%24ui.colors.blue)

**Comment by vendethiel** [comment]
Using colon it is considered too ambiguous:

```
color .a.b.c
// could mean
color.a.b.c { }
//as in <color class="a b c"></color>
```

see https://github.com/stylus/stylus/issues/1405#issuecomment-36175169

**Comment by Yska** [comment]
Thanks @vendethiel
