### ISSUE TITLE
Missing styles when compiled

### ISSUE THREAD

**Issue by wickywills** [stylus/stylus#2366]
I have a bit of an odd issue with stylus and I can't work out what is going on. If you take a look at the stylus snippet below, when `bottom 0` is added, the height from the below doesn't get compiled into CSS. Remove `bottom 0` and it works fine, unfortunately I need `bottom 0` in this case:

**Stylus**
	
```
    &__text-mask
    		span
    			display block
    			position absolute
    			z-index 10
    			left 0
    			right 0
    			height 18px
                        bottom 0
    			background rgba(255,0,0,.5)
```
**Resulting CSS**
```
    .bioink-carousel__text-mask span {
        display: block;
        position: absolute;
        z-index: 10;
        left: 0;
        right: 0;
        background: rgba(255,0,0,0.5);
```
I have also recreated this behaviour in a [Codepen][1]. Am I missing something here? I have no errors in the console when compiling. I also notice that if you move `bottom 0` to a different line, other styles get missed. Very odd.

  [1]: https://codepen.io/wickywills/pen/eMOPzm

**Comment by pakastin** [comment]
You found out the issue?

**Comment by wickywills** [comment]
Yes, it was a whitespace issue - re-tabbing the styles solved my problem

**Comment by pakastin** [comment]
Glad it figured out! 🙂
