### ISSUE TITLE
Is there any way to get a imports list?

### ISSUE THREAD

**Issue by Gcaufy** [stylus/stylus#2368]
in stylus, if my styl file imports several files, like
```
@import 'a';
@import 'b';
@import 'c';
```

How can I get the dependences list?

in Stylus render methods, it only returns a css string.
https://github.com/stylus/stylus/blob/69072469471732059bdafe4126a99eaedbb80ef0/lib/renderer.js#L114

I aslo checked Less and Sass, It allows easily to get the AST and import dependences from the render result.

**Comment by Panya** [comment]
http://stylus-lang.com/docs/js.html#deps
