### ISSUE TITLE
This relative module was not found:  * ./attr(data-avatar ...

### ISSUE THREAD

**Issue by BrickCarvingArtist** [stylus/stylus#2369]
in html  
```html
<div data-avatar="a.png"></div>
```
in stylus  
```stylus
background-image url(attr(data-avatar))
```

and I got this error below:  
```bash
This relative module was not found:  * ./attr(data-avatar ...  
```
It seems like stylus treat `attr` as a build-in function.

then I tried build-in function `unquote` or build-in function `join` to wrap them,
and it didn't work and threw this error again...

can somebody help me, thx!

**Comment by Panya** [comment]
Cannot reproduce. See http://stylus-lang.com/try.html#?code=body%0A%20%20background-image%20url(attr(data-avatar)). Seems like this bug is not related to Stylus.
