### ISSUE TITLE
Error in calculation result.

### ISSUE THREAD

**Issue by MartDSam** [stylus/stylus#2373]
I want to do the following calculation:
`div{
	left: ((100% - 1230px) / 2);
}`

result:
`div{
    left: -565%;
}`

The correct would be:
`div{
    left: calc(50% - 615px);
}`
or

`div{
   left: 336.5px;
}`

If I use as in the example below everything works correctly:
`div{
	left: calc((100% - 1230px) / 2);
}`

**Comment by Panya** [comment]
You should use `calc` in this case.
