### ISSUE TITLE
Is there a way for self reference a hash?

### ISSUE THREAD

**Issue by dlasagno** [stylus/stylus#2376]
I was writing a hash, and I realized that it would be cool to self reference a hash like whit **this** keyword in JavaScript objects:

```javascript
foo = {
  bar: 12,
  baz: this.bar + 4
}
```

Is there anyway to do it in Stylus?

**Comment by atilkan** [comment]
@dlasagno Can you close the issue if the answer is ok?

**Comment by frantisekhanzlikbl** [comment]
Ok, it doesn't work in JavaScript but could it be perhaps implemented in stylus?

I have tons if variables in form
`componentA-someBox-padding-x`
I tried to convert them to hashes for easier organization but then I hit the issue that I can't refer to other values in the same hash like:
```stylus
componentA = {
    someBox: {
        padding: {
            all: 2em
            x: componentA.someBox.padding.all
            y: componentA.someBox.padding.all
            left: componentA.someBox.padding.x
            right: componentA.someBox.padding.x
            top: componentA.someBox.padding.y
            bottom: componentA.someBox.padding.y
        }
    }
}
```
Which would make it easy to maintain and eventually change any of the paddings independently in the future.
