### ISSUE TITLE
Feature request: Export css that matches a certain media query.

### ISSUE THREAD

**Issue by CarlosCotaCastro** [stylus/stylus#2381]
Hello,

i'm currently splitting up declarations for a project, so that i can use 
`<link async rel="stylesheet" href="desktop.css"  media="screen and (min-width: 1025px)" type="text/css" />`
`<link async rel="stylesheet" href="tablet.css"  media="screen and (max-width: 1024px)" type="text/css" />`

A much nicer way to achieve that, would be, that i could add in the console a stylus parameter, that creates that certain kind of css-files from the existing declarations.

This is just an idea.

Thank you for your great work!

**Comment by Panya** [comment]
Sorry, but this is out of the scope of Stylus. Use build systems like gulp, webpack etc.
