### ISSUE TITLE
Screen protector recommendation for my stylus ?

### ISSUE THREAD

**Issue by MEKOtech** [stylus/stylus#2382]
Hello all,

I'm going to buy a capacitive stylus by Asin: **[B00RWHGVDO](https://goo.gl/FL3mpC)** on Amazon US and I would like to hear your advice regarding the screen protector I should buy for it.

I always use a screen protector on my touch devices: I got Belkin MatteScreen on an iPad and HTC's glossy one on the HTC One mini. I may not use a sleeve, but I would always use a screen protector on a portable device, especially if it is designed to be scrubbed with a stylus.

I think I would go for a matte one for my stylus. Which one would you recommend? I'm not doing this wrong, screen protectors do work with a pressure-sensitive screen, don't they?

Any help ?

**Comment by vendethiel** [comment]
Wrong repo. Read the description.
