### ISSUE TITLE
Please update Source Map version

### ISSUE THREAD

**Issue by nothingismagick** [stylus/stylus#2386]
We are concerned that the source-map you are depending on is a VERY outdated version. Would you consider releasing a small point release to npm ASAP that updates source-map to 0.6.1 at least?

In order to make sure that it worked, I removed the source-map module from /node_modules/stylus/node_modules and replaced it with a less stale version (0.6.1) with a file-system copy-paste.

We are tracking the issue here:
https://github.com/quasarframework/quasar-cli/issues/122

**Comment by iChenLei** [comment]
Latest verison use `   "source-map": "^0.7.3"`, so close this issue.
