### ISSUE TITLE
Is the project abandoned?

### ISSUE THREAD

**Issue by yavorski** [stylus/stylus#2389]
Is the project abandoned?
Last release published to `npm` is 2 years ago, to be exact on on `Apr 28, 2016`?
Don't get me wrong here.
I love stylus and it is my preferred choice of preprocessor.
I am still using stylus for work and personal projects and I would love to hear that is not abandoned.

**Comment by Panya** [comment]
See https://github.com/stylus/stylus/issues/2282

**Comment by yavorski** [comment]
10x
