### ISSUE TITLE
grid-template with repeat function compile error

### ISSUE THREAD

**Issue by dreamfliper** [stylus/stylus#2392]
```stylus
grid-template repeat(8, 120px) / repeat(20, 100px)
```
compile this will get ` expected ")", got "newline"`
I need to manually excape `/` with `\/`
```stylus
grid-template repeat(8, 120px) \/ repeat(20, 100px)
// this works fine
```

**Comment by Berckan** [comment]
I am getting the same problem, the brackets `[` or `]` on `grid-template-columns` or `grid-template-rows`  aren't allowing the compiling process.

**Comment by atilkan** [comment]
See https://github.com/stylus/stylus/issues/2306

**Comment by iChenLei** [comment]
duplicated https://github.com/stylus/stylus/issues/2306
