### ISSUE TITLE
Error 500 while trying to install the style from within the extension

### ISSUE THREAD

**Issue by VladimirDev93** [stylus/stylus#2396]
This happens on every site, on every style. I need to go to the userstyles site in order to install the style.

![issue](https://user-images.githubusercontent.com/12301022/42338073-f7b6bfc6-8088-11e8-9f68-27ccc3d8d255.png)

**Comment by Panya** [comment]
Wrong repo. See https://github.com/openstyles/stylus

**Comment by VladimirDev93** [comment]
Whops, haha, sorry, my bad.

**Comment by VladimirDev93** [comment]
Whops, haha, sorry my bad.
