### ISSUE TITLE
Bug: dotted hash getter is not allowed as value without colon

### ISSUE THREAD

**Issue by yukulele** [stylus/stylus#2397]
Example:
```stylus
palette = {
    background: black
    text: white
}

main
    color palette[text]   // works
    color: palette.text   // works
    color palette.text    // doesn't work
```

**Comment by vendethiel** [comment]
Please search for the 5-10 duplicates + the docs about this

**Comment by yukulele** [comment]
@vendethiel nothing found about this in doc.

**Comment by yukulele** [comment]
@vendethiel can you get links ?

**Comment by vendethiel** [comment]
#2357 #2336 #2239 #2208 #2054 #2016 #2010 #1920 #1888 #1738 #1713 #1680 #1644 #1405 
Will these do or do you need more help to search?
