### ISSUE TITLE
Block mixins parameter

### ISSUE THREAD

**Issue by gorriecoe** [stylus/stylus#2403]
Is it possible to pass variables to a block in a mixin interpolation?

```
foo()
  for row in 1 2 3 4 5
    .bar-{row}
      {block}

+foo()
  width: {row}%
```
Expect output
```
.bar-1
  width: 1%
.bar-2
  width: 2%
...
.bar-5
  width: 5%
```
Actual output
```
.bar-
  width: %
```

In the basic example above I would expect foo to loop though rows with the value of row to be accessible from block similar to sass.

**Comment by atilkan** [comment]
row is out of scope. 
```
+foo()
  width: {row}%
```
But what you are trying to do may not be possible. I would go like this.
```
foo()
  .bar
    {block}

    
for row in (1..5)    
  +foo()
    width: unit(row, "px")
```

**Comment by atilkan** [comment]
@gorriecoe Why did yo close? Is it solved.
