### ISSUE TITLE
https://stylus-lang.com/ certificate error

### ISSUE THREAD

**Issue by Munter** [stylus/stylus#2405]
Visiting https://stylus-lang.com/  results in a certificate error. It would be good to get this fixed and redirect all http traffic to the https equivalent

![image](https://user-images.githubusercontent.com/331790/43194672-3c209586-9003-11e8-991b-be1fed604dbc.png)

**Comment by pakastin** [comment]
[Cloudflare](https://cloudflare.com/) could be helpful here.. 🌤

**Comment by iChenLei** [comment]
solved.
