### ISSUE TITLE
'imports' couldn't be set as a option

### ISSUE THREAD

**Issue by fengxinming** [stylus/stylus#2411]
```javascript
function Renderer(str, options) {
  options = options || {};
  options.globals = options.globals || {};
  options.functions = options.functions || {};
  options.use = options.use || [];
  options.use = Array.isArray(options.use) ? options.use : [options.use];
  options.imports = [join(__dirname, 'functions')];
  options.paths = options.paths || [];
  options.filename = options.filename || 'stylus';
  options.Evaluator = options.Evaluator || Evaluator;
  this.options = options;
  this.str = str;
  this.events = events;
};

```

We couldn't set commons functions of us as global functions

**Comment by atilkan** [comment]
What is this file for?

**Comment by fengxinming** [comment]
@atilkan I meant the `Renderer.js` when you use `stylus.render(str, options)`, I am gonna my functions and mixins in context, please support `options.imports` instead of `stylus(str).import('mixins/vendor')`, I am not sure if you understand me

**Comment by fengxinming** [comment]
@atilkan Please merge that branch, I have fixed this issue

**Comment by atilkan** [comment]
I am not core member. Dont worry they will see your commit.
