### ISSUE TITLE
Stylus parser will parse image path from 'not.png'  to  'false'

### ISSUE THREAD

**Issue by CommanderXL** [stylus/stylus#2418]
I use stylus in my vue project where I load the not.png in the App.vue file.During the webpack compiler progress,it occur to errors.The stylus parser parse the `background url(./assets/not.png)` to `background url(./assets/falsepng)`. So webpack can't find the image.

```javascript
// App.vue

<template>
  <div id="app">
    this is app page
  </div>
</template>

<script>
export default {
  name: 'app'
}
</script>
<style lang="stylus">
#app
  font-family 'Avenir', Helvetica, Arial, sans-serif
  -webkit-font-smoothing antialiased
  -moz-osx-font-smoothing grayscale
  text-align center
  color #2c3e50
  margin-top 60px
  background url(./assets/not.png)
</style>
```
Well, I try to debug the source code, I seems that  parser.js in stylus handle this case wrong.

**Comment by Panya** [comment]
'not' is built-in operator. Use quotes in this case (it's a best practice in Stylus):
```styl
#app
  font-family 'Avenir', Helvetica, Arial, sans-serif
  -webkit-font-smoothing antialiased
  -moz-osx-font-smoothing grayscale
  text-align center
  color #2c3e50
  margin-top 60px
  background url('./assets/not.png')
```
