### ISSUE TITLE
Can't use "for-" in variable or mixin name

### ISSUE THREAD

**Issue by dcastil** [stylus/stylus#2422]
Using any of these doesn't work because the compiler thinks I want to use a for-loop.

```styl
// doesn't work with variable
for-something = 5

// doesn't work with mixin
for-tablet-portrait-up()
  @media (min-width: 600px)
    {block}
```

Syntactically it would make more sense to indicate a for-loop with `for` followed by a space character and treat `for-` followed by other characters as a variable name. Also the errors above wouldn't occur then.

stylus v0.54.5
node v10.11.0
macOS Mojave v10.14.0

**Comment by atilkan** [comment]
@dcastil 
Here is the source to capture keywords. It should be updated.
https://github.com/stylus/stylus/blob/57e260d613d4694b00a0d3d825d7fcfe5210bf2c/lib/lexer.js#L433

Tweaked the regex a little. The result:
https://regexr.com/48pfo

I can't merge this even if it works, i don't trust myself yet.

**Comment by vendethiel** [comment]
that `[ \t]*` is certainly not doing anything useful...
