### ISSUE TITLE
Unexpected result of color 'orange'

### ISSUE THREAD

**Issue by zx69** [stylus/stylus#2423]
Hello, I have met a weird problem when I do this :
```
c-primary = #409EFF
c-success = #67C23A
c-warning = #E6A23C
c-danger = #F56C6C
c-info = #909399
c-orange = #FD9200
c-grey-1 = #E6E6E6
c-grey-2 = #C0C4CC

colors = primary success warning danger info orange

for type in colors
  .text-{type}
    color: c- + type
```
Everything is OK until I add `orange`into colors array.  The error message is :
```
./src/style/main.styl (./node_modules/css-loader??ref--11-oneOf-3-1!./node_modules/postcss-loader/lib??ref--11-oneOf-3-2!./node_modules/stylus-loader??ref--11-oneOf-3-3!./src/style/main.styl)
Module build failed (from ./node_modules/stylus-loader/index.js):
CoercionError: D:\work\forklift\src\style\common.styl:20:16
   18| for type in colors
   19|   .text-{type}
   20|     color c- + type
----------------------^
   21| 
   22| .text-center
   23|   text-align center

cannot coerce #ffa500 to ident
    at ".text-" (D:\work\forklift\src\style\common.styl:19:19)
```
The error message is complicated, I never use `#ffa500` in my whole project at all. 

I had tried to delete 'orange' from the colors array, or change other name, like `orang` / `corange`. 
Then the error fixed and the programe running correctly.

I also try it in the [stylus-online-test-tools](http://stylus-lang.com/try.html) , and get the similar result. no any result print out at all when I use `orange`,  and print out correctly  when using `orang`. You can try to change color name to `orange` by yourself at [reproduction link](http://stylus-lang.com/try.html#?code=c-primary%20%3D%20%23409EFF%0Ac-success%20%3D%20%2367C23A%0Ac-warning%20%3D%20%23E6A23C%0Ac-danger%20%3D%20%23F56C6C%0Ac-info%20%3D%20%23909399%0Ac-orang%20%3D%20%23FD9200%0Ac-grey-1%20%3D%20%23E6E6E6%0Ac-grey-2%20%3D%20%23C0C4CC%0A%0Acolors%20%3D%20primary%20success%20warning%20danger%20info%20orang%0A%0Afor%20type%20in%20colors%0A%20%20.text-%7Btype%7D%0A%20%20%20%20color%3A%20c-%20%2B%20type)

Is `orange` a keyword for Stylus ? Thank you.

**Comment by futekov** [comment]
Stylus does that with keywords that are color names. The same thing on your link happens with black, blue, green, red, etc.
The easiest way around it is to quote the word that contains a named color (or quote all of them so the code looks nicer).

**Comment by zx69** [comment]
Yes, It works. Thank you very much

**Comment by Denis535** [comment]
> Stylus does that with keywords that are color names. The same thing on your link happens with black, blue, green, red, etc. The easiest way around it is to quote the word that contains a named color (or quote all of them so the code looks nicer).

This is the most ill-conceived part of the stylus. It would be cool if I could disable this behavior.
