### ISSUE TITLE
How i get the transform css of perspective and rotateX

### ISSUE THREAD

**Issue by IgnacioGans** [stylus/stylus#2430]
Not working just tiping:
      transform perspective(45deg) rotateX(45deg)

I do some research for internet and i get this snippet but not work the mentioned code before.
How i do this animation css --->transform perspective(45deg) rotateX(45deg)

apreciatte, the info, Ty! 

RESOURCES: 
transform-rotateX(value)
  -webkit-transform: rotateX(value)
  -moz-transform: rotateX(value)
  -ms-transform: rotateX(value)
  -o-transform: rotateX(value)
  transform: rotateX(value)

perspective(value)
  -webkit-perspective: value
  -moz-perspective: value
  -ms-perspective: value
  -o-perspective: value
  perspective: value

**Comment by pakastin** [comment]
Well, if you want auto prefixing, just use [nib](http://stylus.github.io/nib/).

What's your other question?

**Comment by IgnacioGans** [comment]
Awesome, Pakastin. 
Exactly what I need to know. 
Thanks!
Note: sorry if I don't clarify the question.

**Comment by pakastin** [comment]
Perfect, glad that figured out! 🎉
