### ISSUE TITLE
BUG: Turn all styles off doesn't work properly

### ISSUE THREAD

**Issue by 2E0PGS** [stylus/stylus#2431]
Hi,

The feature "Turn all styles off" doesn't work properly. I see some CSS still being loaded.

Ways to reproduce

1. Ensure you have Stylus themes installed for the website you test this on.
2. Have [DarkReader](https://github.com/darkreader/darkreader) installed. 
3. Check the "Turn all styles off" box in Stylus.  
4. Notice it loading both CSS. 

If you however disable Stylus all together in Chromes manage extensions it doesn't occur.

**Comment by Panya** [comment]
Wrong repository. See https://github.com/openstyles/stylus.
