### ISSUE TITLE
Import CSS file

### ISSUE THREAD

**Issue by cup** [stylus/stylus#2432]
This addon seems to have no way to import a CSS file - unlike xStyle

this makes it difficult to import styles for multiple sites if you have them as separate CSS files

**Comment by pakastin** [comment]
Just use `@import`?
http://stylus-lang.com/docs/import.html

**Comment by cup** [comment]
@pakastin can you please reopen this

as you comment does not answer the question of how to import a CSS file

as in the addon would have you choose a CSS file - then import it

**Comment by pakastin** [comment]
Sorry, I don't quite get what you mean – could you clarify?

**Comment by cup** [comment]
@pakastin its pretty simple?

before installing this addon - image having several CSS files with styles for different websites

now you want to import those files into the addon

with current situation you have to copy paste each one

it seems you are suggesting just make a master CSS that imports the rest

however that still doesnt solve the problem of having to copy paste "something" into the addon - rather than being able to choose CSS file or files to import

**Comment by cup** [comment]
@pakastin no - the interface has no option for importing CSS - the only import option works with just JSON

>![](https://user-images.githubusercontent.com/926619/48023137-8b6a8c00-e102-11e8-9f5b-f9ec375b8150.png)

**Comment by pakastin** [comment]
What is that?

**Comment by vendethiel** [comment]
They weren’t talking about stylus-lang
