### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by BridgeAR** [stylus/stylus#2436]
@Panya @pakastin it would be great if you could release a new version. The current one has some flaws which also show up in the tests. This breaks the Node.js https://github.com/nodejs/citgm tests.

Please also consider merging https://github.com/stylus/stylus/pull/2424 as it fixes a deprecation.

**Comment by rlam3** [comment]
any update on this?

**Comment by vtimofeev** [comment]
Created new release https://github.com/vtimofeev/stylus/releases/tag/0.55.0

**Comment by BridgeAR** [comment]
@vtimofeev you did that with a fork and it seems like you do not have permissions for the npm package. So this does not help but thanks a lot nevertheless.

**Comment by vtimofeev** [comment]
@BridgeAR 

Yes you need some workaround to use it: 

If you use it in IDE you need install it globally:

```
npm i https://github.com/vtimofeev/stylus.git -g
```

or local
```
npm i https://github.com/vtimofeev/stylus.git 
```

or edit your package.json when 'npm i'
```
{
"stylus": "git+https://github.com/stylus/stylus.git"
}
```

**Comment by vtimofeev** [comment]
Or if you use strict version:
```
npm i https://github.com/vtimofeev/stylus.git#0.55.0
```

**Comment by BridgeAR** [comment]
@vtimofeev it is not about a work around. CITGM won't use a fork.

**Comment by BridgeAR** [comment]
@xdan I saw that you became a new maintainer. Do you already have a timeline for a new release?

**Comment by gengjiawen** [comment]
@xdan Can you help on this ? Thanks.

**Comment by atilkan** [comment]
There is a new release!

**Comment by iChenLei** [comment]
closed via https://github.com/stylus/stylus/pull/2424
