### ISSUE TITLE
Give [stylus-iframe] for Firefox?

### ISSUE THREAD

**Issue by ndaesik** [stylus/stylus#2437]
I don't know what is `[stylus-iframe]` for nor why it only has on Chrome but not Firefox.

Chrome version on stylus has [stylus-iframe] attribution on html that inside of iframe.
That is really useful as it's not possible to select the html that inside of iframe with pure CSS such as `iframe>html`.
I attempting to give background image only on root html but not on iframe html. however it's not compatible with Firefox as the attribution is not exist on Firefox.
I hope give the attribution on Firefox as well.
Thank you.

**Comment by vendethiel** [comment]
Wrong "stylus".
