### ISSUE TITLE
hsl converted to hex automaticaly, why?

### ISSUE THREAD

**Issue by alekspetrov** [stylus/stylus#2438]
Hi, i want to use hsl colors with css variables, but after compiling it returns hex value, can't find how to prevent it. 

input:
`:root {
--my-color: hsl(253, 26%, 7%);
}`
return:
`
:root {
--my-color: #0f0d16;
}
`
Please, let me know how to disable this behavior

**Comment by atilkan** [comment]
Can be done with css literals.
http://stylus-lang.com/docs/literal.html

**Comment by atilkan** [comment]
@alekspetrov Close the issue if you got it.

**Comment by alekspetrov** [comment]
> @alekspetrov Close the issue if you got it.

Ssory, but I'm not. I don't understand why the standard CSS feature have to be implemented over literals or so. Documentation for css literals if not clear for me. Any way, find a solution exclude stylus from the project. Thanks for response.

**Comment by atilkan** [comment]
@alekspetrov It should be removed from BIFs. For now there is no one to do it.

**Comment by scriptura** [comment]
hsl(), min(), max()... It's starting to cause a lot of compatibility problems with modern CSS...
