### ISSUE TITLE
mix function does not accept floats as 3rd parameter

### ISSUE THREAD

**Issue by y-nk** [stylus/stylus#2439]
it's ok to do `mix(#000, #fff, 50%)` but it's not to do `mix($blue, $red, 75.5%)`, and i can't figure out why.

**Comment by atilkan** [comment]
@y-nk I have not see this usage before. Can you point me the documentation about it?

**Comment by atilkan** [comment]
@y-nk It works for me. Can you share you full code?

**Comment by y-nk** [comment]
@atilkan here's a minimal repo with latest version : http://stylus-lang.com/try.html#?code=mix(%23000%2C%20%23fff%2C%2050%25)%0Amix(%23000%2C%20%23fff%2C%2099.99%25)

**Comment by atilkan** [comment]
Could it be this?
```
mix(color1, color2, weight = 50%)   
  unless weight in 0..100   
    error("Weight must be between 0% and 100%")
```
Anyways you can't figure out if you don't check source code. Wondering doesn't help. 
Just avoid using it with decimal number.

**Comment by y-nk** [comment]
@atilkan indeed, `in 0..100` sounds about it. wouldn't `unless 0 <= weight && weight <= 100` solve it ? i can do a PR if you feel like.

**Comment by atilkan** [comment]
@y-nk  I am no core member but i would not recommend doing that. I am guessing; it won't be accepted. I don't think it ads too much to the table and numbers between 0..100 is enough, don't you think?
Only thing to do is documenting for uint requirement.

**Comment by y-nk** [comment]
@atilkan mhm, it depends on each use of the function. in my personal use, i'm converting mix percentages from scss mix function to maintain the same output ; in some cases i _need_ decimals, if not i'd output 1 bit more or less, and it'd break the css unit tests :/ (yeah, i know...)

On a side note, performance wise it would also count as a micro optimization. From reading `0..100` I expect it creates a range (array?) of 101 items and test with a `indexOf(value) !== -1`-ish fashion which is definitely slower than a float comparison with numeric operator...

but i do agree with you that it doesn't add "much".

**Comment by atilkan** [comment]
@y-nk Can you close the issue?
