### ISSUE TITLE
define a prefix for variables imported via json

### ISSUE THREAD

**Issue by MartinMuzatko** [stylus/stylus#2441]
Per convention, variables in stylus are defined using `$` (`$color-primary = '#ff0000'`). 
However, variables are also able to be defined without the dollar sign.
In a json file I have defined my colors without the prefix. (I use them in another place also)
I would like to be able to prefix my colors without putting them into a namespace.
Instead I would like to introduce the `prefix` option:

``` json
{
    "red": "#ff4422"
}
```

``` styl
json('./colors.json', {prefix: '$'})

body
    color $red
```

**Comment by atilkan** [comment]
There is something about prefix in source code. Give it a try.
<img width="342" alt="screen shot 2019-02-18 at 15 12 11" src="https://user-images.githubusercontent.com/1254613/52950269-a3071100-338f-11e9-92f8-949781ddae7f.png">

**Comment by manuelodelain** [comment]
@atilkan thank you! 
`json("../vars/breakpoints.json", false, '$');` works for me

**Comment by MartinMuzatko** [comment]
awesome! thank you so much :)
