### ISSUE TITLE
How to select associative array?

### ISSUE THREAD

**Issue by Venegrad** [stylus/stylus#2443]
Hi guys, im try to get values from array, and try everything but cant get top value of margins, is this possible?
```
tf_margins = {
    title_margins: {top: 1em, bottom: 0.7em},
    p_margins: (0.7em 0.7em),
    blocks_margins: (1.1em 1.1em)
}

h1, h2, h3, h4, h5
    margin-top tf_margins[title_margins][top]
```

**Comment by Panya** [comment]
See http://stylus-lang.com/try.html#?code=tf_margins%20%3D%20%7B%0A%20%20%20%20title_margins%3A%20%7Btop%3A%201em%2C%20bottom%3A%200.7em%7D%2C%0A%20%20%20%20p_margins%3A%20(0.7em%200.7em)%2C%0A%20%20%20%20blocks_margins%3A%20(1.1em%201.1em)%0A%7D%0A%0Ah1%2C%20h2%2C%20h3%2C%20h4%2C%20h5%0A%20%20%20%20margin-top%3A%20tf_margins%5Btitle_margins%5D%5Btop%5D
