### ISSUE TITLE
Is it possible to create scroll in generic animation mixin?

### ISSUE THREAD

**Issue by 2YY** [stylus/stylus#2446]
JavaScript:

    const show = entries => entries[0].isIntersecting ? entries[0].classList.remove('is-hidden') : null;
    const observer = new IntersectionObserver(show, {threshold:0});
    Array.from(document.querySelectorAll('.js-hidden')).forEach(element => observer.observe(element));

I want to play fade in animation when '.js-hidden' class are removed like below... but this code are not working:

HTML:

    <div class="my-component js-hidden is-hidden">
        <p class="text text-1">Hello</p>
        <p class="text text-2">World</p>
    </div>

Stylus:

    fadeIn(duration=1s, delay=0s) {
        opacity: 1;
        transition: opacity duration ease delay;
        &.is-hidden { // <- yeah, this is wrong... but, any ideas? I want to apply transition both element and pseudo element.
            opacity: 0;
        }
    }

    .my-component {
        .text,
        &::before,
        &::after {
            fadeIn();
        }
        .text-2 {
            transition-delay: .3s;
        }
        &::before {
            content: 'foo';
            transition-delay: .5s;
        }
        &::after {
            content: 'bar';
            transition-delay: .7s;
        }
    }

I want to apply transition both element and pseudo element. but I don’t know what should I do...

Thanks.

**Comment by 2YY** [comment]
And, if the fade in elements are more nested?

    <div class="my-component js-hidden is-hidden">
        <div class="wrapper-1">
            <div class="wrapper-2">
                <p class="text text-1">Hello</p>
                <p class="text text-2">World</p>
            </div>
        </div>
    </div>

**Comment by atilkan** [comment]
This is a css specific issue, you should ask this on stackoverflow. Put your code on codepen to get help.
Basicly you should set transition for the my-component. And close the issue after.

**Comment by 2YY** [comment]
I see.

Thanks for your reply.
