### ISSUE TITLE
How to "for" in reverse order?

### ISSUE THREAD

**Issue by Venegrad** [stylus/stylus#2447]
There was a problem when creating the grid, need to work the array in the reverse order, is it real?

```
grid_bpoint = {dlg: 1300, dmd: 1100, dsm: 1000, tlg: 900, tmd: 800, tsm: 700, mlg: 600, mmd: 500, msm: 400}

for index, key in grid_bpoint
  @media(max-width (key)px)
    .grid
      display block


for(var i = grid_bpoint.length;grid_bpoint > 0;i = i - 1)
  @media(min-width (key)px)
    .grid
      display block
```

**Comment by Venegrad** [comment]
Is it possible to create an array from the first array, only in reverse order, so that after reading it?

**Comment by Venegrad** [comment]
Solved
http://stylus-lang.com/try.html#?code=invert(arr)%0A%20a2%20%3D%20()%0A%20for%20i%20in%20arr%0A%20%20push(a2%2C%20pop(arr))%0A%20return%20a2%0A%0Arc%20%3D%201%202%203%204%205%0Afor%20i%2C%20key%20in%20rc%0A%20.div-%7Bi%7D%0A%20%20display%20block%0Afor%20i%2C%20key%20in%20invert(rc)%0A%20.div-%7Bi%7D%0A%20%20display%3A%20table

**Comment by atilkan** [comment]
@Venegrad Please close the issue!

**Comment by MoussaAdam** [comment]
@Venegrad close the issue please

**Comment by Denis535** [comment]
> Solved http://stylus-lang.com/try.html#?code=invert(arr)%0A%20a2%20%3D%20()%0A%20for%20i%20in%20arr%0A%20%20push(a2%2C%20pop(arr))%0A%20return%20a2%0A%0Arc%20%3D%201%202%203%204%205%0Afor%20i%2C%20key%20in%20rc%0A%20.div-%7Bi%7D%0A%20%20display%20block%0Afor%20i%2C%20key%20in%20invert(rc)%0A%20.div-%7Bi%7D%0A%20%20display%3A%20table

```
invert(array)
    result = ()
    for i in array
        result.append( array.pop() )
    result
```
