### ISSUE TITLE
Overriding a valid css property with mixins

### ISSUE THREAD

**Issue by marcwieland95** [stylus/stylus#2461]
Hey guys,

I just came across a very strange issue and I thought I'll report it here. I don't know if you aware of it or not.

I used SCSS for years and now migrated my basic styles over to Stylus. So I had a mixin called transition.

```
transition($timing = ".8s") {
	transition: all $timing ease;
}
```

Down the road I not always used this mixin, sometimes also third-party code or whatever.
The thing is that this code overrides the normal CSS transition property.

So this absolutly valid CSS property `transition: top .5s ease` was turned into the following `transition: all top ease`, which is for sure invalid and wouldn't apply a transition to any item.

Is this something you are aware of? And is there a way to fix it (I see some compatibilty issues there). Maybe it's just a bad practise which I stumbeled across when migrating working code to another syntax.

Cheers Marc

**Comment by Panya** [comment]
It's intended behaviour. See [transparent mixins](http://stylus-lang.com/docs/mixins.html).
