### ISSUE TITLE
Identifier 'x' has already been declared

### ISSUE THREAD

**Issue by Kein** [stylus/stylus#2466]
It is not a big deal but I'm getting this in console every time on startup:

> msg.js:1 Uncaught SyntaxError: Identifier 'msg' has already been declared at msg.js:1
> prefs.js:1 Uncaught SyntaxError: Identifier 'prefs' has already been declared at prefs.js:1
> apply.js:1 Uncaught SyntaxError: Identifier 'APPLY' has already been declared at apply.js:1

Using Chromium's 76 RobRich build from [here](https://chromium.woolyss.com/)

**Comment by Panya** [comment]
Wrong repository.

**Comment by Kein** [comment]
Oh wow, sorry, I messed up by picking first browser address bar entry.
