### ISSUE TITLE
grid-template-area not working

### ISSUE THREAD

**Issue by ninakaur** [stylus/stylus#2467]
Can anyone help me see why grid-template-area refuses to work?
It does not stretch any of the items across both columns.

HTML:

<!DOCTYPE html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial scale=1.0">
    <link rel="stylesheet" href="style2.css">
    <title></title>
  </head>
  <body>

    <div class="grid">
      <div>title</div>
      <div>header</div>
      <div>sidebar</div>
      <div>content</div>
      <div>footer</div>
    </div>

  </body>
</html>

CSS:
* {
  margin:0;
  padding:0;
}

.grid{
  display:grid;
  grid-template-columns:1fr 1fr;
  grid template-rows:1fr 1fr 1fr 1fr 1fr;
  grid-template-areas:
  "item1 ."
  "item1 item2"
  "item3 item3"
  "item4 item4"
  "item5 item5"
  ;
  grid-gap: 10px;
}

.title {
  grid-area: item1
}
.header {
  grid-area: item2;
}
.sidebar {
  grid-area: item3;
}
.content {
  grid-area: item4;
}
.footer {
  grid-area: item5;
}

.grid div:nth-child(even){
background-color: red;
}

.grid div:nth-child(odd){
background-color: green;
}

**Comment by Panya** [comment]
See #2293

**Comment by ninakaur** [comment]
> See #2293

Hi, i saw that one but this did still not fix my problem. when i validate the code it says 

Parse Error template-rows: 1fr 1fr 1fr 1fr 1fr

but i don't see what the problem is in that line.

**Comment by Panya** [comment]
@ninakaur you've missed `-` after grid in `grid-tempate-rows`. See http://stylus-lang.com/try.html#?code=*%20%7B%0A%20%20margin%3A0%3B%0A%20%20padding%3A0%3B%0A%7D%0A%0A.grid%20%7B%0A%20%20display%3Agrid%3B%0A%20%20grid-template-columns%3A1fr%201fr%3B%0A%20%20grid-template-rows%3A1fr%201fr%201fr%201fr%201fr%3B%0A%20%20grid-template-areas%3A%5C%0A%20%20%20%20%22item1%20.%22%5C%0A%20%20%20%20%22item1%20item2%22%5C%0A%20%20%20%20%22item3%20item3%22%5C%0A%20%20%20%20%22item4%20item4%22%5C%0A%20%20%20%20%22item5%20item5%22%3B%0A%20%20grid-gap%3A%2010px%3B%0A%7D%0A%0A.title%20%7B%0A%20%20grid-area%3A%20item1%0A%7D%0A%0A.header%20%7B%0A%20%20grid-area%3A%20item2%3B%0A%7D%0A%0A.sidebar%20%7B%0A%20%20grid-area%3A%20item3%3B%0A%7D%0A%0A.content%20%7B%0A%20%20grid-area%3A%20item4%3B%0A%7D%0A%0A.footer%20%7B%0A%20%20grid-area%3A%20item5%3B%0A%7D%0A%0A.grid%20div%3Anth-child(even)%20%7B%0A%20%20background-color%3A%20red%3B%0A%7D%0A%0A.grid%20div%3Anth-child(odd)%20%7B%0A%20%20background-color%3A%20green%3B%0A%7D
