### ISSUE TITLE
Is it possible to make website resposive after you've already made it?

### ISSUE THREAD

**Issue by ninakaur** [stylus/stylus#2470]
I have this code for now but i am not sure hwo to make it responsive or if i even can make it responsive. As you can see by the code i am still relatively new to this so this problem is confusing the hell out of me, any suggestions..? 

<!DOCTYPE html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial scale=1.0">
    <link rel="stylesheet" href="style3.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <title></title>
  </head>
  <body>
    <div class="grid">
      <div class="item1"><img src="C:\Users\ninak\Desktop\Afsluttende projekt\billeder\logo2.jpg" alt="logo" height="300" width="506"><p>"Giv dit tøj nyt liv, og tjen kassen mens du hygger dig."</p></div>
      <div class="item2"><br><p>#Koncept<br>Vi kæmper hver dag for at gøre bæredygtig mode til det svedigste og verden et bedre sted. Vil elsker at få mails – så smid endelig et kys og klem vores vej, hvis I har lyst.</p></div>
      <div class="item3"><br><p>Book stand til næste marked!<br>På Veras kan kvinder og mænd altid sælge ud af garderoberne. Mændene må især gerne sælge ud på vores mandemarkeder og på vores interiør markeder må du også medbringe boligvarer.</p></div>
      <div class="item4"><br><br<br><br><a href="https://verasvintage.dk/market/koebenhavn/"target="_blank" class="button">Køb en stand</a><div class="logo1"><h1>veras</h1></div></div>
      <div class="item6"><div class="logo"><h1 style="text-align:center;">veras</h1></div></div>
      <div class="item7"><div class="logo"><h1>veras</h1></div></div>
      <div class="item8"><div class="logo"><h1>veras</h1></div></div>
      <div class="item9"><img src="C:\Users\ninak\Desktop\Afsluttende projekt\billeder\citat.jpg" alt="citat" height="300" width="506"></div>
      <div class="item10"><div class="logo"><h1 style="text-align:center;">veras</h1></div></div>
      <div class="item11"><img src="https://cdn1.verasvintage.dk/wp-content/uploads/2017/09/170923-vera-24-1800x1200.jpg" alt="image1" height="100%" width="100%"></div>
      <div class="item12"><img src="https://cdn1.verasvintage.dk/wp-content/uploads/2017/09/170923-vera-48-1800x1200.jpg" alt="image2" height="100%" width="100%"></div>
      <div class="item13"><div class="logo"><h1>veras</h1></div></div>
      <div class="item14"><img src="https://cdn.verasvintage.dk/wp-content/uploads/2017/11/IMG_0486-1800x1200.jpg" alt="image3" height="100%" width="100%"></div>
      <div class="item16"></div>
      <div class="item17"></div>
      <div class="item18"><img src="C:\Users\ninak\Desktop\Afsluttende projekt\billeder\pastel.jpeg" alt="image4" height="100%" width="100%"></div>
      <div class="item19"><img src="C:\Users\ninak\Desktop\Afsluttende projekt\billeder\noget.jpg" alt="image5" height="100%" width="100%"></div>

    </div>
    <div class="fixed-footer-grid-container">
        <div class="footer1">Facebook</div>
        <div class="footer2">Instagram</div>
        <div class="footer3">Bispeengen 15, 2000 Frederiksberg</div>
        <a href="https://www.facebook.com/VerasMarket/"target="_blank" class="social1"><i class="fab fa-facebook fa-4x"></i></a>
        <a href="https://www.instagram.com/verasvintagedk/"target="_blank" class="social2"><i class="fab fa-instagram fa-4x"></i></a>
        <i class="far fa-compass fa-4x"></i>
      </div>
    </div>
  </body>
</html>

 CSS

* {
  margin:0;
  padding:0;

  }

.grid{
  display:grid;
  grid-template-columns: 1fr 1fr 1fr;
  grid-template-rows: 1fr 1fr 1fr 1fr 1fr 1fr;
  grid-template-areas:
  "fill1 title fill2"
  "dato quote nyhed"
  "image4 stand image5"
  "galleri item9 item10"
  "item11 facebook item12"
  "item13 item14 insta"
  ;
  font-family: 'avenir next';
  font-size: 14px;

}
.grid{
grid-template-rows: 150px;

}

.item1 {
  grid-area: title;
  font-size: 30px;
  font-style: italic;
  text-align: center;
  height:300px;

}
.item16 {
  grid-area: fill1;
  height:100px;
  background-color: #ead2df;
  border-radius: 25px;

}
.item17 {
  grid-area: fill2;
  height:100px;
  background-color: #ead2df;
  border-radius: 25px;

}
.item18 {
  grid-area: image4;
  height: 300px;

}
.item19 {
  grid-area: image5;
  height:300px;
;
}
.item2 {
  grid-area: dato;
  font-size: 20px;
  text-align: center;
  height:300px;
  background-color: #ffe5c0;
  border-radius: 25px;
  line-height: 40px;

}
.item3 {
  grid-area: nyhed;
  font-size: 20px;
  text-align: center;
  height:300px;
  background-color: #ffe5c0;
  border-radius: 25px;
  line-height: 40px;

}
.item4 {
  grid-area: stand;
  height:300px;
  background-color: #ead2df;
  border-radius: 25px;

}
.button{
border: solid;
color: white;
background-color: #30104f;
padding: 30px 100px;
text-align: center;
text-decoration: none;
display: inline-block;
font-size:18px;
margin: 5px 1px;
cursor: pointer;
position: fixed;
left:40%;
border-radius: 25px;

}

.item6 {
  grid-area: galleri;
  height:300px;
  background-color: #ead2df;
  border-radius: 25px;

}

.item7 {
  grid-area: facebook;
  height:300px;
  background-color: #edb5d2;
  text-align: center;
  justify-items: center;
  border-radius: 25px;

}

.item8 {
  grid-area: insta;
  height:300px;
  background-color: #ead2df;
  text-align: center;
  justify-items: center;
  border-radius: 25px;

}

.item9 {
  grid-area: item9;
  height:300px;
}
.item10 {
  grid-area: item10;
  height:300px;
  background-color: #c8a8da;
  border-radius: 25px;

}
.item11 {
  grid-area: item11;
  height:300px;
}

.item12 {
  grid-area: item12;
  height:300px;
}
.item13 {
  grid-area: item13;
  height:290px;
  background-color: #c8a8da;
  border-radius: 25px;
  padding: 5px;
  color: white;
  text-align: center;

}
.logo {
  font-family: 'bell MT';
  color: white;
  font-size: 30px;
  margin-top: 20%;
  letter-spacing: 30px;
}
.logo1 {
  font-family: 'bell MT';
  color: white;
  font-size: 30px;
  margin-top: 70px;
  letter-spacing: 30px;
  text-align: center;
}

.item14 {
  grid-area: item14;
  height:300px;
}
.item15 {
  grid-area: quote;
  font-style: italic;
  text-align: center;
  font-size: 30px;
  width: 400px;

}

.fixed-footer-grid-container {
  position: relaive;
  bottom: 0;
  width: 100%;
  background-color: black;
  color: white;
  font-weight: bold;
  height: 150px;
  font-size: 25px;
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  grid-template-areas: "adresse linkfb linkinsta";
  align-items: center;
  justify-items: center;
  font-family: 'avenir next';
  font-size: 14px;
  font-style: bold;
}
.footer1 {
  grid-area: adresse;
}
.footer2 {
  grid-area: linkfb;
}
.footer3 {
  grid-area: linkinsta;
}
img {
  border-radius: 25px;
}
.social1 {
  color: white;
}
.social2 {
  color: white;
}

**Comment by vendethiel** [comment]
Wrong stylus repo.

**Comment by ninakaur** [comment]
> Wrong stylus repo.

What?
