### ISSUE TITLE
Unable to access parent list of selectors at respective index

### ISSUE THREAD

**Issue by armaneous** [stylus/stylus#2472]
So, in keeping strictly with DRY, I'm trying to minimize the footprint of a heavily repeated pattern. Namely, all heading tags (`h1..h6`) share the same characteristics save for `font-size` and possibly `font-weight`. The syntax that seemed obvious given the language, but turned out not to be, resulted in this attempt:

```
headings = {
  h1: 200%,
  h2: 170%,
  h3: 150%,
  h4: 130%,
  h5: 110%,
  h6: 100%
}

size-heading(type)
  font-size headings[type]

h1, h2, h3, h4, h5, h6
  size-heading(selector())
```

It seems that `selector()` is _not_ the respective selector for which this style will be applied (i.e. only 'h2') but instead the *set* of selectors for which the style will be applied (i.e. `h1, h2, ..., h6`).

I cannot find any parameter or value to pass in to `selector()` to get the respective selector so I'm not sure if this is currently possible. Additionally, trying to factor in `font-weight` that would change for most, if there were a `^[N]`-like syntax it would really help to do something like this:
```
...
h1, h2, h3, h4, h5, h6
  size-heading(selector())
  font-weight 500
  ^[0] // Only h1 should be different
    font-weight 800
```

Am I missing something for any of these? Is this possible? I'm probably missing something from the docs in trying to do this.

**Comment by armaneous** [comment]
Upon further reading and experimenting, it seems it's possible this way:
```
headings = {
  h1: 200%,
  h2: 170%,
  h3: 150%,
  h4: 130%,
  h5: 110%,
  h6: 100%
}

style-heading(type)
  if type is 'h1'
    font-weight 800
  else
    font-weight 500
    margin-bottom 5px
  font-size headings[type]

for h in h1 h2 h3 h4 h5 h6
  {h}
    style-heading(selector())
```

It does, however, result in generated CSS looking like this:
```
h1 {
  font-weight: 800;
  font-size: 200%;
}
h2 {
  font-weight: 500;
  margin-bottom: 5px;
  font-size: 170%;
}
...
h6 {
  font-weight: 500;
  margin-bottom: 5px;
  font-size: 100%;
}
```

**Comment by atilkan** [comment]
Can you point the problem? It looks ok to me.

**Comment by armaneous** [comment]
I guess there isn't a problem. The approach in my initial post seemed more intuitive from a programmatic perspective, but it _is_ solvable using a different approach which I highlighted in my second post.
