### ISSUE TITLE
When do you plan to release a version to npm to solve these issues?

### ISSUE THREAD

**Issue by fengxinming** [stylus/stylus#2478]
The last release was three years ago, I wish your team release a new version as soon as possible to fix those issues.

**Comment by IceApriler** [comment]
Emm, maybe they forgot the password of NPM.

**Comment by atilkan** [comment]
There is a new release!

**Comment by fengxinming** [comment]
@atilkan Thanks!

**Comment by IceApriler** [comment]
@atilkan Thanks, super Plus enjoy!

**Comment by MoussaAdam** [comment]
@fengxinming maybe close the issue?
