### ISSUE TITLE
This relative module was not found

### ISSUE THREAD

**Issue by Longgererer** [stylus/stylus#2480]
I install stylus in global

```dash
npm i stylus -g
```

require it and use js api

```dash
async function compileStylus(code) {
  const stylus = await require('stylus')
  return new Promise((resolve, reject) => {
    stylus.render(code, { filename: 'foo.styl' }, (err, css) => {
      if (err) return reject(err)
      resolve(css)
    })
  })
}
```

but terminal report an error when I run it

```dash
This relative module was not found:

* ./lib-cov/stylus in ./node_modules/_stylus@0.54.5@stylus/index.js
```

I tried a lot of things but nothing worked

**Comment by atilkan** [comment]
Does it work without async/await

**Comment by Longgererer** [comment]
it's still not working, but I have new solution:

only import 'stylus.js'

```javascript
async function compileStylus(code) {
  await import('/static/js/stylus.js')
  return new Promise((resolve, reject) => {
    window.stylus.render(code, { filename: 'foo.styl' }, (err, css) => {
      if (err) return reject(err)
      resolve(css)
    })
  })
}
```

**Comment by EscapeB** [comment]
Same problem !
It seems that relative module is decided by process.env.STYLUS_COV in index.js
`module.exports = process.env.STYLUS_COV
  ? require('./lib-cov/stylus')
  : require('./lib/stylus');
`
I'm sure that i didn't set the STYLUS_COV.

**Comment by iChenLei** [comment]
Is still a issue now ?

**Comment by 0biWanKenobi** [comment]
> Is still a issue now ?

Yes. Something is setting `process.env.STYLUS_COV` and I have no idea why.

**Comment by iChenLei** [comment]
@0biWanKenobi Will remove `STYLUS_COV` in the next version, it's unused for a long time actually.

**Comment by ivands** [comment]
Same problem. But in vite.

**Comment by ivands** [comment]
Why does this error happen and why is there a lib-cov version of stylus?

**Comment by iChenLei** [comment]
@ivands Long Long ago, `STYLUS_COV ` is a process ENV for `code coverage` CI. I am current maintainer, I must say that there are so many legacy infra I need to understand, and then remove it or upgrade / replace.
