### ISSUE TITLE
Stylus 0.54.6 broke negation of property lookup

### ISSUE THREAD

**Issue by jduncanator** [stylus/stylus#2485]
In **`Stylus 0.54.5`** the following Stylus snippet:

```stylus
.test {
    margin-top: 20px;
    bottom: -@margin-top + 10px;
}
```
compiles to this:
```css
.test {
  margin-top: 20px;
  bottom: -10px;
}
```

In **`Stylus 0.54.6`** (and later versions), that same snippet is now broken, and compiles to this:

```css
.test {
  margin-top: 20px;
  bottom: -@margin-top10px;
}
```

This seems to only occur when the property being looked up is directly prepended with a negation with no space between, as the following snippet works correctly in both **`0.54.5`** and **`0.54.6`**:

```stylus
.test {
    margin-top: 20px;
    bottom: - @margin-top + 10px;
}
```

As you can imagine, this is causing a lot of breakage in our continuously integrated projects, and is making it difficult to reproduce builds, as our build system have for the longest of time used the latest version of Stylus, whilst our developers use whatever Stylus version they have on their machine.

We have hundreds of projects we use Stylus across, and we are having to fix the Stylus version we install to 0.54.5 in our environment setup script. It would be nice to get this resolved quickly so we can avoid having to do this across too many of our projects.

**Comment by atilkan** [comment]
Can you test on 0.54.7

**Comment by jduncanator** [comment]
It's also broken on 0.54.7, sorry, I should have mentioned that initially.

**Comment by jduncanator** [comment]
Any update on this? Still breaking all our builds...

**Comment by jduncanator** [comment]
Still no action on fixing this breaking change?

**Comment by Cactusbone** [comment]
Trying to fix bug on my side. It seems linked to @apply handling in cf93670b03f4fd46b9530fb4ce035dc25626ab0e
