### ISSUE TITLE
infinite hourglass rotation on style import

### ISSUE THREAD

**Issue by astokes** [stylus/stylus#2488]
I'm attempting to rescue about 400 personal user styles from an old instance of Firefox 47.0 running on a different workstation.  On my new workstation I'm running Firefox 68.0.1.  (Both of these systems are FreeBSD-based, though I doubt this is pertinent.)  

I was able to access the sqlite file on the old system and use the User Style Extractor web page to create export_all_styles.json, which is 291 KiB, all in a single line of text (which is pretty horrible to debug). 

cat export_all_styles.json | python3.6 -m json.tool > all_styles_pretty.json
grep '"name"' all_styles_pretty.json | sort | less

This shows the the names of 400-odd familiar rules from the old system. The export to json appears to have worked perfectly.  

Then I go into the "manage" page on Firefox 61 and try to import this file. (Stylus was freshly installed today.) I've tried both the file picker and the drag and drop method. I've also tried the pretty version of the file. In every instance, after successfully invoking the import operation, I get the infinite pizza wheel that Steve Jobs made famous (which is rotating hourglass on this box at present). 

There is no other feedback about the operation whatsoever. I can click links on the stalled import page, and the page responds. I can also close the page and it kills immediately. I've not seen any evidence of a side-effect in Firefox 61 from an aborted import, so it appears that the import is changing *no* permanent state in my browser instance. 

The FAQ seems to suggest enabling layout.css.moz-document.content.enabled, which I did, to no positive effect on the next attempt.  

I've let the pizza wheel sit there and spin for 10 full minutes on my Xeon E5-1620. No joy.

**Comment by vendethiel** [comment]
Wrong repo

**Comment by astokes** [comment]
Sincere apologies from my forebrain gremlins for posting on the wrong repo. 

I tend to monkey around with low-value tasks (like configuring my desktop) only when my sleep disorder gets the better of me, and even though part of my brain seems to be functioning normally, I have no peripheral vision and boners like this are par for the course (which is why I wasn't doing something remunerative, because I become like a zombie with outstretched arms dead-set on stepping into a CLM). Happily, today I'm 500% wider awake. 

Please feel free to delete this entire bug thread. I have a copy to re-post on the correct repo (wish me luck) when next I return to low-value tasks, in some similarly erratic state of partial competence.
