### ISSUE TITLE
How to compare vw and px ?

### ISSUE THREAD

**Issue by Xiamer** [stylus/stylus#2507]
```stylus
box()
  if calc(100vw) > 768px
    background #f00
  else
    background #00f

.div
  box()
```

or 

```stylus
box()
  if 100vw> 768px
    background #f00
  else
    background #00f

.div
  box()
```

this result is error

**Comment by alexeyten** [comment]
I guess you have to use `@media`-queries

**Comment by MoussaAdam** [comment]
this is not css, this is stylus, it's a css **Preprocessor**, this mean it will compile the stylus code **on your computer** to a css code, then u will use the resulted CSS files on your website
  
CSS doesn't support mixins, functions, if-else statements, etc...
  
when u compile your stylus code,the stylus compiler will decide to write the code after the `if condition` or after the `else`, on your css file that will run on your clients computer, stylus doesn't know if `100vw > 768px` or not, bc `100vw` is different depending on the **V**iewpport **W**idth of the client, and stylus is not run by the client, it run only by you(**the developper**), the client only run the resulted CSS code, that --as-stated-above-- dont have an `if-else` statement, however it have a `@media screen` that can be used to change the style depending on the screen,

close the issue plz
