### ISSUE TITLE
Google Drive Export/Import Support

### ISSUE THREAD

**Issue by hassanila97** [stylus/stylus#2513]
### NOTE: This is only a question not really an issue.

I was wondering why there is no ability to backup/restore to/from Google Drive?
The only options are Dropbox and exporting/importing a .json file

I would love to make a pull request but I currently don't have time for it.

**Comment by vendethiel** [comment]
This is not the correct stylus repo.

**Comment by hassanila97** [comment]
> This is not the correct stylus repo.

Oh, my bad. Thaks for letting me know, closing.
