### ISSUE TITLE
Stylus can't find file @require'd from node_modules

### ISSUE THREAD

**Issue by phun-ky** [stylus/stylus#2514]
I have several stylus files, and they have some dependencies in node modules. The requirement is that the stylus files are to be consumed by gulp and webpack. Using this @require:

```stylus
@require '~@guybrush/color/src/color-variables.styl'
```
Yields:

```
failed to locate @require file ~@guybrush/color/src/color-variables.styl
```
With gulp-stylus

Removing the tilde fixes it, but then it breaks webpack..

Issue originally posted here: https://github.com/stevelacy/gulp-stylus/issues/200

**Comment by phun-ky** [comment]
Found out how I can skip using tilde (~) all together, with a config in webpack:

```javascript
{
  loader: "stylus-loader",
  options: {
    sourceMap: true,
    paths: ['node_modules/']
  }
}
```

Closing

**Comment by matthias-ccri** [comment]
From the CLI, this fixed it for me: `--include node_modules`
