### ISSUE TITLE
Stylus site is down

### ISSUE THREAD

**Issue by adrianofbiz** [stylus/stylus#2525]
Hello the site http://stylus-lang.com/ is down

Evidence
https://drive.google.com/file/d/1_36slVNiLGxGgE5xnTfC7CLqEObmEKnI/view?usp=sharing

**Comment by katabame** [comment]
I took a look with whois, seems domain were transfered to another registrar and the domain owner forgot to set CNAME record (for github pages).

Maybe should ref: https://github.com/stylus/stylus-lang.com/issues/25

whois:
```
Domain Name: STYLUS-LANG.COM
Registry Domain ID: 1902547507_DOMAIN_COM-VRSN
Registrar WHOIS Server: whois.tucows.com
Registrar URL: http://www.tucows.com
Updated Date: 2020-02-14T05:36:49Z
Creation Date: 2015-02-13T02:40:20Z
Registry Expiry Date: 2021-02-13T02:40:20Z
Registrar: Tucows Domains Inc.
Registrar IANA ID: 69
Registrar Abuse Contact Email:
Registrar Abuse Contact Phone:
Domain Status: clientHold https://icann.org/epp#clientHold
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
Domain Status: clientUpdateProhibited https://icann.org/epp#clientUpdateProhibited
Name Server: NS1.HOVER.COM
Name Server: NS2.HOVER.COM
DNSSEC: unsigned
URL of the ICANN Whois Inaccuracy Complaint Form: https://www.icann.org/wicf/
>>> Last update of whois database: 2020-02-15T03:58:55Z <<<
```

**Comment by natevw** [comment]
185.199.109.153 stylus-lang.com

**Comment by corysimmons** [comment]
Is it back up?

**Comment by natevw** [comment]
Looks like it from here!

**Comment by adrianofbiz** [comment]
Hi, it's working.

But I don't remember if before have the site have https, we have this alert in the browser.

Evidence
https://drive.google.com/file/d/1Tyh3C_Lkb7EPRyRWC9AoPkSt4toPMPPY/view?usp=sharing

Is not a problem for me, but I think this will pass a wrong impression about the site.

**Comment by corysimmons** [comment]
It's back up and https is fixed.
