### ISSUE TITLE
Working with Vanilla CSS variables

### ISSUE THREAD

**Issue by SonOfDiablo** [stylus/stylus#2526]
Hello,

I'm trying to figure out if it's possible to convert a Vanilla CSS variable to a Stylus variable.

I'm trying to write a stylesheet for Stylus (the Browser Extension used for userstyles/userCSS) that uses the variables from another stylesheet.

The variables are accessible, but they are Vanilla CSS variables (ex: --BackgroundColor: #000000;)

I want to use Stylus functions such as alpha() to change the values of these variables, but I can't figure out how to do that.

Is this even possible?

**Comment by markfswe** [comment]
This is not possible. You can't use css custom properties as stylus variables. Try to understand how stylus and other **preprocess**ors work

**Comment by markfswe** [comment]
@SonOfDiablo Please close this issue if everything is clear
