### ISSUE TITLE
fix security vulnerability: "mkdirp"

### ISSUE THREAD

**Issue by punund** [stylus/stylus#2528]
The package uses `mkdirp`:

    "mkdirp": "~0.5.x",

which depends on vulnerable version of `minimist`.

Please upgrade to latest mkdirp, which doesn't depend on `minimist`.

**Comment by jimmywarting** [comment]
or just drop it and depend on nodes mkdir instead?

**Comment by iChenLei** [comment]
closed https://github.com/stylus/stylus/commit/a1102a53e3fca4d531d9f962e8687c1f618a1e32
