### ISSUE TITLE
Possible to split string value to multiple rows?

### ISSUE THREAD

**Issue by TokugawaTakesi** [stylus/stylus#2537]
```
equalLeftAndRightBordersOverriding--errorDescription = "If you have specified '$LeftOrRightBordersEqualWidths' " + 
  "do not touch '$LeftBorderWidth' and '$RightBorderWidth'.";
```

causes:

```
Cannot read property 'lineno' of undefined
```

**Comment by futekov** [comment]
Yes, it's [possible](https://stylus-lang.com/try.html#?code=equalLeftAndRightBordersOverriding--errorDescription%20%3D%20%22If%20you%20have%20specified%20'%24LeftOrRightBordersEqualWidths'%20%5Cn%20do%20not%20touch%20'%24LeftBorderWidth'%20and%20'%24RightBorderWidth'.%22%0A%0A.selector%3Aafter%0A%20%20content%3A%20equalLeftAndRightBordersOverriding--errorDescription).

**Comment by TokugawaTakesi** [comment]
@slightlyfaulty Thank you for the solution! It works.

@futekov I am sorry about asked what I want not enough clearly.  I need to break the string literal (as Saul did), not value.
