### ISSUE TITLE
Can't use hex opacity with stylus variables

### ISSUE THREAD

**Issue by ZerdoX-x** [stylus/stylus#2540]
```styl
body
  $test = #aaaaaa
  color "%s1a" % $test /* hex opacity */
```
compiles to
```styl
body {
  color: #aaa1a;
}
```
which is not valid. How do I save original variable value?

https://drafts.csswg.org/css-color/#hex-notation

**Comment by slightlyfaulty** [comment]
Why use hex notation instead of just `rgba`? The alpha value is much more readable too.

```styl
body
  $test = #aaaaaa
  color rgba($test, .1)
```

If you really need to use alpha hex notation, I don't think Stylus supports this natively, but you can write a pretty quick mixin for it. E.g.

```styl
hexa(color, alpha)
  color = '' + alpha(color, 1)
  c = split('', color)
  if c[6] == null
    color = '#' + c[1] + c[1] + c[2] + c[2] + c[3] + c[3]
  return unquote(color + alpha)

body
  $test = #aaaaaa
  color hexa($test, 1a)
```

**Comment by ZerdoX-x** [comment]
Thanks. But why stylus minifies (optimizes?) variables? Why don't keep it as original?

**Comment by slightlyfaulty** [comment]
Because `#aaaaaa` isn't a string value. In Stylus it's an RGBA value. RGBA values always output in their simplest form:

`#aaaaaa` -> `#aaa`
`black` -> `#000`
etc.
