### ISSUE TITLE
New Patch Release is breaking builds across many other projects that depend on stylus

### ISSUE THREAD

**Issue by helloanoop** [stylus/stylus#2545]
Hi,

I just saw that a version 0.54.8 was released 4 days ago.
Many packages (gulp-stylus, brunch-stylus) depending on stylus 0.54.x are failing.
The changes from 0.54.7 to 0.54.8 looks really big https://github.com/stylus/stylus/compare/0.54.7...0.54.8 

Is this really a patch release?

**Comment by kaustubhn** [comment]
Hi,

Getting the build error after this release.

**Comment by helloanoop** [comment]
It seems the `mkdirp` version change from 0.5.x to 1.0.4 is causing the build failures on our system. https://github.com/stylus/stylus/compare/0.54.7...0.54.8#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R35

I will confirm more details soon.

**Comment by kaustubhn** [comment]
@anoopmd Is there a way to fix this in local build? any suggestion would help we have a release coming soom

Thanks in Advance.

**Comment by helloanoop** [comment]
A temporary solution is to explicitly point to stylus ver 0.54.7 in your package.json
```javascrpt
{
  "stylus": "0.54.7"
}
```

**Comment by rmullenix** [comment]
@anoopmd - that won't work if you're on an ancient nodeJS that predates package-lock.json and it's a subdependency of a package you're using.

the tilde in the package.json is supposed to mean _equivalent_ version.  It can't really be _equivalent_ if you jump your dependencies by a major version

**Comment by real-artswan** [comment]
I'm agree in sense that big changes should not be released as minor version update

**Comment by iChenLei** [comment]
Sorry for everyone, stylus lack maintenance last five years.
