### ISSUE TITLE
not working "embedurl" release 0.54.8

### ISSUE THREAD

**Issue by ricomen** [stylus/stylus#2546]
now is not working "embedurl"
@font-face
	font-family 'modul-icons'
	src embedurl('../fonts/icons/modul-icons.woff2'),
		embedurl('../fonts/icons/modul-icons.woff')
	font-weight normal
	font-style normal

**Comment by real-artswan** [comment]
Broken for images as well
it produces
`data:image/png;base64,77+9UE5HChoKAAAACklIRFIAAADvv70AAADvv70IBgAAAO+/ve+/vVo9AAAgAElEQVR477+977+9eXxdZ3Xvv73vv71d77+977+9Z++/vWDJtu+/vVHvv71nee+/ve+/vR3vv712BiDvv70QSO+/vUIS77...`
while correct one for the same image is
`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPoAAAD6CAYAAACI7Fo9AAAgAElEQVR4nOy9eXxdZ3Xv/V3P3mfQYMm25FGeZ3mejR3HdgYggRBIgkISpkALtEDH997et+...`
(both are shortened)

**Comment by alexbruno** [comment]
Yep, same for me!
I tried to update dependencies in my lib (https://www.npmjs.com/package/@jsweb/font-awesome-base64) today and this **v0.54.8** broke my build.
The CSS builds with invalid base64 data uri.
Downgrading to **v0.54.7** fix it.

**Comment by rahbari** [comment]
same here, embedurl is broken in 0.54.8.

**Comment by matheo** [comment]
covid killed `stylus` :(

**Comment by real-artswan** [comment]
Is it possible to release this fix soon? Version 0.54.7 has own unpleasant issue https://github.com/stylus/stylus/issues/2534 annoyng on Node 14.

**Comment by fireph** [comment]
I am running into this issue as well and even after downgrading to 0.54.7 and using Node 12.21.0 I still cannot get embedurl to work 😥

**Comment by iChenLei** [comment]
Hi folks, Is still exist issue ?

**Comment by antonkai2k** [comment]
Version 0.57.0 - still not working. Somehow it simply replaces embedurl(...) to url(...) in resulting CSS

**Comment by antonkai2k** [comment]
> Version 0.57.0 - still not working. Somehow it simply replaces embedurl(...) to url(...) in resulting CSS

Weirdly in newly created project with same version this working. I think this issue can be closed.

**Comment by iChenLei** [comment]
Thanks for feedback.
