### ISSUE TITLE
style element if child has certain value / attribute / style

### ISSUE THREAD

**Issue by Gh3ttoKinG** [stylus/stylus#2553]
Hello,
I'm been searching a long while and couldn't find if it's possible.
I'm trying to style and element if the child (or more like the child's child) has a certain value, attribute or style.
HTML code is something like this:
<table>
  <tbody>
    <th>Name</th>
    <th>URL</th>
    <th>Value</th>
    <tr class="TableRepeaterHeader">
      <td>
        <span>SomeText</span>
      </td>
      <td>
        <a href="SomeLink">Link</span>
      </td>
      <td>
        <div style="color: #ff00ff">SomeValue</div>
      </td>
    </tr>
    <tr class="TableRepeaterHeader">
      <td>
        <span>SomeText2</span>
      </td>
      <td>
        <a href="SomeLink2">Link2</span>
      </td>
      <td>
        <div style="color: #dd77ee">SomeValue2</div>
      </td>
    </tr>
  </tbody>
</table>

And I'm trying to change the style of the `<tr>` element if the span element has text "SomeText" or the `<a>` element has the attribute `href*=Some_parrt_of_the_link` or the `<div>` element has the style `color:#dd77ee`

Is something like this possible?
So far I've only been able to color the child element itself with the following code.
```
tr.TableRepeaterHeader > td > a[href*="SomeLink"] {
  background-color: #ffa600 !important;
  color: #000000 !important;
}
tr.TableRepeaterHeader > td > div[style*="#ffffff"] {
  background-color: #ffa600 !important;
  color: #000000 !important;
}
```

**Comment by markfswe** [comment]
It can be achieved by using CSS `:has` selector. (Btw it is not supported by browsers yet)
Your issue is not related to stylus and css preprocessing at all. Please close issue.
