### ISSUE TITLE
Stylus freezes when importing styles?

### ISSUE THREAD

**Issue by NSExceptional** [stylus/stylus#2555]
The whole page just freezes and I get an hourglass mouse.

[Here are my styles](https://ghostbin.co/paste/p8hmq) if that helps. Using the latest version of the extension at the time of writing.

Edit: so the page isn't actually frozen as I can still interact with it, but I get the hourglass mouse after importing styles, and the import never completes.

Downgrading to `1.5.13_0` fixed this issue for me.

**Comment by vendethiel** [comment]
Wrong stylus.

**Comment by NSExceptional** [comment]
This is embarassing, I meant to post this on openstyles/stylus. My bad!
