### ISSUE TITLE
CSS value stored in hash does not work without colon

### ISSUE THREAD

**Issue by TokugawaTakeshi** [stylus/stylus#2558]
```
Colors = {
  primary: green,
  secondary: blue
}

.Test
  color Colors.primary
```

[🌎 Fiddle](https://stylus-lang.com/try.html#?code=Colors%20%3D%20%7B%0A%20%20primary%3A%20green%2C%0A%20%20secondary%3A%20blue%0A%7D%0A%0A.Test%0A%20%20color%20Colors.primary)

**Comment by vendethiel** [comment]
That's known and documented.

**Comment by TokugawaTakeshi** [comment]
@vendethiel Thank you for the response.
Would you please to share the link of appropriate page of documentation?

**Comment by vendethiel** [comment]
I can't seem to find it in docs now. But it's been asked many times here. So it should probably be added.

**Comment by TokugawaTakeshi** [comment]
@vendethiel, If so, would you please to share the link with the comment where explained the reason WHY this feature could not be fixed in the future?

**Comment by vendethiel** [comment]
#2357 #2336 #2239 #2208 #2054 #2016 #2010 #1920 #1888 #1738 #1713 #1680 #1644 #1405

**Comment by TokugawaTakeshi** [comment]
@vendethiel 
I checked some of above issues.
Does the algorithm below implementable? 

```
color a.b.c
```

1. Does `a` exist among variables? If no, consider it selector.
2. Is `a` the hash? If no, consider as selector.
3. If `a.b.c` has the valid CSS value, interpolate it.

Why I want it will be implemented is the code style unity.
One of amazing feature of Stylus is the minimalist syntax.

Syntactically we need the colon only when using the hash.
So the colon is conspicuous when basically it has not being used.

**Comment by vendethiel** [comment]
No, that'd mean mixing the parsing and evaluation phase, not possible.

**Comment by TokugawaTakeshi** [comment]
@vendethiel Understood. The verdict of this issue is:

This problem solving is impossible with current mechanism of parsing and evaluation.
Now way the Stylus contributors will re-write the core just for make the colon optional in all cases.
