### ISSUE TITLE
[bug] After using the lastest version, some build-in function can't be used.

### ISSUE THREAD

**Issue by ShaytonXu** [stylus/stylus#2560]
When I use the lastest version of stylus, something wrong when it compiled. `Cannot read property 'nodes' of undefined`
![image](https://user-images.githubusercontent.com/32198066/96741902-ea5f6380-13f4-11eb-86c5-fdacb03c0688.png)

Finally, I find that the `lighten` can't be found in [the functions' export file](https://github.com/stylus/stylus/blob/dev/lib/functions/index.js).
![image](https://user-images.githubusercontent.com/32198066/96742216-3a3e2a80-13f5-11eb-9e61-9919c0f0ae35.png)

And after I go back the version to @0.47 and the problem is not shown again.
The build-in function `mixin()` also has the same problem.

**Comment by iChenLei** [comment]
![2021-08-21 15 33 23](https://user-images.githubusercontent.com/14012511/130314451-fb617546-a71b-4298-bfe1-fd1ae33c16c6.png)

It work as expected. Which toolchain did you use ?

**Comment by iChenLei** [comment]
`lighten` function is a stylus mixin which defined in `functions/index.styl`

https://github.com/stylus/stylus/blob/73bd8dbcd48b63a95d6655ffd02c31ff06cc3f3a/lib/functions/index.styl#L132-L133
