### ISSUE TITLE
How to adjust the style file order?

### ISSUE THREAD

**Issue by gMan1990** [stylus/stylus#2565]
RT

**Comment by vendethiel** [comment]
What do you mean?
This might not be the right stylus repo.

**Comment by gMan1990** [comment]
@vendethiel If I have two style file named `a` and `b`, so we have two case:
```html
<body>
<div>text</div>
</body>
<!-- case 1 -->
<style id="stylus-a">div::after{content:"-a"}</style>
<style id="stylus-b">div::after{content:"-b"}</style>
<!-- case 2 -->
<style id="stylus-b">div::after{content:"-b"}</style>
<style id="stylus-a">div::after{content:"-a"}</style>
```
They display diff content, see: https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity

**Comment by vendethiel** [comment]
Wrong stylus repository.

**Comment by gMan1990** [comment]
@vendethiel
- Tampermonkey extension: can adjust the script file order in list page.
- Stylus extension: how?

**Comment by vendethiel** [comment]
Wrong stylus repository. This is not the stylus extension.

**Comment by vendethiel** [comment]
Wrong stylus repository. This is not the stylus extension.

**Comment by gMan1990** [comment]
https://github.com/openstyles/stylus issues/400
