### ISSUE TITLE
lower/uppercase support for String arguments?

### ISSUE THREAD

**Issue by doriandrn** [stylus/stylus#2566]
Hello,

I need to write a function that converts a string argument to lower/uppercase. I've found no way or workarounds to do this so far - it would be great to have these implemented as builtin functions (imo)!

Cheers!

**Comment by vendethiel** [comment]
You cam define them from JS in the meantime

**Comment by doriandrn** [comment]
Yup, thanks for the suggestion, I've already made a plugin for this meanwhile, pretty simple!

**Comment by iChenLei** [comment]
Glad to see you solved the issue.
