### ISSUE TITLE
Remove dep for css-parse

### ISSUE THREAD

**Issue by jnardone** [stylus/stylus#2569]
css-parse is a dumb package.  -> https://github.com/reworkcss/css-parse

all it does is:
`module.exports = require('css').parse;`

It hasn't been updated in 7 years, and it pulls in `css` anyway, so just pull in `css` into this library and stop using this.  This ALSO lets you move to css version 3.0.0, which fixes some old deprecations.

**Comment by vendethiel** [comment]
well, it's a holdover from when `css-parse` was actually parsing CSS, and not just that.

**Comment by muuvmuuv** [comment]
Yes please move to `css` directly to remove the deprecation warning from `urix` which is resolved in the latest `css` version.

**Comment by iChenLei** [comment]
Will release a new version later, PR #2554 for this issue.
