### ISSUE TITLE
In version 1.5.15, when "Turn all styles off" is unchecked, the page turns dark after a clicking on image or link. 

### ISSUE THREAD

**Issue by p3dr1ng** [stylus/stylus#2579]
Firstly, I want to thank the project team for this very useful Firefox extension, and have used it for a long time, even from its Stylish days. I have long used it with the theme "Global dark style - changes everything to DARK" from userstyles.org:
https://userstyles.org/styles/31267/global-dark-style-changes-everything-to-dark

In the latest version of Stylus (1.5.15), I have experienced the following issue: 
- The "Turn all styles off" is UNCHECKED in Stylus menu. 
- When navigating around a page, say clicking on an image or clicking on a link, the page darkens. 
- Reloading/refreshing the page sometimes un-darkens the page, other times not. 

Specific examples: 
1) ebay.com: view a specific item that comes with an image that can be zoomed in. When an image is clicked, the page is darkened. And when I press escape out of enlarged image and reload/refresh, then the page is un-darkened. 

2) arstechnica.com: when I click on an article's comment link, the page gets darkened. For example, the article in the following url: 
"https://arstechnica.com/science/2021/02/even-power-disasters-are-bigger-in-texas-heres-why/"
- click on "Reader Comments" link -> screen darkens
- reloading page does not un-darken page

The reason I report this issue is that I have not experienced it before until the latest update. And to help verify that it was indeed the latest version that was causing my issue: 
- I uninstalled the latest version (1.5.15), 
- I installed the previous version (1.5.13) along with the theme mentioned above, 
- I tested the same pages mentioned in 1) and 2) above, along with other sites (New York Times, Fox News, and BBC UK), and found no issues. 
- I also tested it on a portable Firefox install with Stylus being the only extension and have reproduced the same results: v1.5.15 results in darkening of page even with "Turn all styles off" is UNCHECKED, but with v1.5.13, I didn't encounter the issue. 

I hope that this report can help in addressing my issue and I thank you for your time.

**Comment by vendethiel** [comment]
Wrong stylus repo

**Comment by p3dr1ng** [comment]
My sincerest apologies.
