### ISSUE TITLE
support.mozilla.org - Could not communicate with the page?

### ISSUE THREAD

**Issue by Thermalzombie** [stylus/stylus#2580]
When using stylus on https://support.mozilla.org/ it cannot find a style and says could not communicate with the page.

Thanks for reading.

**Comment by vendethiel** [comment]
Wrong stylus repo.

**Comment by markfswe** [comment]
@Thermalzombie please close this issue. Open it in [openstyles/stylus](https://github.com/openstyles/stylus)
