### ISSUE TITLE
Waterfox Classic: problem to instal an userstyles?

### ISSUE THREAD

**Issue by decembre** [stylus/stylus#2588]
On my principal profile of Waterfox Classic 56.5, when i want install an userstyle from USw or USO,
By example for <a href="https://userstyles.world/style/34">Stylus Black Edition by BillyCool</a>

i have an error massage:
"Stylus a échoué à parser le usercss :
invalid regexp group"

Or on an other profile:
"Stylus a échoué à parser le usercss :
can't access lexical declaration `metaParser' before initialization"

I tested too with disable userscripts ...

On Chrome / Firefox Quantum , no problem.
Am i alone with this problem?

**Comment by vendethiel** [comment]
Wrong stylus repo.

**Comment by decembre** [comment]
Haa sorry , that's the wrong place !
I wanted report to the Stylus addon...
