### ISSUE TITLE
Lack of ability to change language

### ISSUE THREAD

**Issue by Shadow0013HUN** [stylus/stylus#2593]
Hi there,

I am facing an issue, where the program detected that I am using a hungarian chrome, but the hungarian translation is, to say the least, abysmal, it's half english, half hungarian. I would like to change it back to english.

In the settings menu, there is no such option. How could I do it?

Looking forward to your answers. :)

**Comment by markfswe** [comment]
Bruh.. Which program? This is not related to stylus at all. Please close issue

**Comment by markfswe** [comment]
Wrong repo maybe [openstyles/stylus](https://github.com/openstyles/stylus)

**Comment by Shadow0013HUN** [comment]
Stylus detected it. Bruh.
It has everything to do with Stylus. Bruh.
My Google Chrome Stylus UI is half hungarian half english.

Edit: Oh, on the official Chrome extension website, this GitHub page is linked, and not the openstyles/stylus.
Still, why the hell did you call this language the same as that program?

**Comment by vendethiel** [comment]
> Edit: Oh, on the official Chrome extension website, this GitHub page is linked, and not the openstyles/stylus.
> Still, why the hell did you call this language the same as that program?

stylus the language predates stylus the program

**Comment by markfswe** [comment]
@Shadow0013HUN close issue please. thank you
