### ISSUE TITLE
@import url() not working

### ISSUE THREAD

**Issue by Thomasan1999** [stylus/stylus#2595]
When I try to import Google Fonts or any external URL via `@import url('https://...')`, it throws an error: `Cannot read property 'isNull' of undefined`. 

### Example:
```
const stylus = require('stylus');
stylus(`@import url('https://fonts.googleapis.com/css?family=Raleway:300,400,500,700|Montserrat|Inconsolata:400,700&display=swap')`).deps();
```

It seems to be related to: https://github.com/stylus/stylus/blob/59bc665db295981d4e3f702e7275c5589a3c6d15/lib/visitor/deps-resolver.js#L113

### Workaround:
```
@css {
    @import url('https://fonts.googleapis.com/css?family=Raleway:300,400,500,700|Montserrat|Inconsolata:400,700&display=swap')`);
}
```
That way Stylus doesn't compile it and the error is not thrown.

### The original issue:
https://github.com/vitejs/vite/issues/3984

**Comment by yklydxtt** [comment]
i also got this problem
