### ISSUE TITLE
stylus is failed to sync from google.

### ISSUE THREAD

**Issue by ghost** [stylus/stylus#2598]
![image](https://user-images.githubusercontent.com/49443405/126853728-009e2c88-b8e2-4ab2-b179-e7cbac77d203.png)
I cant download all my styles from my google Drive.

**Comment by ghost** [comment]
```
Failed to fetch[401]: {
    "error": {
        "errors": [{
            "domain": "global",
            "reason": "authError",
            "message": "Invalid Credentials",
            "locationType": "header",
            "location": "Authorization"
        }],
        "code": 401,
        "message": "Invalid Credentials"
    }
}
```

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/49443405/126854103-2388ff9d-24a4-4ab4-b387-be9097668c8a.png)
i get it.
i have to go to google and disable permission for stylus and then reconnect it .

**Comment by iChenLei** [comment]
@kasusa This repo is not `Stylus` (chrome extension) !  It's `Stylus` (https://stylus-lang.com), as known as famous css preprocessor.
> https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne?hl=en

**Comment by markfswe** [comment]
@kasusa please close issue. you opened it in wrong repo
