### ISSUE TITLE
RE: Usage of debug@3.1.0

### ISSUE THREAD

**Issue by vsridhars** [stylus/stylus#2639]
**To reproduce:**

```styl
// code here
```

**Current behavior:**

The current version of the debug npm module is 4.3.2 and the 3.1.0 last release has been 4 years ago.
Vulnerability scanners have been reporting usage of older debug versions. 

Wanted to check if this package can also move up to the 4.3.x series usage.

**Expected behavior:**

**Environment information:**

- `stylus` version:
- `nodejs` version:

**Comment by iChenLei** [comment]
Will check it later.
