### ISSUE TITLE
error occured when import variables.

### ISSUE THREAD

**Issue by SparkElf** [stylus/stylus#2649]
![image](https://user-images.githubusercontent.com/58362707/147380859-4ecf0ce0-4500-4975-bec2-8d34ccd89dff.png)

```
@import '/src/common/variable.styl'
    .page
        background-color: #F4F5F5
        width: 100%
        height: 100%
        .optionBar
            position: fixed
            top: $headerHeight
```

 `$headerHeight = 5rem`

I want to extract a public variable file. Did I do anything wrong?Thank you for your answers.

**Comment by iChenLei** [comment]
```styl
@import '/src/common/variable.styl'
```

Please try to use correct relative path to import variable stylus file, thanks.

![2021-12-25 20 34 27](https://user-images.githubusercontent.com/14012511/147384893-ad57ab31-6743-422a-9cbc-acdd07842846.png)

> I try to reproduce your issue, but everything work as expected.

**Comment by SparkElf** [comment]
Thank you so much
