### ISSUE TITLE
Deprecation warning source-map-resolve

### ISSUE THREAD

**Issue by ChristopherBartalos** [stylus/stylus#2665]
I found some dependency issues related to https://github.com/angular/angular-cli/issues/22748. source-map-resolve seems to be deprecated that is used from the css dependency.

**Comment by iChenLei** [comment]
Thanks for deps issue report.

**Comment by anuj9196** [comment]
any update on it?

**Comment by e-oz** [comment]
What he can do, actually? This issue can be resolved only by the "css" package maintainers.

**Comment by doberkofler** [comment]
See https://github.com/reworkcss/css/issues/163

**Comment by iChenLei** [comment]
How about make `css` package be `optionalDependencies` or `peerDependencies` ? I think not many people use cli with `--css` to convert css to stylus. Any suggestions ?

> When people use `--css`, Hint people to install `css` manually .

**Comment by doberkofler** [comment]
> How about make `css` package be `optionalDependencies` os `peerDependencies` ? I think not many people use cli with `--css` to convert css to stylus. Any suggestions ?
> 
> 
> 
> > When people use `--css`, Hint people to install `css` manually .

Sounds good to me

**Comment by ChristopherBartalos** [comment]
> How about make `css` package be `optionalDependencies` os `peerDependencies` ? I think not many people use cli with `--css` to convert css to stylus. Any suggestions ?
> 
> > When people use `--css`, Hint people to install `css` manually .

yup this sounds good to me too

**Comment by Anutrix** [comment]
https://github.com/adobe/css-tools was created as replacement, forked from https://github.com/reworkcss/css.

It's published on npm(https://github.com/reworkcss/css/issues/163#issuecomment-1184633037) and it's MIT licensed. Maybe we can use this.

**Comment by FaisalAfroz** [comment]
@Anutrix I think it would be good idea to use https://github.com/adobe/css-tools because adobe has forked it due to low maintenance.
