### ISSUE TITLE
How to use the mode passed in

### ISSUE THREAD

**Issue by sunjunjie1314520** [stylus/stylus#2671]
![image](https://user-images.githubusercontent.com/34414647/160109179-584ee6bc-390a-40b3-9577-556e91e71089.png)

Please help me

**Comment by vendethiel** [comment]
You can use `lookup(mode + 'Color')` but I recommend using a hash instead.

**Comment by sunjunjie1314520** [comment]
3Q

**Comment by sunjunjie1314520** [comment]
文件已收到！谢谢！
