### ISSUE TITLE
heroku web service space is being added

### ISSUE THREAD

**Issue by Zedai00** [stylus/stylus#2672]
**To reproduce:**

```styl
tag
    height: 100vh
    width: 100vw
```

**Current behavior:**

While Using heroku web service aka `curl -F style=@style.styl http://styl.herokuapp.com -o style.css`
Space is being added between 100 and vh or vw
```
tag {
    height: 100 vh
    width: 100 vw
}
``` 

**Expected behavior:**

Space should not be added

**Environment information:**

- `stylus` version: 0.56.0
- `nodejs` version: v17.6.0

**Comment by iChenLei** [comment]
#### `http://styl.herokuapp.com` is not official stylus online compile services and stylus self work as expected.

![2022-03-25 21 25 30](https://user-images.githubusercontent.com/14012511/160129147-0dfd9be7-4a4f-4275-9de8-dbbefab80a56.png)
