### ISSUE TITLE
bin/stylus in npm packages contains windows style line endings

### ISSUE THREAD

**Issue by michael-mader** [stylus/stylus#2691]
**To reproduce:**

On Linux or Mac OS:
```
yarn add stylus@0.58.0
yarn run stylus                                                                                                                       
> yarn run v1.22.19
> warning package.json: No license field
> $ /Users/myuser/tmp/node_modules/.bin/stylus
> env: node\r: No such file or directory
> error Command failed with exit code 127.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Current behavior:**

In version 0.58.0 `bin/stylus` contains windows style  line endings (CRLF \r\n) which causes the stylus command to fail on mac or linux. I've read somewhere else that npm automatically converts those wrong line endings wheres yarn does not.

In version 0.57.0 the line endings are only single LF (\n) and everything is working as expected.

**Expected behavior:**

`bin/stylus` can be run on Linux via `yarn run stylus`

**Environment information:**

- `stylus` version: 0.58.0
- `nodejs` version: 14.17.6 (but that does not matter)

**Comment by iChenLei** [comment]
Thanks for your report, I will release a patch version to fix it (0.58.1). And add test for regression.
