### ISSUE TITLE
Color Palate and Search Function Fail to Work

### ISSUE THREAD

**Issue by geedogz** [stylus/stylus#2719]
**Current behavior:**
Clicking on a color icon fails to produce the color palate pop-up. And the search function doesn't pop up when I press Ctrl+F on the keyboard. 

**Expected behavior:**
I expect the color palate bubble to pop up upon clicking on the color icon. And I expect the search function to pop up upon using Ctrl+F.

**Environment information:**
- `stylus` version:  1.5.26
- `nodejs` version:  I don't know what this is.

**Comment by iChenLei** [comment]
@geedogz  goto https://github.com/openstyles/stylus

**Comment by geedogz** [comment]
Hey dude. I'm new here. I went to your link. But I dont know what youre wanting me to do exactly.

**Comment by iChenLei** [comment]
`stylus` is not `openstylus`. @geedogz 
stylus -> https://stylus-lang.com/
openstylus -> https://add0n.com/stylus.html
