### ISSUE TITLE
CssSyntaxError: Unclosed bracket

### ISSUE THREAD

**Issue by merndev-agile** [stylus/stylus#2770]
**To reproduce:**
After debugging into the css of react-datepicker found out that multiple not:() selector are cusing the issue.If I comment that css, Project complies without any error.I am using [postcss](https://www.npmjs.com/package/postcss) and [stylelint](https://www.npmjs.com/package/stylelint) in my project.

```styl
range:not(.react-datepicker_day--in-selecting-range,
.react-datepicker__month-text--in-selecting-range,
.react-datepicker__quarter-text--in-selecting-range,
.react-datepicker__year-text--in-selecting-range),
.react-datepicker_month--selecting-range .react-datepickermonth-text--in-range:not(.react-datepicker_day--in-selecting-range,
.react-datepicker__month-text--in-selecting-range,
.react-datepicker__quarter-text--in-selecting-range,
.react-datepicker__year-text--in-selecting-range),
.react-datepicker_month--selecting-range .react-datepickeryear-text--in-range:not(.react-datepickerday--in-selecting-range,.react-datepickermonth-text--in-selecting-range,.react-datepickerquarter-text--in-selecting-range,.react-datepicker_year-text--in-selecting-range) {
  background-color: #f0f0f0;
  color: #000;
}
```

**Current behavior:** 
Above CSS code which is causing the issue and throwing error "CssSyntaxError: Unclosed bracket" but code is a valid syntax.Below is the screenshot of error
![WhatsApp Image 2023-03-06 at 19 39 54](https://user-images.githubusercontent.com/121424822/223153950-671ed36f-f7e2-4b8b-a152-88a3568ad48e.jpeg)

**Expected behavior:**
App should compile with above css without any error

**Environment information:**

- `stylus` version: 0.59.0
- `nodejs` version: 16.16.0
- `postcss` version: 8.4.21
- `stylelint` version: 15.2.0

I created a ticket on postcss but as per them it might be issue with Stylus parser for PostCSS .
Below is the link of ticket 
https://github.com/postcss/postcss/issues/1818

**Comment by akhilpanchal** [comment]
To provide more details for the maintainers to look at this issue, the compiler produces wrong css for the kind of css written below that has a combination of multiple, multi-argument `:not` selectors.
This is reproducible on the stylus playground https://stylus-lang.com/try.html with the following code

```css
.foo:not(.a, .b),
.bar:not(.a, .b) {
	color: red;
}
```

The generated output is as follows:
```css
.foo:not(.a,
.b),
.bar:not(.a {
  color: #f00;
}
```
The closing bracket `)` for the second `:not` is missing.

**Comment by iChenLei** [comment]
duplicated https://github.com/stylus/stylus/issues/2770

**Comment by akhilpanchal** [comment]
@iChenLei 
Can you share the correct duplicate issue link. The issue you shared points to this same issue.
