### ISSUE TITLE
0.60.0 breaks basic type check

### ISSUE THREAD

**Issue by OktarinTentakel** [stylus/stylus#2820]
**To reproduce:**

```styl
$jig---config ?= null
if !($jig---config is a 'object')
	if jig---config is defined
		$jig---config = jig---config
	else if $JIG_CONFIG is defined
		$jig---config = $JIG_CONFIG
	else if JIG_CONFIG is defined
		$jig---config = JIG_CONFIG

if !($jig---config is a 'object')
	error('jig:globals | jig config is undefined or not a hash')
```

**Current behavior:**

the second "is a 'object'" test (above the error) fails due to "undefined" ("cannot perform is 'object' undefined"), which is very strange since $jig---config must be null or defined according to this setup

**Expected behavior:**

since "undefined" is definitely not an object, I'd expect the error to be thrown

**Environment information:**

- `stylus` version: 0.60.0
- `nodejs` version: 16.20

version 0.59.0 works as expected

**Comment by iChenLei** [comment]
@vixalien any idea ?

**Comment by OktarinTentakel** [comment]
Still happening in 0.61.0.

**Comment by vixalien** [comment]
I can confirm this error, but it doesn't seem to be introduced by `0.60.0`. I hence believe the statement "version 0.59.0 works as expected" is false.

Reproducing:

1. Create a project, I named mine `stylus-test` and initialize node with `yarn init -y`
2. Add stylus `yarn add stylus@0.59.0`
3. Create the following `index.js` file

```js
var stylus = require('stylus');


const value = `
$jig---config ?= null
if !($jig---config is a 'object')
	if jig---config is defined
		$jig---config = jig---config
	else if $JIG_CONFIG is defined
		$jig---config = $JIG_CONFIG
	else if JIG_CONFIG is defined
		$jig---config = JIG_CONFIG

if !($jig---config is a 'object')
	error('jig:globals | jig config is undefined or not a hash')
`;

stylus(value).render((err, css) => {
	if (err) {
		throw err;
	}
	console.log(css);
});

```

4. Run it

```
$ node index.js 
.../stylus-test/index.js:20
                throw err;
                ^

[Error: stylus:12:2
    8|  else if JIG_CONFIG is defined
    9|          $jig---config = JIG_CONFIG
   10| 
   11| if !($jig---config is a 'object')
   12|  error('jig:globals | jig config is undefined or not a hash')
--------^
   13| 

jig:globals | jig config is undefined or not a hash
] {
  fromStylus: true,
  lineno: 12,
  column: 2,
  filename: 'stylus',
  stylusStack: ''
}

Node.js v20.5.1
```

**Comment by OktarinTentakel** [comment]
@vixalien 0.59.0 definitely works and by the way, you proved my point above, since the error thrown is exactly what's expected, but the error above is a completely different problem

your example throws my custom error, as expected, but 60/61 throws "cannot perform is 'object' undefined", which is exactly the problem since 60/61 fails at parsing "if !($jig---config is a 'object')"

**Comment by vixalien** [comment]
sorry. It seems I misunderstood your problem.

I updated stylus to `0.61.0` and the error is still:

```
$ node index.js 
.../stylus-test/index.js:20
                throw err;
                ^

[Error: stylus:12:2
    8|  else if JIG_CONFIG is defined
    9|          $jig---config = JIG_CONFIG
   10| 
   11| if !($jig---config is a 'object')
   12|  error('jig:globals | jig config is undefined or not a hash')
--------^
   13| 

jig:globals | jig config is undefined or not a hash
] {
  fromStylus: true,
  lineno: 12,
  column: 2,
  filename: 'stylus',
  stylusStack: ''
}

Node.js v20.5.1
```

Is there something I'm not understanding?

**Comment by OktarinTentakel** [comment]
@vixalien no, that would be expected, which is weird, since I just tested the upgrade/downgrade half an hour ago

two differences here:

I do have $JIG_CONFIG = {} previously defined before hitting the check (in another file), which should result in no error anymore and instead $jig---config just being {}

and I still have to use node 16.20 in docker, since intel macs throw segfaults in docker, so my node lts is older then yours (and running in docker, which hopefully does not make a difference here)

**Comment by vixalien** [comment]
Thanks for explaining. It indeed seems the `$JIG_CONFIG = {}` was the missing thing. Since I can now reproduce the issue, I'll try to get to what caused it.

Thank you.

**Comment by OktarinTentakel** [comment]
Just checked out the new version, everything seems to work again. Thanks a lot!
