### ISSUE TITLE
Stylus preprocessor has problems with semicolon ";" in attributes in some cases

### ISSUE THREAD

**Issue by Atexor** [stylus/stylus#2842]
**To reproduce:**
Hi, there is similar issue to #2841 but not with regexp, but styles itself.

**Current behavior:**

In Stylus addon (Firefox/Chrome) create new userstyle with `@preprocessor stylus`. Paste:
```
#viewport > div > div[style^="background-color: rgb(252, 252, 255)"], [style^="background-color:#fff;"] {
 background-color: #2C2C2C !important;
}
```

In some cases there will be parsing issue. When I remove semicolon `;` in the end of attribute or `#viewport > ` in the beginning, error disappears:
![obraz](https://github.com/stylus/stylus/assets/34380553/13961f97-943e-43c3-95e5-676a5c422976)

I am unable to save a style due to that.

**Expected behavior:**

Parsing css should work in more complicated cases.

**Environment information:**

- `stylus` version: 0.60.0 (not sure of version used in addon).
- `nodejs` version: n/a

**Comment by iChenLei** [comment]
maybe you can use [@css](https://stylus-lang.com/docs/literal.html) as a workaround.

**Comment by iChenLei** [comment]
Duplicated https://github.com/stylus/stylus/issues/2841
