### ISSUE TITLE
vulnerable @adobe/css-tools

### ISSUE THREAD

**Issue by pumano** [stylus/stylus#2860]
```
@adobe/css-tools  <4.3.2
```
Severity: moderate
@adobe/css-tools Improper Input Validation and Inefficient Regular Expression Complexity - https://github.com/advisories/GHSA-prr3-c3m5-p7q2

**To reproduce:**

```styl
// code here
```

**Current behavior:**

vulnerable version of @adobe/css-tools

**Expected behavior:**

update @adobe/css-tools to latest version

**Environment information:**

- `stylus` version: latest
- `nodejs` version: 18 / 20

**Comment by pumano** [comment]
@iChenLei could you please release new version?

**Comment by iChenLei** [comment]
I'll be releasing a new version this week, please @ me if not happened : ) @pumano

**Comment by pumano** [comment]
@iChenLei warm reminder :)
