### ISSUE TITLE
[bug] Stylus Popup Too small (Wrong repo sorry) 

### ISSUE THREAD

**Issue by Ameer-Jamal** [stylus/stylus#2889]
![image](https://github.com/user-attachments/assets/f46a2fed-c7be-4afc-af8e-165b4e78bc32)

The popup does not have an adjustable height and is WAY too small by default so you cant control the settings style

**Comment by slightlyfaulty** [comment]
You're in the wrong repo my friend.

https://github.com/openstyles/stylus

**Comment by Ameer-Jamal** [comment]
Thank you @slightlyfaulty  and im sorry for the mistake!
