### ISSUE TITLE
Strong Caching Headers

### ISSUE THREAD

**Issue by bminer** [stylus/stylus#399]
The Stylus middleware relies on some sort of static file server middleware to serve up the compiled CSS file.  This is both unnecessary and unflexible.  For example, it would be much more efficient to combine CSS files into a single file, serve that file using URL fingerprinting, and send "strong" caching headers.  Ready for an example?

The HTML includes the CSS file like so...
`<link rel="stylesheet" type="text/css" href="/css/style.css?1315596267" />`

For this to work, Express views (or perhaps other middleware) would need to be provided the last modification date from the Stylus middleware.  Maybe set `app.local(...)` or `req.stylusLastModified`?

The query parameter is the URL fingerprinting at work.  It is the UNIX timestamp of the last modification date (or last compilation date) of the master CSS file.  Then, `/css/style.css` is served directly from the Stylus middleware, not from the static middleware.  This allows us to control the caching headers and so on.  The server response includes the `Expires` and `Cache-control: max-age` headers to tell the browser to cache the file for 1 year (the max recommended cache duration if you ask W3C).  The Stylus middleware should also set the `Last-Modified` header and check `If-Modified-Since` header in the request to allow Stylus to respond with 304, as appropriate.

Now, if the admin changes any *.styl file, Stylus automatically re-compiles the CSS bundle and serves it up.  The last modification date changes, so any new HTML pages now have the new query parameter.  Since the URL for the CSS file has changed, the browser knows to grab the latest version and ignore its cached version.

Ultimately, these changes would allow Stylus to implement "strong" and "weak" caching, serve up all CSS in one master file, and still allow changes to *.styl files to be made on-the-fly without any server restart.  I would be more than willing to make these changes to Stylus.  Would you accept a pull request from me?

More info: http://code.google.com/speed/page-speed/docs/caching.html
Similar pull request for Browserify project: https://github.com/substack/node-browserify/pull/71

**Comment by kizu** [comment]
I don't think this issue is still in Stylus' scope (with new utils like grunt, gulp etc.), so I'm closing it.
