### ISSUE TITLE
@import regular css

### ISSUE THREAD

**Issue by tj** [stylus/stylus#448]
we can:
- pull it in as a literal, untouched
- treat it the same as a .styl import, parsing it etc

**Comment by terion-name** [comment]
really need an option to treat imported css-files as styl :(

**Comment by alcalyn** [comment]
Yep, and when I'm doing

``` styl
.prefix
    @import "file-stylus"
    @import "file-css.css"
```

css rules in `file-stylus.styl` are well inside the `.prefix` class, but not rules in `file-css.css`.

Also I find it not obvious to pass the option `--include-css`, it should be the default.

**Comment by isaac-jordan** [comment]
I'm running into the exact issue @alcalyn outlined above (importing .css files inside a block import), and the block import isn't applied to the CSS file.

**Comment by sffc** [comment]
I don't understand why the CSS file isn't just interpreted as a Stylus file when importing, since Stylus syntax is a superset of CSS syntax.  If I change my CSS file to have a .styl extension, then everything works the way it should.
