### ISSUE TITLE
Add --check

### ISSUE THREAD

**Issue by mmozuras** [stylus/stylus#489]
This would make it easier (and it would run faster) for editors to add syntax checking. For examples of implementations, you can look at:

```
ruby -c
haml --check
```
I'm sure there are more.

I would be mostly interested in using this with [syntactic](https://github.com/scrooloose/syntastic), a great vim plugin by @scrooloose for syntax checking.

**Comment by kizu** [comment]
Linting and similar tasks shouldn't be hardcoded into Stylus. In 1.0.0 we would expose AST after parsing in a way it could be used by external linters, so I'm closing this issue.
