### ISSUE TITLE
Feature suggestion: _index.styl

### ISSUE THREAD

**Issue by ianstormtaylor** [stylus/stylus#513]
Might be nice to allow for underscored index.styl files so that they always are at the top of folders arranged alphabetically. Otherwise they intermingle with the real stylesheets.

Also, other thought: is it possible to make folders referenced that don't have an index.styl automatically import all the stylus files in alphabetical (or some other if you want) order? I often find my index.styl referencing everything in the folder. (Of course you'll still want it for the cases where the order of import matters, but would be more convenient when it doesn't)

**Comment by kizu** [comment]
We now have file globbing (the folder use case) and a lot of tools like grunt/gulp which you could use to create a custom builded for Stylus. Adding this to Stylus itself would be a feature creep.
