### ISSUE TITLE
Feature: auto-escape special-characters in selectors

### ISSUE THREAD

**Issue by jasonkuhrt** [stylus/stylus#523]
Large-scale css codebases need special class name patterns that provide better structure. For instance two white-paper-like sites on the topic:
- http://bem.github.com/bem-method/html/all.en.html
- http://smacss.com/

One major problem I see with these systems is the convoluted syntax, i.e.:
- smacss sugests to call layout styles like `.l-<class-name>` (http://smacss.com/book/type-layout)
- bem suggests to represent bem elements with a class like `<block-name>__<element-name>` or `menu__item`

Looking through either it is clear that expressive syntax is a real issue. Yet it shouldn't be since we can use any characters in our selector names!
- http://mathiasbynens.be/notes/html5-id-class  
- http://mothereff.in/css-escapes

We could create much nicer class naming systems with more characters. For instance if we wanted bem block-names to be indicated with a class name like `.@<block-name` we could write it like this in our css code:

```
.\@block-name
    color red

.\@block-name {
    color: #f00;
 }
```

Escaping our css selectors sucks and scares away a good idea. It's also error-prone to try and remember how to correctly escape every possible character. But there is a perfect solution: let stylus do the escaping for us! I'll rewrite the above code for example:

```
.@block-name
    color red

.\@block-name {
    color: #f00;
 }
```

I think this would be an awesome feature of stylus because it woud make an awesome feature of css available to the masses.

**Comment by kreo** [comment]
simple workaroud 
.{class}\\@xs
