### ISSUE TITLE
Feature idea/request: @override or @reset

### ISSUE THREAD

**Issue by mekwall** [stylus/stylus#534]
It would be awesome if we could have the ability to properly override/reset already defined rules. You might say that this is already possible by just setting a new value, which is all true but far from optimal.

    // this is located in foo.styl
    .foo
      color: #bbb;
      font-size: 14px;
      font-family: Verdana;

    // now we're in a new file, and import the rules from foo.styl
    @import foo

    // we don't want .foo to change font-size or font-family, but set the color to #ccc
    .foo
      color: #ccc;
      font-size: inherit;
      font-family: inherit;

The above will generate bad and bloated code that doesn't make sense to send to the client.

I wish we could have something like this instead:

    // this is located in foo.styl
    .foo
      color #bbb
      font-size 14px
      font-family Verdana

    // now we're in a new file, and import the rules from foo.styl
    @import foo

    // we don't want .foo to change font-size or font-family, but set the color to #ccc
    .foo
      @override // or @reset
      color #ccc

The `@override` or `@reset` will remove all rules before it that match the selector. We will now have a proper way to override/reset previously defined rules which in turn generates optimal code that makes sense. I.e. this will be handy when working with CSS frameworks that provide default values in rules that you wish to change. Instead of having to change the actual source, you would merely have to use the function in your own code which keeps it clean and simple.

Perhaps we could take it even further by passing an argument that tells the function which values to override.

    .foo
      @override color,font-family
      color #ccc
      font-family Arial

The above would remove any `color` and `font-family` values that were defined before it that matches that selector.

I welcome any feedback and critique!

**Comment by SevereOverfl0w** [comment]
:+1: I like the feature suggestions here. Less annoyed me at first with it's version of scope, but it actually works very well in practice. 
```less
@x: red;

body { color: @x; }

@x: blue;
```
Produces:
```
body { color: blue; }
```

It feels dirty at first, but when you compare the less versions of bootstrap to the sass versions. It comes ahead as a clean winner.

**Comment by kizu** [comment]
While I see how this feature would be handy, it is falling slightly out of the Stylus scope, as it fits more into the post-processing. It can be rather easily implemented now using something like PostCSS, and adding it to Stylus itself would be a feature creep, so I'm closing this issue.
