### ISSUE TITLE
selector names from variable

### ISSUE THREAD

**Issue by ghost** [stylus/stylus#596]
I am trying to create a set of helper classes for things like padding programatically.  
Example:  .pad1 .pad2 .pad5 .pad10 .pad15 .pad20 etc.

I was hoping to clean up some space in the sheet and just write a quick loop for this such as:
for i in 1 2 3 4 5 10 15 25 50
  .pad + i
    padding unit( i, px )

However i cannot seem to get the selector name to be treated as anything but a string

Stylus is awesome you guys do a great job, thanks alot!

**Comment by OEvgeny** [comment]
+1

**Comment by Panya** [comment]
@OEvgeny this is already documented [here](http://learnboost.github.io/stylus/docs/interpolation.html).

**Comment by OEvgeny** [comment]
Thanks, miss it.
