### ISSUE TITLE
Extending imported CSS

### ISSUE THREAD

**Issue by kevindente** [stylus/stylus#693]
I'm trying to do something that's not working, but I don't know if It's something that's supposed to work or not.

I'm trying @import a .css file into a .styl file (bootstrap in this case), and then .extend one of the styles from the CSS file in the .styl file. Is this supposed to work? I just get an error "Failed to extend <class>". Does extend only work with classes defined in .styl files?

**Comment by kentor** [comment]
Bummer. This is the only thing preventing me from using stylus. I like to extend css installed via npm
