### ISSUE TITLE
Add config to `package.json`

### ISSUE THREAD

**Issue by Zearin** [stylus/stylus#719]
According to the [documentation for npm](http://npmjs.org/doc/scripts.html#configuration), it’s possible to add configuration values in `package.json` that persist across upgrades.  

The user can tweak these values to their liking using `npm config set stylus:foo bar`.  

I would love it if Stylus added configuration option for the number of spaces for indentation (both for Stylus->CSS and CSS->Stylus).

**Comment by kizu** [comment]
I don't think we need this, seems like a feature bloat and slightly out of scope. However, if someone would point out to how other tools are using such functionality and propose a set of options for Stylus — feel free to reopen or send a PR!
