### ISSUE TITLE
Support custom units by desugering 123foo to foo(123)

### ISSUE THREAD

**Issue by tillda** [stylus/stylus#745]
While using a grid system, I often run into situations where I want to specify sizes, margins, paddings etc. by grid units. So far this is easy done by defining `gridUnits(int)` function and writing instructions like `margin-top: gridUnits(1)`.

I was thinking whether it would be possible to introduce alternative syntax `1gridUnits` or `1gu` that would mimic other css units such as `em`, `px` etc.

The rule would be: if a function `foo` exists, any unit definition in the form of `[number]foo` would be de-sugared to `foo(number)` and compiled after that.

**Comment by darsain** [comment]
Any progress on this? Wanted to use this in all of my new projects.

**Comment by kizu** [comment]
While I like the idea behind this issue, it fits more into the post-processing. It can be rather easily implemented now using something like PostCSS, and adding it to Stylus itself would be a feature creep, so I'm closing this issue.
