### ISSUE TITLE
String operation fails if string happens to be function name

### ISSUE THREAD

**Issue by lunelson** [stylus/stylus#782]
```
test(str)
    return str + ''
```

This test case will fail if I pass say `p` or `unit` as the argument, with an error of "Cannot call method 'slice' of null". 

Though this is strictly logical, I'd like to be able to get around this -- given that `p()` is both a function and the name of an html element it has potential for problems. Can this be fixed, or perhaps more expediently can anyone suggest how to modify the above code so that it will accept function names as strings and just treat them as such? 

P.S. I know I can pass it `'p'` instead of `p` but I'd like it to be able to handle the latter case, since it's part of a larger routine I'm doing where I can't put every argument in single quotes.

Thanks

**Comment by HamsterCoder** [comment]
I am not sure I have the same problem, correct me if I am wrong.

So if I have escaped class names in my .styl like so:

`
.foo\.bar {
  color: red;
}
`

Everything is compiled ok. But if I have a null as part of class name:

`
.foo\.null {
  color: red;
}
`

I get an error:

`
ParseError: /home/.../styles/test.styl:1:12
   1| .foo\.null {
-----------------^
   2|   color: pink;
   3| }
   4| 

expected "indent", got "null"
`

I am using stylus "^0.54.5" with gulp-stylus "^2.3.1"
