### ISSUE TITLE
A way to select immediate parent only?

### ISSUE THREAD

**Issue by lunelson** [stylus/stylus#802]
So here's an example of a situation I've run in to; the code looks like this

````
table {
	th, td {
		border: 1px solid black;
		thead &, tfoot & {
			border: none;
		}
	}
}
````
... and what I get is this
```
table th,
table td {
  border: 1px solid #000;
}
thead table th,
thead table td,
tfoot table th,
tfoot table td {
  border: none;
}
```
but what I wanted was this
```
table th,
table td {
  border: 1px solid #000;
}
table thead th,
table thead td,
table tfoot th,
table tfoot td {
  border: none;
}
```
is there a way to do this presently? I want to grab just the preceding frame of reference, not the entire chain of selectors

**Comment by kizu** [comment]
This would be possible with the partial references from the #1240 which would be most likely implemented at 1.0.0
