### ISSUE TITLE
CSS Selectors Level 4

### ISSUE THREAD

**Issue by buschtoens** [stylus/stylus#833]
There are new selectors, yay! :smile: Unfortunenately they don't all work with Stylus. Here are the issues.
- `E:not(s1, s2, ...)`
  ... now takes a comma-speperated selector list.
  Spec: [Negation](http://dev.w3.org/csswg/selectors4/#negation) and [Selector List](http://dev.w3.org/csswg/selectors4/#grouping)
  Issue: _Commas in brackets should not insert a line break._
  Safe to implement: Totally.
- `E:matches(s1, s2, ...)`
  ... takes a comma-speperated selector list.
  Spec: [Matching](http://dev.w3.org/csswg/selectors4/#matches) and [Selector List](http://dev.w3.org/csswg/selectors4/#grouping)
  Issue: _Commas in brackets should not insert a line break. `matches` needs to be added to the parser._
  Safe to implement: Totally.
- `E[foo="bar" i]`
  ... matches a `foo="bar"` attribute case-insensitively.
  Spec: [Case-sensitivity](http://dev.w3.org/csswg/selectors4/#attribute-case)
  Issue: _The space between the closing `"` and the `i` should not be trimmed._
  Safe to implement: Totally.
- `E /foo/ F`
  ... matches `F` when it's referenced by `E`'s attribute `foo`. 
  Spec: [Reference combinator](http://dev.w3.org/csswg/selectors4/#idref-combinators)
  Issue: _Selectors need to accept `/`._
  Safe to implement: Nope. They might replace this with a functional pseudo-class.
- `E! F`
  ... matches `E` when it contains `F`.  ("Parent selector")
  Spec: [Subjects](http://dev.w3.org/csswg/selectors4/#subject)
  Issue: _`!` should be allowed in selectors._
  Safe to implement: Yes. They will use the exclamation mark. They're just arguing about how.
- `E:dir(ltr)`
  ... matches `E` when it's direction is left-to-right.  (vice-versa for rtl)
  Spec: [:dir()](http://dev.w3.org/csswg/selectors4/#dir-pseudo)
  Issue: _`dir` needs to be added to the parser._
  Safe to implement: Totally.
- A bunch of further pseudo-classes and pseudo-functions
  ... that don't require any special markup.
  Spec: [Selectors Overview](http://dev.w3.org/csswg/selectors4/#overview)
  Issue: _These pseudo-classes need to be added to the parser._

I'm pretty sure that this are all incompatible/unimplemented new selectors.

**Comment by trmdi** [comment]
How about this now?
Adguard extension implemented these e.g. [:has()](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#pseudo-class-has)
I like to use these selectors but Stylus still hasn't implemented them.
