### ISSUE TITLE
Is there a way to get a substring of a string?

### ISSUE THREAD

**Issue by kizu** [stylus/stylus#887]
I found out that there are almost no ways to work with strings in stylus, and that's strange.

We can use addition, `match` and `join` on strings, but we don't have `substr`, `split` or at least simple `replace` functions. It would be nice to have them in Stylus.

**Comment by saulfautley** [comment]
How is this stuff not documented anywhere?? Is Stylus really just dead and we should wait around for Styl or be forced to use Less/Sass?

**Comment by Panya** [comment]
@saulfautley it's open source, man. Feel free to use whatever you want, or be more constructive and send a PR.

**Comment by saulfautley** [comment]
@Panya Not everyone who would like to use Stylus is a Node.js developer, nor should they need to be.

I am genuinely asking the devs if they recommend using Stylus as is, or if there are greener pastures ahead/elsewhere?

**Comment by Panya** [comment]
> Not everyone who would like to use Stylus is a Node.js developer, nor should they need to be.

You're asking about docs, you cannot write?

**Comment by kizu** [comment]
Stylus is ok, the latest release was around a month ago, so it is strange to speak about Stylus being dead.
