### ISSUE TITLE
CodeMirror Syntax Highlighting

### ISSUE THREAD

**Issue by TuckerWhitehouse** [stylus/stylus#917]
Hey,

I see you've already got a CodeMirror syntax highlighter written for use on the website in the try it now section. I was curious if you had considering submitting a pull request to CodeMirror to have your syntax highlighter included. Once included in CodeMirror I would like to submit a pull request to adobe brackets to enable syntax highlighting for .styl files.

**Comment by kizu** [comment]
There is now a stylus mode in CodeMirror, so I'm closing this issue.
