### ISSUE TITLE
selector statement expansion

### ISSUE THREAD

**Issue by jonni83** [stylus/stylus#981]
Is there a way to expand a selector statement with a range?  For example, suppose there are five classes associated with different list items (priority_1, priority_2, etc.) that all need to have the same property assigned.
The current CSS would look like:
```
li.priority_1, li.priority_2, li.priority_3, li.priority_4, li.priority_5 {
  font-weight: bold;
}
```
Currently, the stylus I would use:
```
li
  &.priority_1, &.priority_2, &.priority_3, &.priority_4, &.priority_5
    font-weight bold
```
or
```
li
for count in 1..5
  &.priority_{count}
    font-weight bold
```
However, what I'd like to do is simplify the statement using the already existing range expansion to read something like:
```
li
  &.priority_{1..5}
    font-weight bold
```
The brackets are just a suggestion for delineation.  I haven't found a way to do anything like this yet, so this may be a feature request.  There are several examples within the stylus guide that could benefit from this.  For instance, the [selector parent reference](http://learnboost.github.com/stylus/docs/selectors.html), which has the same statement applied to html.ie6, html.ie7, and html.ie8. 

I understand that this wouldn't usually be necessary when writing all the css for a site.  However, I run into this problem when using third-party javascript packages that come with their own css.    I prefer to extend the pre-packaged css with my own stylesheet rather than editing their's, especially since I prefer writing stylus instead of css.

**Comment by kizu** [comment]
I don't think we need something like that in Stylus from the box — it is a rather rare case and could be completed using mixins:

```styl
expandSelector($selector, $array)
  $result = ()
  for $number in $array
    push($result, $selector + $number)
  $result = join(',', $result)
  return $result

li
  {multiplySelector('&.priority_', 1..5)}
    font-weight bold
```
